### ISSUE TITLE
Release end of May

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#101]
We need first release some external package:
  * moutainsort
  * tridesclous
  * heardingspike

And then release spikeextractor and spiketoolkit at the same time for Jeremy.

**Comment by colehurwitz31** [comment]
We are aiming for end of may for these releases, right?

**Comment by samuelgarcia** [comment]
Yep.
I will do a release of tridesclous very soon. I swear it!!

**Comment by colehurwitz31** [comment]
Herdingspikes as well!

**Comment by samuelgarcia** [comment]
You must swear it.

**Comment by alejoe91** [comment]
@colehurwitz @samuelgarcia @mhhennig what is left to do?

Are the HS and TDC releases out?

**Comment by samuelgarcia** [comment]
No. Sorry.
Let's say I do it today when kids are sleeping.

**Comment by samuelgarcia** [comment]
tridesclous 1.1.0 is released.
@colehurwitz @mhhennig : do you think you could release soon HS2 ?
So travis would be tested again the github version but the pypi one.

I think that 
pip install ml_ms4alg 
in travis.yml should also have a fixed version.

**Comment by alejoe91** [comment]
Is HS2 released?? @mhhennig @colehurwitz @martinosorb

**Comment by martinosorb** [comment]
Yes. But I need to run a couple more tests and I'll make a release that's compatible with python 3.5 (currently only 3.6).

**Comment by martinosorb** [comment]
All good now on my side.

**Comment by alejoe91** [comment]
what's the pip install? I'll add it on travis

**Comment by martinosorb** [comment]
`pip install herdingspikes`
