### ISSUE TITLE
Joblib should not be use when n_job=-1

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#108]
Maybe I have miss something.
In my mind, using joblib was optional and not imposed.
In current implement, **do_matching** always use the joblib.Parralell.
I think this is a mistake because joblib have problem when object are not pickelable.
It happens very oftens.

```
AttributeError: Can't pickle local object 'do_matching.<locals>.match_spikes'
```

jiblib is very cool be the use should be totally optional and a standard loop should be used instead. there are many situation we do not want parralel:
  * another parral machinery is already done at another level.
  * pickle problem
  * ...

I propose to do this always:
```python
if n_jobs=-1:
    for e in loop:
        ...
else:
     results = Parallel(n_jobs=n_jobs)(delayed(...))
```

**Comment by samuelgarcia** [comment]
Another thing joblib do not work well with closure (function inisde a function).
So Ipropose to also move **match_spikes()** outside the **do_matching()**

**Comment by colehurwitz31** [comment]
I think n_jobs=-1 is supposed to imply that all the cores are being used?

**Comment by samuelgarcia** [comment]
I did not explore joblib sources but I have this:
```AttributeError: Can't pickle local object 'do_matching.<locals>.match_spikes'```
meanning taht even with n_jobs=-1 there some pickle at some level.

I think this is saffer to keep loops explicitly.

**Comment by samuelgarcia** [comment]
See change in # 109
