### ISSUE TITLE
export to phy for GUI

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#12]
I think this belongs to spiketoolkit rather than spikeinterface, because many things need to be computed in order to launch the phy GUI.

I think the easiest thing would be using the template-GUI that KiloSort and SpykingCircus use because:
- files are well documented (https://phy-contrib.readthedocs.io/en/latest/template-gui/)
- it doesn't require from us to write a new plugin for phy (e.g. KwikGUI, or template-GUI)

We could have implement:
`st.exportToPhy(recording, sorting, save_folder)`

That allows then to call:
`phy template-gui save_folder/params.py`
and after the changes in Phy, we need a SortingExtractor `PhySortingExtractor`.

This would standardize manual curation too!

What do you guys think? @magland @colehurwitz31 @jamesjun

**Comment by magland** [comment]
Seems reasonable to me.

**Comment by jamesjun** [comment]
That's a great idea. There are many who is using phy for manual interface. It used to be significantly slow for high-channel count probes but I am not sure if the have made improvements.

**Comment by colehurwitz31** [comment]
+1

**Comment by alejoe91** [comment]
Won't close this because I need to fix the template scaling in the GUI..but for the rest it works :)

995df7f56a9ca94522f3f65c3100b8576194f88b
