### ISSUE TITLE
Align semantic and formula to wikipedia

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#123]
We have some performance label:
_perf_keys = ['tp_rate', 'fn_rate', 'cl_rate','fp_rate',  'accuracy', 'sensitivity', 'precision',
              'miss_rate', 'false_discovery_rate']

This wikipedia https://en.wikipedia.org/wiki/Sensitivity_and_specificity is sligtly different.
What is the story of formula in spiketool.comparison ?

**Comment by samuelgarcia** [comment]
And here https://en.wikipedia.org/wiki/Confusion_matrix

**Comment by samuelgarcia** [comment]
I think we should align to wikipedia semantic and formula so the doc could just could be a link to theses page. No ?

**Comment by alejoe91** [comment]
I don't remember when tp_rate fp_rate etc were added to the picture. In the original paper in which I used them (https://www.researchgate.net/publication/328392258_Independent_Component_Analysis_for_Fully_Automated_Multi-Electrode_Array_Spike_Sorting) I only used accuracy, sensitivity, precision and misclassification rate.

I think it makes sense to keep those and add false disc rate. Anything else uses tn and we don't have true negatives

**Comment by alejoe91** [comment]
In fact in our formulation tp_rate and accuracy should coincide perfectly from the formula

**Comment by alejoe91** [comment]
No maybe that's not true :)

In my opinion we can keep:
- accuracy
- specificity 
- precision
- false discovery rate
- miss rate
- misclassification rate

**Comment by colehurwitz31** [comment]
What’s wrong with tp_rate?

**Comment by alejoe91** [comment]
Tp_rate is the same as sensitivity
