### ISSUE TITLE
Question/feedback how SNR is compute

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#124]
@alejoe91 @colehurwitz31 @mhhennig 
I reading the code on how the the SNR is computed in qualitymetrics.

Some questions/feedback:
  * I don't see any filtering step, how can estimate the SNR on the full band ?
  * the std is not robust at all to estimate the noise, we need to use MAD. The std is bias with the 
    spike rate.
  * the full signal duration is used to estimaded the noise (std/mad), it is useless if the noise is 
    stable, 30s of signal is enough because mad is robust. It will be faster.
  * the amplitude is computed as max(template) - min(template), I think we should keep 
    max(template) is peak is positive and abs(min(template)) is peak is negative
  * for amplitude the recording need also to be taken on high pass signal other wise it is a 
    mistake.
  * template are computed with all spikes, this is tottaly unsane for memoery and CPU.
  * template are computed with np.mean they must be computed with np.median.

I think we need to fix this before the release. The SNR estimation is weak in actual state.

**Comment by colehurwitz31** [comment]
I agree on these issues. I did not implement the templates or the SNR so I am not sure completely how they work. Alessio would have a better idea of why he implemented them the way he did.

**Comment by alejoe91** [comment]
Hi Sam :) @magland implemented it. I agree with those changes.

- We can add an optional filtering step, which can be only HP
- I agree MAD should be used 
- we can use 30 second snippet
- Ok for using: abs(min(template))
- Templates can be easily computed with less waveforms by using the arg `max_num_waveforms` (already implemented)
- yeah median should be more robust

Let's implement those changes ;)

**Comment by samuelgarcia** [comment]
I am not sure to have time just now to do it.
I would prefer fisrt finish the actual PR.
Clean launcher and make more easier to use.







And get better benchmark for tdc.... :(

**Comment by colehurwitz31** [comment]
@alejoe91 Could you possibly implement these changes?

On a separate note, the GUI is coming along and an alpha version should be available soon for people to try.

**Comment by alejoe91** [comment]
@samuelgarcia BTW right now actually the snr was estimated only on 1000 samples!

I will set 10 seconds as default

**Comment by samuelgarcia** [comment]
Oups. I di not see it.
Where is it in the code ?

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/126

**Comment by alejoe91** [comment]
@samuelgarcia https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/qualitymetrics.py#L47
Now it uses 10 seconds by default, but it can be passed as an arg. See PR
