### ISSUE TITLE
Break the circular dependency.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#130]
@alejoe91 @magland @colehurwitz @mhhennig 
I think there is a design problem :)

spikeinterface should depend on fixed version of ml_ms4alg and heardingspike.
But ml_ms4alg and heardingspike also depend on fixed version of spikeinterface.

This circular dependency should be broken because we could theorically have a blocade at relase time. Who release first spiekinterface or ml_ms4alg ?

spikeinterface have 2 purposes:
  * propose utility for spike sorting (filtering,  ...) for some package that adopt the API (HS, 
     moutainsort, ...)
  * compare sorter

This 2 purpose create a circular dependency inevitably, no ?

**Comment by mhhennig** [comment]
HS actually does not have a dependency yet, it does not import spikeextractors/toolkit. But my plan is to integrate both soon. In this case, HS would explicitly depend on the latest (or a previous release), so SI can be developed without breaking HS. The release schedule should thus solve these issues (I hope).

**Comment by samuelgarcia** [comment]
OK thanks for clarification.
I was thinking wring.
But we need a quite fast release cycle each time there is a change in naming and api.
