### ISSUE TITLE
get_result_from_folder fails when given a string for the output_folder (for klusta, but possibly others)

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#143]
It appears that when I pass a string into the get_result_from_folder method of a sorter, it throws as error (due to: 'output_folder /  string').

I have to wrap the output_folder path in a Path object to make it work. Is this intended behaviour?

Example:

This fails:
```python
sorting = klusta.get_result_from_folder(output_folder="result_klusta")
```
This works:
```python
sorting = klusta.get_result_from_folder(output_folder=Path("result_klusta"))
```

**Comment by samuelgarcia** [comment]
It is a bug : it should be done inside the get_result_from_folder.
I think the same occur in several place.

**Comment by alejoe91** [comment]
@samuelgarcia can you fix it?

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spikesorters/pull/25

**Comment by alejoe91** [comment]
fixed and merged https://github.com/SpikeInterface/spikesorters/pull/25
