### ISSUE TITLE
Bug in Spyking-circus notebook

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#16]
When I run the spike sorting function for spyking circus, I get this error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-76c76043ef33> in <module>
     14         electrode_dimensions=[1,2],
     15         whitening_max_elts=1000,  # I believe it relates to subsampling and affects compute time
---> 16         clustering_max_elts=10000,  # I believe it relates to subsampling and affects compute time
     17         )

~/miniconda3/envs/spiketoolkit/lib/python3.7/site-packages/spiketoolkit/sorters/spyking_circus/spyking_circus.py in spyking_circus(recording, output_folder, probe_file, file_name, detect_sign, adjacency_radius, spike_thresh, template_width_ms, filter, merge_spikes, n_cores, electrode_dimensions, whitening_max_elts, clustering_max_elts)
     45     if probe_file is None:
     46         si.saveProbeFile(recording, join(output_folder, 'probe.prb'), format='spyking_circus', radius=adjacency_radius,
---> 47                          dimensions=electrode_dimensions)
     48         probe_file = join(output_folder, 'probe.prb')
     49     # save binary file

~/miniconda3/envs/spiketoolkit/lib/python3.7/site-packages/spikeinterface/tools.py in saveProbeFile(recording, probe_file, format, radius, dimensions)
    163                                      "'location' property to save .csv probe file")
    164     elif probe_file.endswith('.prb'):
--> 165         _export_prb_file(recording, probe_file, format, radius=radius, dimensions=dimensions)
    166     else:
    167         raise NotImplementedError("Only .csv and .prb probe files can be saved.")

~/miniconda3/envs/spiketoolkit/lib/python3.7/site-packages/spikeinterface/tools.py in _export_prb_file(recording, file_name, format, adjacency_distance, graph, geometry, radius, dimensions)
    239                                   for chan in range(recording.getNumChannels())])
    240             if dimensions is not None:
--> 241                 positions = positions[:, dimensions]
    242         else:
    243             print("'location' property is not available and it will not be saved.")

IndexError: index 2 is out of bounds for axis 1 with size 2

**Comment by colehurwitz31** [comment]
I still run into this issue when running it on the toy dataset after removing electrode_dimensions:

| Step "filtering" failed for reason Command '['mpirun', '-x', 'LD_LIBRARY_PATH', '-x', 'PATH', '-np', '24', 'spyking-circus-subtask', 'filtering', '/afs/inf.ed.ac.uk/user/s17/s1727843/spiketoolkit/examples/spyking_circus/recording.npy', '24', '0', 'False']' returned non-zero exit status 1.!

| Step "merging" failed for reason Command '['mpirun', '-x', 'LD_LIBRARY_PATH', '-x', 'PATH', '-np', '24', 'spyking-circus-subtask', 'merging', '/afs/inf.ed.ac.uk/user/s17/s1727843/spiketoolkit/examples/spyking_circus/recording.npy', '24', '0', 'False', 'None']' returned non-zero exit status 1.!

**Comment by alejoe91** [comment]
it's probably an mpi-related problem..can you try: `conda install -c mpi4py openmpi`. Should work ;)

**Comment by alejoe91** [comment]
Hi @ivan-pi, the problem is usually the mpi installation...

There are some known issues with openmpi (https://groups.google.com/forum/#!searchin/spyking-circus-users/mpirun$20error%7Csort:date/spyking-circus-users/sYYU_xJLAp4/_oDM2JmCAAAJ)

Can you check the mpi version? `mpirun --version`

Cheers
Alessio

**Comment by alejoe91** [comment]
@ivan-pi can you also try a:
`pip install pyqt5` ?
