### ISSUE TITLE
New idea : create a gtstudy submodules

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#167]

**Comment by samuelgarcia** [comment]
I have started a very basic worflow to run many GT files with many sorter and make results more automatic. And avoid writting nobebbok with lot of loops.

All this is in st/comparisons/groundtruthstudy.py

I would like, if you where ok, to make some separated module for this.
The name would "gtstudy" or "groundtruthstudy" or something similar.

  * comparison would more the algo for comparison
  * gtstudy would be more the framework.

The main motivatio is that with using SortingComparisona and GroundTruthComparison need to have evrything in memory. With many recording and sorting object it is becoming very heavy because of the memory footprint.

So the idea is to make persistent in folder some intermediate results.
Now only the sorting outptu is stor in npz format but we could make more : save counting, save matching, perf tables.

For this a clear separte module would be better.

@alejoe91 @mhhennig @colehurwitz what do you think ?

let talk about this at the workshop.

**Comment by colehurwitz** [comment]
Sounds interesting! Let's talk about it for sure at the workshop. I am not sure how much overlap that would have with spikeforest, but something to discuss for sure.

**Comment by samuelgarcia** [comment]
There is not really an overlap. Sf could even use it.
SF have a machinery with distant computing.
Here the topic is to run locally a full "study" and get result with fancy functions.
