### ISSUE TITLE
Change the matching logic when GT.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#173]
As discuss with Jeremy in Edimburgh, we should change the matching logic in the context of ground truth.

**Comment by samuelgarcia** [comment]
Accepted.
@magland : could you show me where is it done in SF ?

**Comment by samuelgarcia** [comment]
#194 : now the counting is based on the best match.

**Comment by colehurwitz** [comment]
Great!

**Comment by alejoe91** [comment]
@samuelgarcia I believe that in the spikeforest implementation they used the linear assignment (https://github.com/flatironinstitute/spikeforest/blob/master/spikeforest/spikeforest_analysis/sortingcomparison.py#L230).

With the new implementation they are using the compare_sorter_to_ground_truth, so the changes should be propagated automatically (https://github.com/flatironinstitute/spikeforest/blob/master/spikeforest/spikeforest_analysis/compare_sortings_with_truth.py#L31).

**Comment by samuelgarcia** [comment]
SF use linear assignment but for counting they use best match.
In short linear assignment is computed for nothing at the end.
But I like the idea of having in the same class the 2 mactch in parralel (best and linear assignement)
