### ISSUE TITLE
Adding mountain tools quality metrics for curation

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#176]
For one of the upcoming papers, we need to have the quality metrics from the mountainsort algorithm. I think these metrics could be implemented as two different quality metrics in the validation submodule and then I would be able to use those metrics to create threshold postprocessing extractors in the post-processing module.

So far, quality metrics return a list of scores where each entry is the score for a unit id. I use this list in the postprocessing modules to exclude units below a certain threshold.

@magland

**Comment by colehurwitz** [comment]
Hey @magland , so we are looking into including these metrics into SpikeInterface as both quality metrics and as curation tools in the near future. Do you think you would have time to work on this?

**Comment by alejoe91** [comment]
@colehurwitz still need this? https://github.com/SpikeInterface/spiketoolkit/pull/417

**Comment by colehurwitz** [comment]
I think this is not needed for now.
