### ISSUE TITLE
Create curation module

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#178]
Move the CurationSortingExtractor and the automatic curation tools (max_ISI, min_num_spikes, min_SNR) here.

**Comment by colehurwitz** [comment]
I can do this. However, that removes quite a bit from the postprocessing module. Not sure the best use of the postprocessing module then. Maybe we could break you postprocessing tools into multiple files then?

**Comment by alejoe91** [comment]
The postprocessing module has the postprocessing tools.
They allow to get waveforms, templates, max_channels, compute_pca, export to phy etc.

I think it's fine :)

**Comment by colehurwitz** [comment]
Sure, I think that is fine as well. I think it might be nice to break those into separate files now. Otherwise, postprocessing is a folder with only one python file!

**Comment by colehurwitz** [comment]
I will move things into curation now though

**Comment by alejoe91** [comment]
I think it's ok as the users won't know :)

**Comment by colehurwitz** [comment]
Fair enough. I think devs will care, however.

**Comment by alejoe91** [comment]
I think it's actually better to have a single file. Many functions call other functions internally: e.g. get_templates calls get_waveforms, get_max_chan calls get templates, compute pca calls get_waveforms, export to phy calls them all. The imports would become too complicated

**Comment by colehurwitz** [comment]
Not if they all import from the postprocessinglist ;)

**Comment by alejoe91** [comment]
@colehurwitz do you think it's worth it having a "Curation module" page in the docs?

**Comment by colehurwitz** [comment]
Yeah, I can do this. I just need to port over the curation one I did in the spikeextractors docs
