### ISSUE TITLE
Export to phy fails when no units found

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#185]
When no units are found (or all the units are curated), export to phy fails when trying to get PCs. What is an elegant way for export to phy to handle this case? We will run into an issue this when trying to create pipelines.

**Comment by alejoe91** [comment]
We can just check that len(unit_ids) > 0 and raise an error otherwise. Can you do that?

**Comment by colehurwitz** [comment]
Can we save to phy even with zero units? Like save part of the recording or something? Or should we just throw an error?

**Comment by colehurwitz** [comment]
I can make the first change if that is what we decide on

**Comment by alejoe91** [comment]
you could save the RecordingExtractor related stuff, nothing related to units.

**Comment by colehurwitz** [comment]
I wonder if that is better than just throwing an error... not sure myself.

**Comment by alejoe91** [comment]
mmm I don't see any use of exporting to phy if there are no units

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/186
