### ISSUE TITLE
Unification of all of SpikeInterface into one repository

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#198]
I know we have discussed this before, but after seeing how we could separate the development of spikesorters from spiketoolkit, I have an idea on how to make using this framework simpler for new users. Idea: We can separate our work into two conceptual groups: development packages and usage packages.

**Development packages (what we develop and other developers can utilize):**
_spikeextractors_ - File IO
_spiketoolkit_  - Preprocessing, postprocessing, curation, comparison, validation
_spikesorters_ - wrapped sorters
_spikewidgets_ -- visualization tools

**Usage packages (what experimentalists and users might want to use):**
_spikeinterface_ -- module for running all development packages
_spikely_ -- GUI for running all development packages 

In this workflow, we would have something like this for the spikeinterface package,

```
spikeinterface.extractors -- exposes all code from spikeextractors
spikeinterface.preprocessing -- exposes all code from spiketoolkit
spikeinterface.sorters -- exposes all code from spiketoolkit
spikeinterface.postprocessing -- exposes all code from spiketoolkit
spikeinterface.curation -- exposes all code from spiketoolkit
spikeinterface.comparison -- exposes all code from spiketoolkit
spikeinterface.validation -- exposes all code from spiketoolkit
spikeinterface.widgets -- exposes all code from spikewidgets
```

and **the user would only use spikeinterface** for their work. As developers, we could work on each development package separately so we would focus on development packages.

**Old way of getting started with spikeinterface:**

```
pip install spikeextractors spiketoolkit spikewidgets
```

```python
import spikeextractors
import spiketoolkit
import spikewidgets

recording = spikeextractors.MDARecordingExtractor('path_to_mda_folder')
recording_bpf = spiketoolkit.preprocessing.BandpassFilter(recording)
sorting =  spiketoolkit.sorters.run_klusta(recording_bpf)
widget = spikewidgets.UnitWaveformsWidget(recording_bpf, sorting)
```

**New way of getting started with spikeinterface:**

```
pip install spikeinterface
```

```python
import spikeinterface

recording = spikeinterface.extractors.MDARecordingExtractor('path_to_mda_folder')
recording_bpf = spikeinterface.preprocessing.BandpassFilter(recording)
sorting =  spikeinterface.sorters.run_klusta(recording_bpf)
widget = spikeinterface.widgets.UnitWaveformsWidget(recording_bpf, sorting)
```

If we were to implement this idea, it would have to be now as we are yet to release the paper. I think current software using spikeinterface wouldn't have to change much as they can still use each development package separately (**spikeforest can still use spikeextractors and spiketoolkit and spikesorters as standalone packages**), but I think users would migrate towards only using spikeinterface.

I want to stress that we wouldn't have to change almost any of the code we have created since **spikeinterface would just be a wrapper package for all our development repositories**. Having one package for users would would dramatically simplify the usage and documentation of our framework in general while not changing the developer experience.

Thoughts @samuelgarcia @magland @mhhennig @alejoe91 ?

**Comment by alejoe91** [comment]
Hi @colehurwitz, I see your point but I like the way it is and I don't think it's too hard. I like the separation of spikeextractors, toolkit, and widgets which have pretty defined scopes. Maybe instead of what you propose I would favor having extractors, toolkit, widgets, but still I kind of prefer the way it is.

We could have a spikeinterface package which installs the other repos and place the docs there. But let's see what the others say. We should discuss via Hangouts some time next week.

Also I think that SpikeInterface is already a much simpler API than anything else around, so I would not worry about scaring users off..

**Comment by colehurwitz** [comment]
@alejoe91 Good points! I think the idea stems from when I talked with experimentalists and they looked at the 3-4 packages and were a bit confused on where to start. Also, I think importing separate packages for File IO and analysis is a bit of an artificial separation. 

Basically, I think spikeinterface can do for the development repositories what spiketoolkit did for spikesorters where it allows you to access _all_ the code in the repositories.

**Comment by magland** [comment]
Sounds like you want to make it easier for a certain type of user to get started. I can see the advantage of simplifying it like that, but there are also disadvantages. From a development perspective (and giving us the flexibility to evolve the project over time) it's better to keep things separate when possible. My vote is to keep it as it is for now.

**Comment by mhhennig** [comment]
I also see the point, but quite like how it is at the moment (I just got used to it). The separation offers flexibility, for example I can use the extractors alone also for data analysis, just to read sorted spike trains. I wold also vote to leave it as it is, and perhaps a new approach to documenting the software could help. 
I'm thinking of a website where the landing page gives a choice to go on to different use cases (e.g. experimenter wanting to sort, lab creating a pipeline, coder wishing to see the full API reference).
How about that?

**Comment by colehurwitz** [comment]
Ok, I think you guys are all making more sense than me here. We should keep it as is and maybe just add a unified read the docs or something. Thanks for the discussion!

**Comment by samuelgarcia** [comment]
Personnally, I like the idea the idea of a meta package spikeinterface.

I my mind the way it is is over modularized from the user point of view. We need to memorize or search for copy/paste for eavry line of code.

From the dev point of view, I am very happy to have this super split we can release each package at different speed without breaking any thing.

So if we would have a metapackage I would vote:
  * slow release (one or twice a year max!)
  * release would have fixed dependency with other 4 packages
    like a distro
  * everything would be flatten in the pacakge
    ```python
    import spiekinterface as si
    si.MDARecordingExtractor(...)
    si.run_klusta(...)
    si.GrounTurthComaprison(...)
    ```
    but here I am pretty sur to have zero concensus :)

**Comment by colehurwitz** [comment]
I am reopening this issue just in case people have a different view of the issue based on Samuel's comments. I think the split could potentially benefit developers and users as well and wouldn't change functionality :)

**Comment by colehurwitz** [comment]
Round 2 anyone? ;)

**Comment by alejoe91** [comment]
I suggest:

```
si.extractors
si.toolkit (preprocessing, postprocessing, validation, curation)
si.sorters
si.comparison
si.widgets
```
@magland @mhhennig @samuelgarcia are you ok with this?

If so, @samuelgarcia can you make the meta package? :)

**Comment by samuelgarcia** [comment]
OK for me the only doubt I have is the place of curation even if this is the more intuitive place

**Comment by samuelgarcia** [comment]
I can do it but we need to finish the discussion in #203. Lets wait Jeremy and Matthias.

**Comment by samuelgarcia** [comment]
@alejoe91 : are you also OK to have everything flatten also ?
si.*

**Comment by colehurwitz** [comment]
I think curation is a form of data processing (low level).

I would strongly suggest this module structure though:

```
spikeinterface.extractors -- exposes all code from spikeextractors
spikeinterface.preprocessing -- exposes all code from spiketoolkit
spikeinterface.sorters -- exposes all code from spiketoolkit
spikeinterface.postprocessing -- exposes all code from spiketoolkit
spikeinterface.validation -- exposes all code from spiketoolkit
spikeinterface.curation -- exposes all code from spiketoolkit
spikeinterface.comparison -- exposes all code from spikecomparison
spikeinterface.study -- exposes all code from spikecomparison
spikeinterface.widgets -- exposes all code from spikewidgets
```

I think users/developers should expect each module to contain a different conceptual part of the spike sorting pipeline. Having a toolkit module doesn't reflect that.

I don't think having a flattened version would harm anything, so I am ok with it.

**Comment by alejoe91** [comment]
Actually I would prefer submodules. I think that otherwise it might become more confusing...

**Comment by colehurwitz** [comment]
We could have both though @alejoe91 . I wouldn't use the flattened version myself, but some people might like it.

**Comment by samuelgarcia** [comment]
@colehurwitz 
I prefer the version of alessio + flatten at the same time
```
si.extractors
si.toolkit (preprocessing, postprocessing, validation, curation)
si.sorters
si.comparison
si.widgets
```
This avoid magic routing of submodule.

**Comment by colehurwitz** [comment]
Alright, I think I am in the minority on this one so I will agree to the alessio + flatten at the same time version of spikeinterface. :)

**Comment by samuelgarcia** [comment]
I close this issue.
spiekinterface is working.
Let's continue discution there
