### ISSUE TITLE
Deal with our cyclic dependencies

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#203]
ascertainment :  we have, and we will have more cyclic dependencies.

Here some notes as reminder and to open a discussion.

I think we have in mind something like that about our dependency chain:

  * spikeextractor<spikesorters<spiketoolkit<spikewidget<spieksforest

But there are problems that break this chain :

  * spiketoolkit.preprocessing<spikesorter
  * spikewidget<spiketoolkit.comparison (plot in method wich is very convinient)
  * spikewidget<spiketoolkit.study (a future idea of generating comparison auto report in MD + 
    figures)

The main design problem is that spiketoolkit offer:

  * low level (used in many place) functions : **preprocessing/postprocessing/curation**
  * intermediate level functions : **sorters**
  * high level functions : **comparison/study**

We will front more more over cyclic deendency with a such organization.

Some solutions:

  1. stay with that and accept weak dependencies. (not in setup but ```import``` inside function)
     already the case in sorter
  2. move out comparison/study from spiketoolkit and create a new module (spikecomparison)
    AND move out sorter  from toolkit and (put laucher in spikesorter)
  3. move out **preprocessing/postprocessing/curation** and create a new module

In my mind the best is the 2. The name toolkit meaningful for all processing stuff.
I can live with 1 but #198 will be quite important in that case.

@alejoe91 : I am pretty sure you will be unhappy the solution 2. :)

@magland @colehurwitz @mhhennig 

The solution 2 will lead to with no more cyclic dep.

  * spikeextractor<spikesorters<spiketoolkit<spikewidget<spikecomparison<spikesforest

EDIT : I wanted to say

  * spikeextractor<spiketoolkit<spikesorters<spikewidget<spikecomparison<spikesforest

**Comment by colehurwitz** [comment]
I am actually a big fan of number 2. The more I write about SpikeInterface in the paper, the more I realize that spiketoolkit is conceptually two parts: analysis and comparison. I think it would more intuitive to have these in separate repositories and would obviously help with cyclic dependencies. 

Also, we could always combine these four repositories with a metapackage if things get too confusing.  ;)

**Comment by alejoe91** [comment]
It's ok for me to have spike comparison as a separate module. But I would leave the spikesorters wrapper in spiketoolkit. A weak dependency for the preprocessing is ok for me

**Comment by colehurwitz** [comment]
I think putting sorters and comparison into their repos is a good move. However, if we do that, we would have to have a meta package that combines them together and freezes the versions. Otherwise, it would be too hard to use. I think even with 4 packages, it is already good to have a metapackage.

**Comment by samuelgarcia** [comment]
@alejoe91 : you have done half the way :) Why do you still want to keep sorter in toolkit ?

**Comment by colehurwitz** [comment]
Here is what I would suggest:

*Packages*: spikeextractors, spiketoolkit, spikesorters, spikecomparison, spikewidgets, spikeinterface, spikely

*Dev packages*:
spikeextractors: file IO
spiketoolkit: data processing (preprocessing, postprocessing, curation, validation)
spikesorters: wrapped sorters and launcher
spikecomparison: comparison and study
spikewidgets: data visualization and widgets

*Meta packages*:
spikeinterface: extractors, preprocessing, sorters, postprocessing, validation, curation, comparison, study, widgets
spikely GUI: extractors, preprocessing, sorters, curation (postprocessing used for export to phy) (edited)

**Comment by colehurwitz** [comment]
Would you agree with this @alejoe91 and @magland? I know the meta package is a bit controversial, but I think that with this package structure, we would avoid cyclical dependencies while making the whole framework more accessible to users and developers. I am totally convinced that this is the right path, but I think we should all agree if we were to make a change like this.

**Comment by alejoe91** [comment]
Not sure. Maybe I would keep preprocessing, postprocessing, curation, and validation in the toolkit or tools metapackage

**Comment by colehurwitz** [comment]
I can see where you are coming from, but I am really not sure what information that would give the user. Why would keeping them together help the user? If I want preprocessing functions or curation functions, I might actually be confused to look in something called a toolkit. I would rather look inside a module that is named after the operation for which I am looking.

**Comment by colehurwitz** [comment]
I have been out voted in #198 so I will agree with @alejoe91 on this one :)

```
si.extractors
si.toolkit (preprocessing, postprocessing, validation, curation)
si.sorters
si.comparison
si.widgets
```

**Comment by alejoe91** [comment]
@samuelgarcia can you use spikewidgets for the study plots? I think that when we freeze the packages in spikeinterface it's safer to have dependencies. So spikecomparison could depend on spikewidgets (spikewidgets does not depend on spikecomparison, it only depends on spiketoolkit)

**Comment by samuelgarcia** [comment]
@alejoe91 : yes I plan to use spikewidget for study plot. And so yes spiekcomparison would depend on spikewidget.

My proposal was:

  * spikeextractor<spiketoolkit<spikesorters<spikewidget<spikecomparison<spikesforest

**spikewidget<spikecomparison** : resolve on cyclic dep

**spiketoolkit<spikesorters** : could resolve the other one :) but on that difficult point you did not say anything at the moment ;) and my guess is that you don't like it.

About the name spikecomparison : I am not so happy with this **sorterevaluation** or **sortercomparison** would be more semantcally appropriate. But I don't car so much.

Lets wait @magland and @mhhennig before making again big changes.
I won't have time ti do it before 2 weeks. I can manage everything. (spikecomparison + metapackage)

**Comment by alejoe91** [comment]
Ehehehe I'm very jealous of the toolkit, but I agree. 

In the meta-package we'll have:

si.extractors
si.sorters
si.toolkit
si.widgets
si.comparison

Only the study will depend on the widgets. I suggest making a submodule in spikewidgets (studywidgets) to make the seaborn plots. Do you agree?

I think that porting the packages would be super fast. We just need to make spikecomparison and spikeinterface, clean up the toolkit, and make the meta-package spikeinterface.

@samuelgarcia do you know if you you can overwrite the `python setup.py develop`? It would be cool if we could `pip install -e spike...` all the wrapped packages in the spikeinterface folder.

**Comment by samuelgarcia** [comment]
>Only the study will depend on the widgets. I suggest making a submodule in spikewidgets (studywidgets) > to make the seaborn plots. Do you agree?

Flat is OK for the moment. Lets wat how many plot function will be done and see if a submodule is needed, no ?

>@samuelgarcia do you know if you you can overwrite the python setup.py develop? It would be cool if > we could pip install -e spike... all the wrapped packages in the spikeinterface folder.

I see the point. I am not very expert in installation.
What could do :
  * keep the setup.py 
   * force to all with == **when we release** SI
   *  just after put >= so we could have spikeinterface also as "develop" always for all package.

> I think that porting the packages would be super fast.

Yes it will be super fast but:
  * lets wait @magland  and @mhhennig 
  * there is no urgency in this new packae organisation
  * you have a thesis to write.

**Comment by samuelgarcia** [comment]
spikecomparison is out.
