### ISSUE TITLE
No sorters attribute?

### ISSUE THREAD

**Issue by matthewperkins** [SpikeInterface/spiketoolkit#209]
`In [2]: st.sorters.available_sorters()                                                                                                                                           
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-df15c12b1d5a> in <module>
----> 1 st.sorters.available_sorters()

AttributeError: module 'spiketoolkit' has no attribute 'sorters'
`

**Comment by alejoe91** [comment]
Hi @matthewperkins!

We are refractoring the code. Now we recommend using `spikeinterface` package, which is a metapackage for spikeextractors, spiketoolkit, spikesorters (sorters were moved here), spikecomparison, and spikewidgets. We are updating the docs right now. 

Basically all the `st.sorters` calls are now:
`import spikeinterface as si`

`si.sorters.available_sorters()`

Cheers 
Alessio

**Comment by alejoe91** [comment]
@matthewperkins does this fix the problem?

**Comment by McD-NMI** [comment]
I have the same problem. Using the spikeinterface package and the running those lines gives the same error.

> si.sorters.get_default_params()
> 
> AttributeError: module 'spikeinterface' has no attribute 'sorters'

**Comment by samuelgarcia** [comment]
@McD-NMI : could you open this issue here https://github.com/SpikeInterface/spikeinterface/issues
I confirm this bug and this is strange.
I have this in ipython (jupyter) but not in scripts.
