### ISSUE TITLE
tridesclous

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#21]
Hi @alejoe91.
I did not knewn that you are also involved in spike sorting.

This project is somethign that I wanted to do from a long time.
Congratulation for this.
I can join effort if you want.

I am the author of tridesclous.
Would you be intereested to have an interface with tridesclous here ?
I can do it if you want.

**Comment by samuelgarcia** [comment]
Great.
Thank for the quick anwser.

I will have few time the 4 next weeks.
But I will try a PR for tridesclous in spikeintreface and spiketoolkit.

yes TDc have a really great UI but it is verylink to the TDC methods itself (template matching).
Moreover offer 2 distinct UI one for curating the catalogue (catalogueWindow) not spikes and one for checking the spike sorting (PeelerWindow).
Few spike sorting software have the same workflow.

I already code some importedrs from spyking-circus in TDC.

You should try TDC to have a global idea. There are some open dataset integrated for a fast dicovery.

**Comment by alejoe91** [comment]
will definitely try :)

**Comment by alejoe91** [comment]
d612090ee6cda4b1b59a786dcfc4d7016a91a0b6

I believe this is done :)
