### ISSUE TITLE
URGENT: fix docs for spikeinterface use

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#210]

**Comment by samuelgarcia** [comment]
very urgent.

**Comment by alejoe91** [comment]
@samuelgarcia I can try to have a minimal example tomorrow. We should especially change the readme and point to spikeinterface.

**Comment by samuelgarcia** [comment]
We should  copy/paste spiketoolkit readme to spikeinterface readme more or less no ?

**Comment by samuelgarcia** [comment]
And make readme minial at the moment for all subpackage?

**Comment by alejoe91** [comment]
Yes :) and also merge the read the docs

**Comment by alejoe91** [comment]
https://spikeinterface.readthedocs.io/en/latest/
