### ISSUE TITLE
KeyError: 'unit' with spiketutorial

### ISSUE THREAD

**Issue by nahawtho** [SpikeInterface/spiketoolkit#211]
spikeextractors==0.5.4
spiketoolkit==0.3.5
spikewidgets==0.2.0

I am trying to do the SpikeInterface_Tutorial. On the line saying: 
`sorting_KL_split_curated = st.curation.threshold_min_SNR(recording=recording, sorting=sorting_KL_split, min_SNR_threshold=5)`
I am getting a persistent error Key error: 'unit'. I have tried versions 0.5.3 and 0.5.5 of se and multiple versions of st as well. The traceback goes into the if statement (unit_id is None) which i find kind of strange.

Any advice? What is the combination of versions expected to work for these tutorials? It would be helpful if the requirements.txt and environment files also included version numbers.

**Comment by alejoe91** [comment]
@nahawtho I'll try to port the code to spikeinterface (new meta-package that installs the correct versions) in the following week. Sorry about that..busy summer for all of us :(

How many units does sorting_KL_split have? 
Can you paste the entire error?

Alessio

**Comment by nahawtho** [comment]
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-96-c7f15c94d5b8> in <module>
----> 1 sorting_KL_split_curated = st.curation.threshold_min_SNR(recording=recording, sorting=sorting_KL_split, min_SNR_threshold=5)
      2 print('Curated Units', sorting_KL_split_curated.get_unit_ids())

~/.local/lib/python3.6/site-packages/spiketoolkit/curation/threshold_min_SNR.py in threshold_min_SNR(recording, sorting, min_SNR_threshold, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)

~/.local/lib/python3.6/site-packages/spiketoolkit/curation/threshold_min_SNR.py in __init__(self, recording, sorting, min_SNR_threshold, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)

~/.local/lib/python3.6/site-packages/spiketoolkit/validation/qualitymetrics.py in compute_unit_SNR(recording, sorting, unit_ids, save_as_property, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)
     47     templates = st.postprocessing.get_unit_templates(recording_f, sorting, unit_ids=unit_ids,
     48                                                     max_num_waveforms=max_num_waveforms,
---> 49                                                     mode='median')
     50     max_channels = st.postprocessing.get_unit_max_channels(recording, sorting, unit_ids=unit_ids,
     51                                                           max_num_waveforms=max_num_waveforms, peak='both',

~/.local/lib/python3.6/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_templates(recording, sorting, unit_ids, mode, grouping_property, save_as_property, start_frame, end_frame, ms_before, ms_after, dtype, max_num_waveforms, compute_property_from_recording, verbose)
    267                                            grouping_property=grouping_property, dtype=dtype,
    268                                            compute_property_from_recording=compute_property_from_recording,
--> 269                                            verbose=verbose)
    270         if mode == 'mean':
    271             template = np.mean(waveforms, axis=0)

~/.local/lib/python3.6/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_waveforms(recording, sorting, unit_ids, grouping_property, start_frame, end_frame, ms_before, ms_after, dtype, max_num_waveforms, save_as_features, compute_property_from_recording, verbose)
    188                 else:
    189                     features = waveforms
--> 190                 sorting.set_unit_spike_features(unit_id, 'waveforms', features)
    191             waveform_list.append(waveforms)
    192 

~/.local/lib/python3.6/site-packages/spikeextractors/MultiSortingExtractor.py in set_unit_spike_features(self, unit_id, feature_name, value)
    100         else:
    101             if(unit_id is None):
--> 102                 property_names = []
    103                 for sx in self._SXs:
    104                     property_names_sx = sx.get_unit_property_names(unit_id)

KeyError: 'unit'`

However this error output is from using se 0.5.4

**Comment by nahawtho** [comment]
There are 37 units

**Comment by alejoe91** [comment]
@colehurwitz seems to be from the multisortingextractor. Can you take a look?

**Comment by colehurwitz** [comment]
Found the issue. The 'set_unit_features'  in the multisortingextractor was using the wrong key (from an older version) to access the underlying sorting extractors. Fixed that and merged to master in spikeextractors. Thanks for letting us know! I should be able to work much more on cleaning up spikeinterface starting next week.

**Comment by colehurwitz** [comment]
Should be fixed now in the master branch! We will release clean versions of things soon I think.

**Comment by colehurwitz** [comment]
Should I close?

**Comment by nahawtho** [comment]
Perhaps not:
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-44-c7f15c94d5b8> in <module>
----> 1 sorting_KL_split_curated = st.curation.threshold_min_SNR(recording=recording, sorting=sorting_KL_split, min_SNR_threshold=5)
      2 print('Curated Units', sorting_KL_split_curated.get_unit_ids())

~/.local/lib/python3.6/site-packages/spiketoolkit/curation/threshold_min_SNR.py in threshold_min_SNR(recording, sorting, min_SNR_threshold, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)
     82         apply_filter=apply_filter,
     83         freq_min=freq_min,
---> 84         freq_max=freq_max
     85     )

~/.local/lib/python3.6/site-packages/spiketoolkit/curation/threshold_min_SNR.py in __init__(self, recording, sorting, min_SNR_threshold, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)
     33                                     max_num_waveforms=max_num_waveforms,
     34                                     apply_filter=apply_filter,
---> 35                                     freq_min=freq_min, freq_max=freq_max)
     36         for i, unit_id in enumerate(self._sorting.get_unit_ids()):
     37             if snr_list[i] < self._min_SNR_threshold:

~/.local/lib/python3.6/site-packages/spiketoolkit/validation/qualitymetrics.py in compute_unit_SNR(recording, sorting, unit_ids, save_as_property, mode, seconds, max_num_waveforms, apply_filter, freq_min, freq_max)
     47     templates = st.postprocessing.get_unit_templates(recording_f, sorting, unit_ids=unit_ids,
     48                                                     max_num_waveforms=max_num_waveforms,
---> 49                                                     mode='median')
     50     max_channels = st.postprocessing.get_unit_max_channels(recording, sorting, unit_ids=unit_ids,
     51                                                           max_num_waveforms=max_num_waveforms, peak='both',

~/.local/lib/python3.6/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_templates(recording, sorting, unit_ids, mode, grouping_property, save_as_property, ms_before, ms_after, dtype, max_num_waveforms, compute_property_from_recording, verbose)
    262                                            grouping_property=grouping_property, dtype=dtype,
    263                                            compute_property_from_recording=compute_property_from_recording,
--> 264                                            verbose=verbose)
    265         if mode == 'mean':
    266             template = np.mean(waveforms, axis=0)

~/.local/lib/python3.6/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py in get_unit_waveforms(recording, sorting, unit_ids, grouping_property, channels, ms_before, ms_after, dtype, max_num_waveforms, save_as_features, compute_property_from_recording, verbose)
    189                 else:
    190                     features = waveforms
--> 191                 sorting.set_unit_spike_features(unit_id, 'waveforms', features)
    192             waveform_list.append(waveforms)
    193 

~/.local/lib/python3.6/site-packages/spikeextractors/MultiSortingExtractor.py in set_unit_spike_features(self, unit_id, feature_name, value)
    100             raise ValueError("Non-valid unit_id")
    101         sorting = self._unit_map[unit_id]['sorting']
--> 102         unit_id_sorting = self._unit_map[unit_id]['unit']
    103         self._sortings[sorting].set_unit_spike_features(unit_id_sorting, feature_name, value)
    104 

KeyError: 'unit'`

**Comment by nahawtho** [comment]
!pip freeze | grep spikeextractors 
!pip freeze | grep spiketoolkit
!pip freeze | grep spikewidgets

spikeextractors==0.5.5
spiketoolkit==0.4.0
spikewidgets==0.2.2

**Comment by alejoe91** [comment]
@nahawtho Can you install spikeestractors from sources?

First `pip uninstall spikeestractors`, and then from the cloned repo run: `python setup.py develop`
