### ISSUE TITLE
current status and probe abstraction

### ISSUE THREAD

**Issue by sin-mike** [SpikeInterface/spiketoolkit#213]
Dear Developers,

I've been following SpikeInterface for a while. Thank you for your efforts, your package perfectly fits my intent to generalize spike sorting algos. I have two questions at the moment.

At first, I noticed a burst of activity recently, so I was wondering if you're planning to make a release. The question if pure practical, should I introduce spikeinterface to my lab teammates right now and include it in our routine practice or just wait a bit for a more stable version (e.g. spikely)?

The second question is more about a bit of advice. Do you have, at your side, some abstraction of a probe? Which could cover reading and writing of prb files, and which could be used for visualizing topoplots and topo trace plots as in eeg processing packages? I do simultaneous ecog-intracratial recordings with a bunch of different probes. I have elaborated some class for a probe, but I doubt it is enterprise-ready, and I suppose there must be some other classes to represent probes.

What I mean, that I can do something like previewing a layout
![image](https://user-images.githubusercontent.com/4338049/62721599-3c48e300-ba15-11e9-9a57-03bc4b4f6cee.png)

or previewing erps
![image](https://user-images.githubusercontent.com/4338049/62721657-5da9cf00-ba15-11e9-93de-0634922f353b.png)

If you don't have any, would you need such a class? I can work on it.

BR
Mike

**Comment by alejoe91** [comment]
Hi @sin-mike,

Thank you for the interest! We are currently finishing up for a first release, which will happen around the end of the month in combination with a preprint release. We created a meta-package called spikeinterface, which wraps spikeextractors, spikesorters, spiketoolkit, spikecomparison and spikewidgets.

That should be already quite stable if you want to give it s try, but we'll make a 1.0 at the end of the month. I think it's ready for including it in a lab pipeline. We have been using it for quite a while and it works great! :)

Regarding the probes, we do have functions to load and save prb files in spikeextractors (https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extraction_tools.py#L60). By design, visualization-related stuff should belong to the widgets. We have already a couple of widgets for electrode geometry and plotting waveforms that can do something similar to what you suggested. I think though that the widgets can be improved. 

I have also developed a package for probe handling package (including electrical stimulation) called MEAutility (https://meautility.readthedocs.io/en/latest/). We could use both packages to improve the plotting utilities. What do you think?

Cheers,
Alessio

**Comment by colehurwitz** [comment]
I actually like the idea of a probe class that can be stored inside each recording extractor. It could be accessed as Mike showed in his example. Would be worth thinking about!

**Comment by sin-mike** [comment]
Thank you for answers!

@colehurwitz would you need a PR to preview my probe class structure? To my mind, the class could just be a wrap up around pandas dataframe with IO handling and some viz. I guess, what @alejoe91 did with MEAutility could cover my needs, I need to look it more thoroughly. 

Widgets are useful, true. In the MVC paradygm, the probe class could just represent 'model', while widgets are just 'views', however, having a fast preview embeded to the probe class is so incredibly handy in practice.

**Comment by sin-mike** [comment]
@alejoe91 I wonder, why you didn't include MEAutility to spike interface? Are there problems? It looks complete to me. It could encapsulate well all load/write prb functions.

**Comment by alejoe91** [comment]
@sin-mike MEAutility is indeed complete and working :) I use it in the MEArec package, which is a simulator of extracellular activity (https://github.com/alejoe91/MEArec).

At the beginning we decided to keep spikeinterface lightweight and we thought that prb or csv files can be used for probe info. Especially prb files, which more used on the field, could be used as standard for probe info. Moreover, I believe that prb files are more powerful than the MEAutility abstraction as they can handle groups. 

I'm a bit reluctant honestly in having a probe class for 3 reasons:
- all the info loaded from the prb file and needed for spike sorting is stored in the recording extractor object as locations, groups, or other properties. Hence I don't see how an extra layer of abstraction is needed
- I find the current probe handling simple and straightforward. The `load_probe_file` does everything under the hood.
- in my opinion all viz should be handled by the widgets. This is the way it's implemented now. The `plot_electrode_geometry`, `plot_timeseries`, and `plot_unit_waveforms` can already make use of the location information.

An alternative approach as you suggested could be depending on MEAutility for loading/saving probe filed and providing several available designs. The `MEA` object could be then stored in the recording extractor. The MEAutility package could be used then in the widgets for visualizing traces and electrode layout. In this case, however, we would need to handle groups in the MEAutility objects. In addition, MEAutility would then possibly depend on spikeextractors and spikeextractors on MEAutility..and I would avoid this cyclic dependency.

What do you think would be the main benefit of having an abstraction layer for the probe (apart from plotting)? 

We could provide a series of available prb files (e.g. for tetrodes, neuropixels, etc.) internally in spikeextractors.

Nevertheless, I will be happy to include prb and csv handling in MEAutility if you wish to use it for plotting. Note that the MEAutility probe definition includes several metadata which are useful for simulation, such as size, shape, probe type etc, but useless for spike sorting purposes.

Let me know what you guys think @sin-mike @colehurwitz

**Comment by colehurwitz** [comment]
So what I took from Mike's comment and what I think would be a nice addition to the RecordingExtractor is a built-in probe object that can store information from and handle file IO with probe files. I imagine that it could handle groups and locations currently.

This object abstraction inside of the RecordingExtractor could be very useful as when we want to start adding more information about probes or we want to store information about the probe that is unrelated to the channels (pitch, etc.), having an object that we can extend is important. We can still use the `load_probe_file` function to do most of the work, but that can internally setup a probe object in the RecordingExtractor.

To be honest, I am not sure I like having channel properties at all... I think having unit properties and spike feature properties makes sense, but channel properties are just a probe in disguise usually. Having a probe object would take away the need for channel properties and we could just load and get information from the probe class.

**Comment by alejoe91** [comment]
In my opinion having properties is a good implementation. If for example we remove a channel or extract sub recordings, the properties are handled easily. Instead, having a probe object would require to modify the object and keep track of the modification. Another caveat that I see is if the probe file has more ore less channels than the recording. This is the case for example when there are reference channels. You would still need to map locations and groups to the channel ids, and to me that sounds like a channel property :)

Regarding adding more info to the probe file, I'm not sure that is needed and I don't see a use case inside of spikeinterface when it could be useful. It could be like a metadata, and I think we should keep it as lightweight as we can. 

I don't agree that properties are probe info in disguise. Instead prb files contain probe info that needs to be linked to the recording.

**Comment by colehurwitz** [comment]
Ok, I can agree with what you are saying @alejoe91 . Maybe @sin-mike could help us with some probe widgets then. :)

**Comment by sin-mike** [comment]
@alejoe91 @colehurwitz Thank you for a fruitful discussion! Some thoughts about encapsulating a probe.

Probes could have an internal structure developed independently of SpikeInterface packages and used in other packages, e. g. in elephant to calculate CSD (as I do routinely) http://neuralensemble.org/elephant/

Probes in .prb lack 3D support, which is crucial to me, as I'm using simultaneous ECOG-LFP in my experiments.

Probe electrodes could also contain useful parameters for a user, e.g. impedance, to perform impedance correction. In my case, I have size varying electrodes in a single probe, which are handy, as they allow both spike and LFP recordings.

The exact layout of a probe could also vary, as in my case, it is more a 3d layout rather than a 2d.

To my mind, probes are well represented by a pandas dataframe, like
![image](https://user-images.githubusercontent.com/4338049/62781178-0ca2e500-bac0-11e9-8493-6a5281285fff.png)

It allows easily to extend it with coordinates in 3D space, impedances, labels, adc channels, etc. I suppose not all features would work with blank probes, e.g. with Xs and Ys, so you need to have a certain feature to use a certain class interface.

Thus, I thought, if we agree on interfaces of the class, it could be less of a problem to support it properly. I understand, that the interfaces would vary more frequently than it should in the beginning of development, but they will stabilize eventually.

Unless, it is like matlab, when you have a very poor package structure, all the functions names are present in the global namespace, which results in conflicts eventually.

**Comment by alejoe91** [comment]
@sin-mike sorry for the late reply. I just wanted to point out that you can achieve what you suggested using the prb file:

- locations can be in 3d as well. However, for spike sorting, you will need to drop one dimension (e.g. for kilosort).

- any dictionary key is parsed, so you could easily embed `label` and `ADC` in the probe file, or set them using the `set_channel_property`

I like the idea of showing channel properties as a pandas dataframe though. This could be easily implemented. 

We could try to support both prb files and MEAutility (adding channel groups, and labels -- if you think that it's a good start :) ), but I still think that loading probe info as channel properties is a better and more handy approach when it comes to `RecordingExtractor` objects and processing.

**Comment by samuelgarcia** [comment]
Hi all.
welcome here @sin-mike !!

Contrary to what @alejoe91 said I am in favor of having a Probe object in spikeinterface.
To be honest I am not so happy that all geometry problems are solve through properties in recording.

I also thinks that MEAutility:
  * should be renamed (with no capital and no mea) maybe something like "probelayout", 
    "probesutils", ...
  * should be integrated in spikeinterface family as an independant package
  * could be use by many many spike sorters tool (tridesclous, spikyking circus, phy, HS2 ...)

In short this package would:
  * handle mea definition (today in MEAutility)
  * handle probe layout input/output (today in spikeextractors)
  * have a clear class for probe geometry/layout (

And the plotting would be in spikewidget.

spikeextractor would depend on this for all probe stuff.
We could have a slow transition by keeping location in recording properties but read/write would depend on this package.

And maybe one day the geometry layout could be handle explicitly with a class and not implicitly in properties. But this is a string change.

:)

**Comment by colehurwitz** [comment]
I think I agree with @samuelgarcia and @sin-mike . My only question would be if the channel properties would be a part of the RecordingExtractor still. I can't see a use for them if we have a probe object.

**Comment by samuelgarcia** [comment]
I think for a first step channel properties for location still would exists (and could be used for plotting) but and second (but long term) step location as property  would not handle anymore the probe geometry. This is a string change because run_sorter would imply to also provide a probe object.

This would occur of course after the v1.0 and the paper preprint.

**Comment by alejoe91** [comment]
@sin-mike take a look at https://probeinterface.readthedocs.io/en/main/ :)
