### ISSUE TITLE
bandpass_filter memory leak

### ISSUE THREAD

**Issue by mhhennig** [SpikeInterface/spiketoolkit#215]
It's quite massive: some things remain in memory even when the extractor objects are discarded. Please help :(

**Comment by alejoe91** [comment]
Hi @mhhennig, what do you mean by discarding objects? to `del` them? Can you show an example of this? I won't be able to look into it before next week..but maybe we can understand what's going on

**Comment by mhhennig** [comment]
I think I have tracked it down to the scipy fft function, there seems to be some caching going on that is not garbage collected properly. Still investigating...

**Comment by mhhennig** [comment]
Ok, it's complicated. This seems to be a problem with the memoryviews cython uses. If I request data from a preprocessing extractor from cython code (via memorview), somewhere a leak opens. Nothing we can do here, so closing.
