### ISSUE TITLE
validation module: add save_as_property

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#222]
@colehurwitz similar to the [postprocessing](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L285-L286), can you add a `save_as_property` option when calling the validation functions separately?

**Comment by colehurwitz** [comment]
Sure, I can do that.

**Comment by colehurwitz** [comment]
All but SNR actually have that. I can add it for SNR.
