### ISSUE TITLE
complete curation module

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#230]
- add curation funcion/class for all metrics
- add a function to combine more metrics at once:

e.g.
```
sorting_curated = st.curation.threshold_metrics(sorting, recording, metrics=['firing rate','snr' ], 
                                                                            threshold_signs=['less', 'less'], mode='and')
```

`mode` can be 'and' or 'or'.

**Comment by colehurwitz** [comment]
Looks cool. Leave it to me.

**Comment by colehurwitz** [comment]
Should we do this after the paper? Some metrics return multiple things which make them difficult to make curation tools for.

**Comment by colehurwitz** [comment]
@rogerhurwitz

**Comment by alejoe91** [comment]
Is this completed? @colehurwitz

**Comment by colehurwitz** [comment]
In the refactorization PR it is completed.
