### ISSUE TITLE
Allow passing of chunk_size to BandpassFilterRecording

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#238]
Currently, when using `BandpassFilterRecording`, the underlying `FilterRecording` chunk size is fixed to 30k points. This makes the calculation of spike metrics during curation extremely slow for large dataset, as each read need to filter 30k points. This problem is especially prominent when the dataset is large. Although the filtered data is cached, for large dataset the hit rate is so low that very likely each read is a fresh read and the data caching won't help much. Considerring the fact that a spike usually last for 1.5 - 2ms, allowing one to specify the filter chunk size can dramatically improve the performance with minimal efforts.

Suggested improvement:
allow one to specify the `chunk_size` in `preprocessing.bandpass_filter`

It may be also beneficial to move some of the filter initiation code to the constructor of `bandpass_filter`, as all the filters parameters are known when the object is created.

**Comment by colehurwitz** [comment]
Yes, this makes sense. I think we can make this a parameter for each subclass of the `FilterRecording` object, including `BandpassFilterRecording`.

**Comment by alejoe91** [comment]
@teristam now it is a param. Another option to speed it up is to filter and save the entire recording as binary and then load it back with the BinDatRecordingExtractor. Otherwise extracting waveforms is very slow I agree..
