### ISSUE TITLE
st.curation.threshold_snr produces error if 'waveform' is already in sortingextractor

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#240]
hi, sorry, it's me again...

When the 'waveform' property is already set in the` sortingextractor` by `st.postprocessing.get_unit_waveforms`, calling `st.curation.threshold_snr` results in an error

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

at 

` template = np.median(waveforms, axis=0)` in `postprocessing_tools.py`

Probably cause:
`waveforms = np.array(waveforms[idx_not_none])` should be `waveforms =np.stack(waveforms[idx_not_none])` instead

**Comment by alejoe91** [comment]
Hi @teristam 

Can you paste the entire traceback? when you get waveforms, are you using `max_num_waveforms`?

**Comment by alejoe91** [comment]
Yes I was able to reproduce it :) Let me quickly fix it! thanks for spotting the bug!

**Comment by alejoe91** [comment]
@teristam should be fixed with this PR https://github.com/SpikeInterface/spiketoolkit/pull/241

Can you confirm this?

**Comment by teristam** [comment]
It's fixed now. Thanks!
