### ISSUE TITLE
MetricCalculator and option to filter the input recording

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#247]
Is there an option to force the band pass filter on the input recordings ?
If not, it is dangerous because metris like SNR are suposed to play with flat signal.

Am I wrong ?

**Comment by colehurwitz** [comment]
I will re-implement this. I think it was removed in translation to the metric calculator. We need to think about which metrics want filtering/non-filtering.

**Comment by alejoe91** [comment]
I think all metrics based on waveforms/templates should use filtered data or have a filter option.

**Comment by samuelgarcia** [comment]
Hi is the filtering implemented in compute_snrs ?

**Comment by colehurwitz** [comment]
Not yet! I can add that back today

**Comment by colehurwitz** [comment]
Should all metrics use the filtered data if possible?

**Comment by colehurwitz** [comment]
Any advice on this @alejoe91 @samuelgarcia . I want to implement this, but in the best way possible. I was thinking that when a recording is added, we give the option to filter it there so that everything is using the correct filtered recording. Thoughts?

**Comment by colehurwitz** [comment]
I have an idea on how to implement this.

**Comment by alejoe91** [comment]
@colehurwitz any updte on this?

**Comment by alejoe91** [comment]
I believe this is done :) https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/metric_calculator.py#L27
