### ISSUE TITLE
Add code (to `postprocessing.py` ?) for calculating features from spike waveforms

### ISSUE THREAD

**Issue by jaib1** [SpikeInterface/spiketoolkit#255]
It would be nice if within one module there were different functions to calculate different features from spike waveforms (e.g. width, peak-trough amplitude, PC variations, wavelet variations, etc...)
Had mentioned this to @alejoe91 in an email thread.

**Comment by alejoe91** [comment]
Hi @jaib1 

I'm starting to implement a `FeatureCalculator` class in the postprocessing.py. At first I will include:

- width (p2p)
- fwhm (full width half max)
- neg (negative_peak)
- pos (positive peak)
- amp (p2p amp)

that could be applied either to the template or to single waveforms, and computed either for the channel with largest amplitude, or for all channels (which could be relevant to find backpropagating spikes, etc.)

What do you think?

**Comment by jaib1** [comment]
Great! Will watch this space

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/334

**Comment by alejoe91** [comment]
@jaib1 this is in place now. You can compute features with: `st.postptocessing.compute_unit_template_features()`

**Comment by jaib1** [comment]
awesome, thanks!
