### ISSUE TITLE
Meaning of threshold in curation is not so clear

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#263]
In `threshold_snr`, for the argument `threshold_sign`, the documentation says: 

> will threshold any metric less than the given threshold.

By "threshold", here does it means it will remove cluster according to the threshold sign, or keep the clusters? I think the wordings can be improved to avoid confusion.

Thanks!

**Comment by colehurwitz** [comment]
Good point! I will update.

**Comment by colehurwitz** [comment]
Should be fixed
