### ISSUE TITLE
Include an option to do in-memory filtering of input signal 

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#264]
Currently there is an option to save the filtered output as temporary binary file. However, for most users with typical recording, actually saving the filtered data in memory is fine and can offer the greatest speed. It may be beneficial to just offer an simple in-memory filtering option using the scipy.signal, without worrying about all those caching mechanisms.

**Comment by colehurwitz** [comment]
We could theoretically have an in_place option which filters the recording and builds a numpy_recording_extractor for it. That should be the fastest way to filter a recording (also, quite memory hungry). Maybe, all preprocessing modules could have this

**Comment by colehurwitz** [comment]
What do you think of this idea, @samuelgarcia ?

**Comment by alejoe91** [comment]
@teristam you can do that by setting `chunk_size=None`. In this case the signals are filtered on the fly when you get traces, without RAM caching or saving the binary file. Is that what you suggest?
Otherwise, the caching system actually saves the filtered data in memory, but it does it in chunks.

Also note that you can set the `type='butter'` to use the scipy filter instead of the fft kernel.

**Comment by teristam** [comment]
@alejoe91  I don't think filtering is on the fly is a very good option if I am accessing a lot of spikes, and it seems that when setting `cache=True`, now it cache data in a binary file rather than just memory?

I think the in-place filtering should be very straight forward? Just do filtering on the `_timeseries` of the extractor, without changing anything else?

**Comment by alejoe91** [comment]
> @alejoe91 I don't think filtering is on the fly is a very good option if I am accessing a lot of spikes, and it seems that when setting `cache=True`, now it cache data in a binary file rather than just memory?

Yes, and then they are memmapped so it should be pretty fast. Have you tried that out? 

> I think the in-place filtering should be very straight forward? Just do filtering on the `_timeseries` of the extractor, without changing anything else?

I see what you mean. We can implement a similar mechanism for caching in memory instead than on file. This will be very memory hungry though.

**Comment by samuelgarcia** [comment]
Hi all.
For in memory there is already ```cache_chunks=False/True``` option wich is an in-memory but by chunk cache and as Alessio said. The combinaison of ```cache_chunks=True + chunk_size=None``` is already a in-memory cache.

Globally, I don't like so much the inplace stuff... :)

**Comment by alejoe91** [comment]
I thinkwe should leave it the way it is. The `cache` option gives both behaviors
