### ISSUE TITLE
Common_reference doesn't work for single channels that are not in a list [fixed]

### ISSUE THREAD

**Issue by maartensc** [SpikeInterface/spiketoolkit#265]
When running the preprocessing function common_reference, with referencing to a single channel, I got the error:

spikeextractors/spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py, line 64, in get_traces,
channel_ids = [self._channels.index(ch) for ch in channel_ids]
TypeError: 'numpy.int64' object is not iterable

This is easily fixed by changing line 37 to `self._ref_channel = [ref_channels]`, so channel_ids always becomes a list, and thus becomes iterable.

Maybe I was just doing something wrong in the first place, but this easily fixed it for me, so maybe if others also experience this error, it could be a solution to change it in the code.

**Comment by alejoe91** [comment]
@maartensc thanks for spotting this. Indeed it should work with an int as well. I'll fix that!
