### ISSUE TITLE
Memory map postprocess - export to phy performance

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#270]
As discussed in a **spikeinterface** issue, `export_to_phy` tries to extract all the spikes from the recording so you can do manual curation later. This will unfortunately not scale to large datasets. 

To overcome this, I think we could extract an appropriate amount of spikes for computing the PCA components (not all the spikes) then waveforms could be loaded, transformed, and saved out in chunks. 

This would allow for `export_to_phy` to be used on large-scale recordings and on smaller machines. Not sure the priority on this, but seems potentially important.

**Comment by alejoe91** [comment]
I think that the best option would be to create memmap objects for waveforms and pca scores. This would allow to reduce dramatically RAM usage and export in chunks as well.

@colehurwitz what do you think? It's a big refractoring but I think it'll make things easier in the future.

In the `BaseSorter` extractor we could have a `self._tmp_folder` in which we can dump all temporary files. At deletion, the folder gets removed. 

If you agree I can start on this. I think this is very important as currently we cannot really handle huge datasets...

**Comment by colehurwitz** [comment]
Why do they need to be objects? Could they be memmaped numpy arrays or something?

**Comment by alejoe91** [comment]
Yes that's what I meant (memmap array are actually objects!) No need to make new classes

**Comment by alejoe91** [comment]
implemented
