### ISSUE TITLE
problem on exporting to Phy 

### ISSUE THREAD

**Issue by mafrasiabi** [SpikeInterface/spiketoolkit#274]
I am trying to export the sort results to Phy for curation but no matter what sorter I'm using it'll give _index_ error at pca.fit step , any idea what's the problem?

**Comment by alejoe91** [comment]
Hi @mafrasiabi 

What is the entire error traceback? Can you try to install the latest version of spiketoolkit from git?

Also, do you get the same error if you run this?

`st.postprocessing.export_to_phy(recording, sorting, max_spikes_for_pca=100000)`

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/issues/281 duplicate
