### ISSUE TITLE
Common referencing turns data into 'float64'

### ISSUE THREAD

**Issue by benefron** [SpikeInterface/spiketoolkit#295]
After applying common reference to my data the data is turned from 'int16' to 'float64'.
 Is it necessary?
If not is there a way to change it because it creates a much larger file which takes much longer to run the postprocessing toolkit on especially the export to phy.
Thanks,
Ben

**Comment by samuelgarcia** [comment]
Hi.
We must change this. It is a non wanted behavior.
Thanks for discovering it.
Sam

**Comment by benefron** [comment]
no problem.
I did a ad-hock solution for me now and added dtype='int16' for the np.mean but it is a solution just for my data set.
to change the np.median function was too complicated for me. so I am just running everything with average referencing.
Thank you

**Comment by alejoe91** [comment]
Hi @benefron 
I agree this is unintended if you use 'median', but the mean of int16 can very well be float. Maybe we can Add a dtype to force the output dtype?

**Comment by benefron** [comment]
That is right.
Maybe add an option also when exporting to phy to choose dtype

**Comment by samuelgarcia** [comment]
with dtype=None by default that would keep the input dtype.

**Comment by benefron** [comment]
is there a reason to export to phy in float32 if mt data originally is in int16? 
What is the syntex for dtype in export_to_phy if I want to change it?

**Comment by alejoe91** [comment]
Export to Phy should not change the dtype. You probably observe this because of the common reference problem. Can you try to export without applying common reference? Then the data should be int16

**Comment by benefron** [comment]
Yeah I so the code for it. 
I will try it with my patch solution,
Thanks

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/296
