### ISSUE TITLE
MetricCalculator.compute_pca_scores default variable max_spikes_for_pca should be int

### ISSUE THREAD

**Issue by DanBenHa** [SpikeInterface/spiketoolkit#299]
Hi,

when I do `compute_metrics()` on a MetricCalculator without prior computation of PCA scores, I get a TypeError for slicing because the default value for `max_spikes_for_pca` is a float:
https://github.com/SpikeInterface/spiketoolkit/blob/38f7118c66f3c6bebc16b3464e01648d62e2b54b/spiketoolkit/validation/metric_calculator.py#L243
See #281 

I'm not going to make a PR for this, since it can be easily circumvented by separately computing the PCA scores with custom settings, and because I see that there is soon going to be a refactoring of this, anyway. However, in the PR #294 the default should be changed to an int: https://github.com/SpikeInterface/spiketoolkit/blob/03c6f78a9ee502ed734a3f68d7d50cad610686cd/spiketoolkit/validation/quality_metric_classes/parameter_dictionaries.py#L32

**Comment by alejoe91** [comment]
Hi! This is fixed if you install from master. We will make a new package release very soon :)

**Comment by alejoe91** [comment]
Sorry I didn't see it referred to the open PR. Thanks for the suggestion! We'll change that @colehurwitz

**Comment by colehurwitz** [comment]
I will change this. Thanks!

**Comment by colehurwitz** [comment]
In postprocessing, max spikes for PCA is 10000 while for metrics, it is 100,000. Which should be the default. @alejoe91 , maybe we can also give some thought about how parameter dictionaries could be used for postprocessing in a future PR.

**Comment by alejoe91** [comment]
I like that in postprocessing all args are exposed as they are lower level functions. It's easier to document them in the docstring as well :)

**Comment by colehurwitz** [comment]
Ok, I guess the only problem is that we have to be careful in changing parameter values in two places as they can get out of sync.

**Comment by colehurwitz** [comment]
Btw, you can get the same effect by doing:

`max_spikes_for_pca=parameter_dict['max_spikes_for_pca']`
vs.
`max_spikes_for_pca=100000`

The parameter will be exposed to the user as 100000 when they read the details of the function. Also, between 10000 vs 100000, which should we do?

**Comment by alejoe91** [comment]
Maybe 100000 by default. It doesn't make that much of a time difference for fitting the pca

**Comment by alejoe91** [comment]
fixed
