### ISSUE TITLE
AssertionError in compute_unit_pca_scores if max_spikes_per_unit set and save_as_features True

### ISSUE THREAD

**Issue by DanBenHa** [SpikeInterface/spiketoolkit#300]
If I do `MetricCalculator`'s `compute_pca_scores()` with `max_spikes_per_unit=300` and `save_as_features=True` I get an AssertionError in
https://github.com/SpikeInterface/spiketoolkit/blob/38f7118c66f3c6bebc16b3464e01648d62e2b54b/spiketoolkit/postprocessing/postprocessing_tools.py#L632
because of 
https://github.com/SpikeInterface/spiketoolkit/blob/38f7118c66f3c6bebc16b3464e01648d62e2b54b/spiketoolkit/postprocessing/postprocessing_tools.py#L568

Is this the desired behaviour? `idx_not_none` is never set to another value, so the assertion is always false.

**Comment by alejoe91** [comment]
Hi @DanBenHa 
Are you using the latest master? I'll look into that. Can you paste some minimal code to reproduce the error? Thanks!

**Comment by alejoe91** [comment]
@DanBenHa this should fix it https://github.com/SpikeInterface/spiketoolkit/pull/301
Thanks for spotting it! The variable name was changed but not in that loop.

Can you test if it works on your side?

**Comment by DanBenHa** [comment]
Yes, using f14655b39e580b6baf58008aaa1ca0c6c3b40006 fixes this issue.
Thanks.
