### ISSUE TITLE
default max_spikes_per_unit is inf

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#306]
Hi guys, 

I try convert MS4 data to phy with your interface but I encounter a big issue, each time my memory was overload... 
I check export_to_phy function and it appear that default value for max_spikes_per_unit is set to infinite and their is no way to change it... 
Maybe you could add this variable in export_to_phy function?

Best regards,
Victor

**Comment by alejoe91** [comment]
HI Victor,

For exporting to phy, you need to compute pca_scores for all waveforms, so that parameter cannot be changed.
Are you using the master branch? I recently added an option (true by default) that creates memmap objects for all waveforms, so they don't get loaded to memory. 

How long are your recordings and how many channels? 

Cheers
Alessio

**Comment by mhhennig** [comment]
Also, could you show the code you use for this? I suspect the memmapping may not yet work in all cases...

**Comment by llobetv** [comment]
Hi, 

I used dev branch of spikeInterface so it should be on date
I record 30mn with 64 channels (and some unit with 200000 events)

Here my code:

#####################################################################
from spikeinterface import extractors as se
from spikeinterface import toolkit as st

import numpy as np
import os

import pdb


verbose=True
#change tempdir of mountainSort
os.environ['TEMPDIR'] = "/mnt/hdd/mountainlab/mountainlab/"


file_path = "/mnt/ssd/spikeinterface_test/rec_200306_094252/amplifier_sorted.dat"
prb_file = "64_para.prb"

output_folder = "./MS_test/"

ms4_params= {'detect_sign': 0, 'adjacency_radius': 51, 'freq_min': 150, 
              'freq_max': 4000, 'filter': True, 'whiten': True, 'curation': False, 
              'num_workers': 40, 'clip_size': 40, 'detect_threshold': 3, 
              'detect_interval': 10, 'noise_overlap_threshold': 0.15}

numchan = 64
sampling_frequency = 30000
dtype = np.int16




#launch analysis
sorting_MS4 = ss.run_mountainsort4(recording=recording_prb, output_folder=output_folder, verbose=verbose, **ms4_params)

#export to phy
st.postprocessing.export_to_phy(recording, sorting_MS4, "phy/", n_comp=2, 
                                electrode_dimensions=None, grouping_property=None, 
                                ms_before=1., ms_after=1.5, dtype=None, 
                                amp_method='absolute', amp_peak='both', 
                                amp_frames_before=3, amp_frames_after=3, 
                                #max_spikes_per_unit=2000,
                                max_spikes_for_pca=10000, max_channels_per_template=64, 
                                recompute_info=False, save_features_props=True, 
                                verbose=verbose, seed=0)



#####################################################################

Maybe an option to not export pca would be nice considering its duration.
It also appear that ms_before/ms_after is only for computing pca and not extracting waveform (what I thought first). It would be nice to be able to choose ms_before and after for template generation.


Thanks for your help!
Victor

**Comment by alejoe91** [comment]
Hi @llobetv 

The dev branch is not up-to-date. We should just remove it as it makes things confusing. In order to get the latest updates, you should install all packages from sources.

I think that Phy needs pca values, but I can double check! The ms_before and after are used for waveforms, and the waveforms are then used for pca. Try the master branches of spiketoolkit. It should fix the memory problem thanks to memmapping. 

Let us know if the problem persists!
Alessio

**Comment by llobetv** [comment]
I misspoked, I install my version from source and I have still memory issue (90 Gb for waveform extraction). 
For waveforms you're right, but then it would be nice to be able to plot longer waveform on phy that the one use for pca?

**Comment by alejoe91** [comment]
> I misspoked, I install my version from source and I have still memory issue (90 Gb for waveform extraction).
Do you first compute waveforms and then export to phy?
In that case you have to set the `memmap` argument of the `get_unit_waveforms` to True.
Memmap is set to True by default in the `export_to_phy` (see [here](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L847))

> For waveforms you're right, but then it would be nice to be able to plot longer waveform on phy that the one use for pca?
I think that this is not a common use case. Usually you would want to compute pca scores on the same waveforms that you see so that you can relate the differences. Do you agree?

**Comment by llobetv** [comment]
OK I just found the issue, if I install spiketoolkit with spikeinterface it install the version without memmap, I have to install it directly from spiketoolkit source.
I'll test and let you know.


For waveforms, It could be usefull to see full shape of spike for particular usage, even if pca are done in shorter waveform. I got spike with 10ms duration (complex spike of Purkinje cell) and it's simpler to understand everything if you can see its full shape. 


Thanks!

**Comment by alejoe91** [comment]
> OK I just found the issue, if I install spiketoolkit with spikeinterface source it doesnt install latest version of package, I have to manually install all package form source, my bad...
> I'll test and let you know.
Glad to hear you found the issue! I changed the README of the `spikeinterface` package to make it clearer.

> For waveforms, It could be usefull to see full shape of spike for particular usage, even if pca are done in shorter waveform. I got spike with 10ms duration (complex spike of Purkinje cell) and it's simpler to understand everything if you can see its full shape.
> 
I see your point here. On the other hand if you have complex spike features over long spike durations, I think there is no harm in computing pca scores useing the entire waveform. This might also help find slight differences in the feature view as well. So I would recommend setting longer `ms` values in your case.
The processing time is mainly due to the waveform extraction. PCA is relatively faster so I don't see it as a bottleneck to have more time samples :) 

> Thanks!
No worries!

**Comment by llobetv** [comment]
Well it took 100 Gb to extract all wavefom for 2.5ms so would be 400 Gb if I ask for 10ms, which is quite big when template need only sub part of unit.

Otherwise everything work pretty well !
I remove pc feature to check and phy is opening, just without pc view. I still think it's an usefull option, for fast manual curring (only merge and check quality unit their is no need of pca).

The last thing is that phy hasn't the map for the probe (just linear disposition), I'll check that and I'll keep you informed.

**Comment by llobetv** [comment]
Just one thing, I needed to ad this line to make it work (my tmp directory is too small): sorting_MS4.set_tmp_folder(tmp + "/tmp")

**Comment by llobetv** [comment]
One last thing,
I'm not sure but it appear that all channels are extract for pca calculation? (maybe i'm wrong). 
Considering the amount of data produce for 64 ch it would definitly be an issue for larger dataset, and also increase the duration of calculation when you can only extract a subpart of the channels (max_channels_per_template).


One more times, thanks for your help, 
Best,
Victor

**Comment by alejoe91** [comment]
Hi @llobetv 

> Well it tooks 100 Gb to extract all wavefoms for 2.5ms so would be 400 Gb if I ask for 10ms, which is quite big when template need only sub part of unit.

RAM or disk usage?

> 
> Otherwise everything work pretty well !
> I remove pc features to check and phy is still opening, just without pc view. I think it's an usefull option for fast manual curing (to merge and check unit quatlity their is no need of pca).

I can implement that, but it's a bit convoluted, so I might need a couple of days :)




> One last thing,
> I'm not sure but it appear that all channels are extract for pca calculation? (maybe i'm wrong).
> Considering the amount of data produce for 64 ch it would definitly be an issue for larger dataset, and also increase the duration of calculation when you can only extract a subpart of the channels based on max_channels_per_template.
> 

That should not be the case. You can see [here](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1109-L1133) that waveforms are computed on the `max_channels` and passed along to the `compute_unit_pca_scores` (as `_waveforms`), which [are used](https://github.com/SpikeInterface/spiketoolkit/blob/1c6de740733a59a686ee55c71dfd2e0330b5fba7/spiketoolkit/postprocessing/postprocessing_tools.py#L620-L625) for computing the PCA model and scores.

I'll get back to you when those fixes are implemented (so you can test them!)

Cheers
Alessio

**Comment by llobetv** [comment]
> Hi @llobetv
> 
> > Well it tooks 100 Gb to extract all wavefoms for 2.5ms so would be 400 Gb if I ask for 10ms, which is quite big when template need only sub part of unit.
> 
> RAM or disk usage?
> 
Disk usage, but i don't know why I update it a third time and now size is ok, so their is no pb anymore...

> > Otherwise everything work pretty well !
> > I remove pc features to check and phy is still opening, just without pc view. I think it's an usefull option for fast manual curing (to merge and check unit quatlity their is no need of pca).
> 
> I can implement that, but it's a bit convoluted, so I might need a couple of days :)
> 

It would be perfect, there is no need to rush everything work well without it.

> > One last thing,
> > I'm not sure but it appear that all channels are extract for pca calculation? (maybe i'm wrong).
> > Considering the amount of data produce for 64 ch it would definitly be an issue for larger dataset, and also increase the duration of calculation when you can only extract a subpart of the channels based on max_channels_per_template.
> 
> That should not be the case. You can see [here](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1109-L1133) that waveforms are computed on the `max_channels` and passed along to the `compute_unit_pca_scores` (as `_waveforms`), which [are used](https://github.com/SpikeInterface/spiketoolkit/blob/1c6de740733a59a686ee55c71dfd2e0330b5fba7/spiketoolkit/postprocessing/postprocessing_tools.py#L620-L625) for computing the PCA model and scores.
> 

You are right I was looking the old script one more time... (i  exctracted it from compress file to check it and I forget to do it again when I upgrade spiketoolkit...), 

So maybe this is why similarity is big for distant channel? (if template are done and compare on a subpart of channel)?

> I'll get back to you when those fixes are implemented (so you can test them!)
> 
> Cheers
> Alessio


Thank you very much ! :)

**Comment by alejoe91** [comment]
I'll make a PR on similarity in 2 minutes

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/312

**Comment by alejoe91** [comment]
implemented
