### ISSUE TITLE
Similarity score for distant unit

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#310]
Hi guys,

I've got an issue with similarity score, it gives really big value between units that are far away. 

Maybe their is a way to set similarity score to 0 for far away unit or scale similarity score based on amplitude difference on best channels? 

Best,
Victor

**Comment by alejoe91** [comment]
Hi @llobetv 

This is definitely a bug! I think that is because similarity is computed ignoring the different locations of the templates. I'll fix that immediately! Thanks for spotting it. :)

Alessio

**Comment by llobetv** [comment]
Thanks :)

**Comment by alejoe91** [comment]
@llobetv you can test this [PR](https://github.com/SpikeInterface/spiketoolkit/pull/312)

Basically I use only shared channels of the templates and I weighted the similarity score by the proportion of shared channels over the total template_ind.

Let me know if it gives reasonable results on your side

**Comment by alejoe91** [comment]
is it working on your side? I implemented to optional PCA export as well. Waiting for that PR to be merged before creating a new one

**Comment by llobetv** [comment]
I try but a new error  happened link to spikeexctractor, i hadn't time to go deeper in that today... , I'll check tomorrow morning and I will keep you informed

**Comment by alejoe91** [comment]
you should pull the latest master form spikeextractors too. I'll make a new release of all packages tomorrow

**Comment by alejoe91** [comment]
I'll merge this as it works on my side :)

**Comment by alejoe91** [comment]
fixed
