### ISSUE TITLE
Waveform extraction - Bus error

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#314]
There is a bug in export_to_phy function:

(spikeinterface) llobet@nspc28:/mnt/ssd/spikeinterface_test$ python launch_spikeinterface.py 
Waveform 1/227                                                                                                                                      
Waveform 2/227                                                                                                                                      
Waveform 3/227                                                                                                                                      
Waveform 4/227                                                                                                                                      
Waveform 5/227                                                                                                                                      
Waveform 6/227                                                                                                                                      
Bus error 

And when I check tmp file .raw file are not create anymore...

Here my  code:

class spikeInterfaceClass():
    """
    check https://spikeinterface.readthedocs.io/en/latest/index.html
    """
    def run_ms(self, file_path, prb_file, ms4_params, numchan=64, sampling_frequency=30000, 
                   dtype=np.int16, dead_channels=[], output_folder="analysis/",
                   tmp="/mnt/hdd/mountainlab/mountainlab/", verbose=True):
        """
        - file_path: str, path + filename for raw data
        
        - prb_file: str, path + filename for probefile, format:
        channel_groups = {
            0: {
                'channels': [1, 0],
                'geometry': [[0, 0], [0, 1]],
                'label': ['first_channel', 'second_channel'],
                },
            1: {
                'channels': [2, 3],
                'geometry': [[3,0], [3,1]],
                'label': ['third_channel', 'fourth_channel'],
                }
        }

        - ms4_params: dict, params for mountainSort, ex: 
        ms4_params= {'detect_sign': 0, 'adjacency_radius': 51, 'freq_min': 150, 
                     'freq_max': 4000, 'filter': True, 'whiten': True, 'curation': False, 
                     'num_workers': 40, 'clip_size': 40, 'detect_threshold': 3, 
                     'detect_interval': 10, 'noise_overlap_threshold': 0.15}
            
        
        - num_chan: int, number of channel
        - sampling_frequency: int, sampling rate
        - dtype:type of raw data (for other format convert to raw data or use 
                                  spikeInterface looader for these data)
        - dead_channels: list of int, indef of dead channels
        - output_folder: str, folder with analysis results
        - tmp: str, directory for tmp file
        """
        #temp file for MS4
        os.environ['TEMPDIR'] = tmp
        if not os.path.isdir(tmp):
            os.makedirs(tmp)

        #get raw data and eventually filter it and/or median substraction
        recording = se.BinDatRecordingExtractor(file_path, sampling_frequency, numchan, dtype)
        recording_prb = recording.load_probe_file(prb_file)

        recording_remove_bad = st.preprocessing.remove_bad_channels(recording_prb, 
                                                                    bad_channel_ids=dead_channels)

        #launch mountainSort
        # sorting_MS4 = ss.run_mountainsort4(recording=recording_remove_bad, 
        #                                     output_folder=output_folder, 
        #                                     verbose=verbose, **ms4_params)
        sorting_MS4 = se.MdaSortingExtractor(file_path=output_folder+"firings.mda",
                                            sampling_frequency=sampling_frequency)
        #set tmp folder for postporcessing, + "t/tmp" cauz otherwisde it suppress 
        #tmp file
        if not os.path.isdir(tmp + "/tmp"):
            os.makedirs(tmp + "/tmp")
        sorting_MS4.set_tmp_folder(tmp + "/tmp") 
        #export to phy
        st.postprocessing.export_to_phy(recording_prb, sorting_MS4, 
                                        output_folder + "phy/", n_comp=2, 
                                        electrode_dimensions=None, grouping_property=None, 
                                        ms_before=1, ms_after=1.5, dtype=None, 
                                        amp_method='absolute', amp_peak='both', 
                                        amp_frames_before=3, amp_frames_after=3, 
                                        #max_spikes_per_unit=2000,
                                        max_spikes_for_pca=10000, max_channels_per_template=16, 
                                        recompute_info=False, save_features_props=True, 
                                        verbose=verbose, memmap=True, seed=0)

        # label bad unit as noise
        # isi_violations = st.validation.compute_isi_violations(sorting_MS4, 
        #                                                       isi_threshold=0.001, 
        #                                                       min_isi=0.0005)
      
file_path = "/mnt/ssd/spikeinterface_test/data/2020_01_01_test_US_4_64_30kHz/amplifier_sorted.dat"
dead_channels = [22]

prb_file = "64_para.prb"
numchan = 64
sampling_frequency = 30000
dtype = np.int16

output_folder = "./analysis/"

ms4_params= {'detect_sign': 0, 'adjacency_radius': 51, 'freq_min': 150, 
              'freq_max': 6000, 'filter': True, 'whiten': True, 'curation': False, 
              'num_workers': 40, 'clip_size': 40, 'detect_threshold': 3, 
              'detect_interval': 10, 'noise_overlap_threshold': 0.15}

tmp = "/mnt/ssd/tmp/"

si = spikeInterfaceClass()
si.run_ms(file_path, prb_file, ms4_params, numchan, sampling_frequency, 
                   dtype, dead_channels, output_folder,
                   tmp, verbose=True)

**Comment by alejoe91** [comment]
Hi @llobetv 

I think the proble could be that the tmp folder is full given all crashes. Can you try deleting all the folders starting with tmp?

**Comment by alejoe91** [comment]
did you check the `/mnt/hdd/mountainlab/mountainlab/` folder and saw no .raw files there?

**Comment by llobetv** [comment]
yes I check and their was nothing

**Comment by alejoe91** [comment]
ok. Can you add this line before you call the `export_to_phy`:

`print(sorting_MS4.get_tmp_folder()`

Just to make sure it is correct.

**Comment by llobetv** [comment]
It's correct

**Comment by llobetv** [comment]
I'll check manually with pdb where file are saved

**Comment by llobetv** [comment]
It appear that manual tmp directory is remove in _extract_waveforms_one_unit:
sorting object is set to dict l.106 and then back to sorting object l.1367 . 
At this point sorting.get_tmp_folder() return default value '/tmp/tmpkf9ancyo'

**Comment by llobetv** [comment]
and finally waveform are saved int /tmp directory which is too small in my cases

**Comment by alejoe91** [comment]
great catch!!! will fix that. I can pre-allocate memmapped arrays like it's done when n_jobs>1 :)
Thanks for looking into this. I'll make a PR by the end of the day

**Comment by llobetv** [comment]
The issue is solved with new PR
