### ISSUE TITLE
export_to_phy, params.py dat_path

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#319]
Hi :)
Just a small comment,
by default dat_path in params.py take absolute (/mnt/ssd/spikeinterface_test/data/2020_01_01_test_US_4_64_30kHz/analysis/phy/recording.dat in my case) path in export_to_phy function. So when you move your phy directory it doesn't find it anymore and you have to change it manually.

One thing that could be done easely is to set relative path for dat_path, and just set it as recording.dat, as recording.dat move with phy directory

Cheer,
Victor

**Comment by alejoe91** [comment]
Hi Victor! Can you test if it works when you launch Phy from another directory? In that case I agree it's a good idea :)

**Comment by llobetv** [comment]
Yep it works

**Comment by alejoe91** [comment]
Sweet! Do you want to make a PR?

**Comment by llobetv** [comment]
Yep I can, I never did that but it would be nice to learn

**Comment by alejoe91** [comment]
Then give it a try :) it's easy: fork, make changes, push, open a PR

**Comment by llobetv** [comment]
Ok I'll try this!

**Comment by llobetv** [comment]
#320
