### ISSUE TITLE
Recursive loading in export to phy, st.get_unit_waveforms, sw.plot_unit_waveforms, others maybe

### ISSUE THREAD

**Issue by banchan86** [SpikeInterface/spiketoolkit#321]
Hi all

Upon running this command 

```
st.postprocessing.export_to_phy(recording_cmr, 
                                sorting_KL_all, output_folder='phy_KL_detect_8_new', max_spikes_for_pca=100000)
```

it gets stuck in a loop till it fails with a memory error:
```
Loading Open-Ephys: reading settings.xml...
Decoding data from  openephys  format
Reading all channels
104_CH9.continuous
104_CH10.continuous
104_CH11.continuous
104_CH12.continuous
104_CH13.continuous
104_CH14.continuous
104_CH15.continuous
104_CH16.continuous
104_CH17.continuous
104_CH18.continuous
104_CH19.continuous
104_CH20.continuous
104_CH21.continuous
104_CH22.continuous
104_CH23.continuous
104_CH24.continuous
Automatically removing channels: []
Loading Open-Ephys: reading settings.xml...
Decoding data from  openephys  format
Reading all channels
104_CH9.continuous
104_CH10.continuous
104_CH11.continuous
104_CH12.continuous
104_CH13.continuous
104_CH14.continuous
104_CH15.continuous
104_CH16.continuous
104_CH17.continuous
104_CH18.continuous
104_CH19.continuous
104_CH20.continuous
104_CH21.continuous
104_CH22.continuous
104_CH23.continuous
104_CH24.continuous
Automatically removing channels: []
Loading Open-Ephys: reading settings.xml...
Decoding data from  openephys  format
Reading all channels
104_CH9.continuous
104_CH10.continuous
104_CH11.continuous
104_CH12.continuous
104_CH13.continuous
104_CH14.continuous
104_CH15.continuous
104_CH16.continuous
104_CH17.continuous
104_CH18.continuous
104_CH19.continuous
104_CH20.continuous
104_CH21.continuous
104_CH22.continuous
104_CH23.continuous
104_CH24.continuous
Automatically removing channels: []
Loading Open-Ephys: reading settings.xml...
Decoding data from  openephys  format
Reading all channels
104_CH9.continuous
104_CH10.continuous
104_CH11.continuous
104_CH12.continuous
104_CH13.continuous
104_CH14.continuous
104_CH15.continuous
104_CH16.continuous
104_CH17.continuous
104_CH18.continuous
104_CH19.continuous
```
This didn't happen before with an old version of the st toolkit=0.5.2.

recording_cmr is a OpenEphys recording that has been median filtered with st.preprocessing.common_reference and sorting_KL_all is a se.SpykingCircusSortingExtractor

**Comment by alejoe91** [comment]
Hi @banchan86 
Thanks for the issue. Can you try to figure out where it hangs? I don't recall any while loop in the code.. if you ctrl+c, where does it stop?

**Comment by banchan86** [comment]
I have reduced the code to 4 lines skipping the preprocessing steps and it still loops. Could this be a problem with the OpenEphysRecordingExtractor? although other steps seem to work fine, the loop only comes in export to phy

```
recording_file = 'day_4\LPOA_pilot_2_2020-03-10_15-50-15_day4a'
recording = se.OpenEphysRecordingExtractor(recording_file)
sorting_KL_all=se.SpykingCircusSortingExtractor('results_all_spyking_8_no_merge_cc')
st.postprocessing.export_to_phy(recording, sorting_KL_all, output_folder='phy_KL_detect_8_new', max_spikes_for_pca=100000)
```
If i ctrl+c i think it just stops during loading, theres no indication it ever goes beyond that but heres the traceback

---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-4-c3b6abe33971> in <module>
      1 # takes about 30 minutes
      2 st.postprocessing.export_to_phy(recording, 
----> 3                                 sorting_KL_all, output_folder='phy_KL_detect_8_new', max_spikes_for_pca=100000)

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in export_to_phy(recording, sorting, output_folder, compute_pc_features, max_channels_per_template, **kwargs)
    982     spike_templates, templates, templates_ind, similar_templates, channel_map_si, channel_groups, \
    983     positions = _get_phy_data(recording, sorting, compute_pc_features,
--> 984                               max_channels_per_template, **kwargs)
    985 
    986     # Save .tsv metadata

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in _get_phy_data(recording, sorting, compute_pc_features, max_channels_per_template, **kwargs)
   1410                                    recompute_info=recompute_info, max_channels_per_waveforms=max_channels_per_template,
   1411                                    save_property_or_features=save_property_or_features, verbose=verbose, memmap=memmap,
-> 1412                                    seed=seed, compute_pc_features=compute_pc_features)
   1413 
   1414     channel_map = np.arange(recording.get_num_channels())

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in _get_quality_metric_data(recording, sorting, n_comp, ms_before, ms_after, dtype, amp_method, amp_peak, amp_frames_before, amp_frames_after, max_spikes_per_unit, max_spikes_for_amplitudes, max_spikes_for_pca, recompute_info, max_channels_per_waveforms, save_property_or_features, n_jobs, verbose, seed, memmap, compute_pc_features)
   1230                                                                        memmap=memmap, return_idxs=True,
   1231                                                                        max_channels_per_waveforms=
-> 1232                                                                        max_channels_per_waveforms)
   1233     else:
   1234         waveforms, spike_index_list, channel_list = None, None, None

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in get_unit_waveforms(recording, sorting, unit_ids, channel_ids, return_idxs, **kwargs)
    238                                                                                        max_spikes_per_unit, n_pad,
    239                                                                                        dtype, seed, verbose,
--> 240                                                                                        memmap_array=None)
    241                     waveform_list.append(waveforms)
    242                     spike_index_list.append(indexes)

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in _extract_waveforms_one_unit(unit, rec_arg, sort_arg, channel_ids, unit_ids, grouping_property, compute_property_from_recording, max_channels_per_waveforms, max_spikes_per_unit, n_pad, dtype, seed, verbose, memmap_array)
   1694                                                           snippet_len=n_pad,
   1695                                                           channel_ids=channel_ids,
-> 1696                                                           seed=seed)
   1697                 wf = wf.astype(dtype)
   1698                 if max_channels_per_waveforms < len(channel_ids):

~\Anaconda3\envs\spikesorting2\lib\site-packages\spiketoolkit-0.6.1-py3.6.egg\spiketoolkit\postprocessing\postprocessing_tools.py in _get_random_spike_waveforms(recording, sorting, unit, max_spikes_per_unit, snippet_len, channel_ids, seed)
   1059 
   1060     spikes = recording.get_snippets(reference_frames=st[event_indexes].astype('int64'),
-> 1061                                     snippet_len=snippet_len, channel_ids=channel_ids)
   1062     return spikes, event_indexes
   1063 

~\Anaconda3\envs\spikesorting2\lib\site-packages\spikeextractors-0.8.1-py3.6.egg\spikeextractors\recordingextractor.py in get_snippets(self, reference_frames, snippet_len, channel_ids)
    186         num_snippets = len(reference_frames)
    187         num_channels = len(channel_ids)
--> 188         num_frames = self.get_num_frames()
    189         snippet_len_total = int(snippet_len_before + snippet_len_after)
    190         snippets = np.zeros((num_snippets, num_channels, snippet_len_total))

~\Anaconda3\envs\spikesorting2\lib\site-packages\spikeextractors-0.8.1-py3.6.egg\spikeextractors\extractors\openephysextractors\openephysextractors.py in get_num_frames(self)
     34 
     35     def get_num_frames(self):
---> 36         return self._recording.analog_signals[0].signal.shape[1]
     37 
     38     def get_sampling_frequency(self):

~\Anaconda3\envs\spikesorting2\lib\site-packages\pyopenephys\core.py in analog_signals(self)
    394         if self._analog_signals_dirty:
    395             self._analog_signals = []
--> 396             self._read_analog_signals()
    397 
    398         return self._analog_signals

~\Anaconda3\envs\spikesorting2\lib\site-packages\pyopenephys\core.py in _read_analog_signals(self)
    697                         print(f)
    698                         fullpath = op.join(self.absolute_foldername, f)
--> 699                         sig = loadContinuous(fullpath)
    700                         block_len = int(sig['header']['blockLength'])
    701                         sample_rate = float(sig['header']['sampleRate'])

~\Anaconda3\envs\spikesorting2\lib\site-packages\pyopenephys\openephys_tools.py in loadContinuous(filepath, dtype)
     64         else:  # Keep data in signed 16 bit integer format.
     65             data = np.fromfile(f, np.dtype('>i2'), N)  # big-endian 16-bit signed integer
---> 66         samples[indices[recordNumber]:indices[recordNumber + 1]] = data
     67 
     68         marker = f.read(10)  # dump

KeyboardInterrupt:

**Comment by banchan86** [comment]
ok hang on running it from a python script clears it so it must be something with Jupyter notebook caching the output from a previous run and the offending line is somewhere else

**Comment by banchan86** [comment]
ok seems like the issue isn't with the export to phy its with the sorting extractor as trying to plot the unit waveforms itself triggers this file loading recursivity (that seems to stop after 4-5 loops so not exactly a while loop). ill investigate further before making an issue in that repository

**Comment by banchan86** [comment]
ok i think i figured out what the problem is

at least for st.get_unit_waveforms and sw.plot_unit_waveforms, the recursive loading occurs for every unit_id that is retrieved. is that intended behaviour?

for instance running st.postprocessing.get_unit_waveforms(recording_cmr, sorting_KL_all, unit_ids  = range(3) will load the recording 3 times (i know this because theres a statement for "Automatically removing channels: []" attached to each loop)

running sw.plot_unit_waveforms(recording_cmr, sorting_KL_all, unit_ids=range(5)) loads the recording 5 times.

my guess is that export to phy loads the recording a gazillion times for all the units, although i havent tested it.

is that intended behaviour? each load of the recording file takes like 15 minutes for me for a 16 channel 45 min recording. 

disregard what i said earlier about it working in a python script, that didn't finish too even though it only printed the loop once.

**Comment by alejoe91** [comment]
Hi @banchan86 

Here is what's happening. In order to allow for parallel processing, the recording is serialized and passed to the function that extract waveforms. Inside the function, the recording is re-instantiated and this is very time comsuming fotr the OpenEphys extractor (using the open ephys format -- I highly recommend switching to the binary format which is much more efficient).

So this is why you are seing multiple prints saying that the recording is being loaded.

There is a solution though :) 
You can use the `CacheRecordingExtractor`:
```
recording_cache = se.CacheRecordingExtractor(recording_cmr)
```

This creates a binary array with the process data (in your case the open ephys data after cmr), dumps it to file, and memory maps them (so it also saves RAM).  If you do that, the processing should be much faster :)

We're currently updating the docs, but this caching system is highly recommended before postprocessing. 

Before you try, please upgrade `spikeextractors` because I pushed some fixes (version 0.8.2).
Let me know if that solves the issue!

Cheers,
Alessio

**Comment by banchan86** [comment]
Ok thanks alessio I will try it out! 
So just have one question do i need to convert the OpenEphys recording extractor object to binary first before using CacheRecording Extractor?

**Comment by alejoe91** [comment]
Nope! It takes any recording extractor. It just dumps the traces, whatever they are :)

**Comment by banchan86** [comment]
thanks works beautifully :)
