### ISSUE TITLE
validation.compute_metrics fails when specifying unit_ids

### ISSUE THREAD

**Issue by TRuikes** [SpikeInterface/spiketoolkit#323]
When giving a list of unit ID's to 'compute_metrics' , the function can break:

```python
res = st.validation.compute_metrics(
    sorting=sorting_klusta,
    recording=recording_klusta,
    metric_names=['firing_rate'],
    isi_threshold=0.001,
    unit_ids=[unit_ids[2], unit_ids[3]]
)
```

Due to `metrics.calculate_firing_rate_and_spikes` not taking 'unit_ids' as input, and assuming it should loop over all unique values in the proved `spike_clusters`.

```
c:\users\thijs\miniconda3\envs\test_sp_3\lib\site-packages\spiketoolkit\validation\quality_metrics.py in compute_metrics(sorting, recording, sampling_frequency, isi_threshold, min_isi, snr_mode, snr_noise_duration, max_spikes_per_unit_for_snr, drift_metrics_interval_s, drift_metrics_min_spikes_per_interval, max_spikes_for_silhouette, num_channels_to_compare, max_spikes_per_cluster, max_spikes_for_nn, n_neighbors, n_comp, ms_before, ms_after, dtype, max_spikes_per_unit, amp_method, amp_peak, amp_frames_before, amp_frames_after, recompute_info, max_spikes_for_pca, apply_filter, freq_min, freq_max, save_features_props, metric_names, unit_ids, epoch_tuples, epoch_names, return_dataframe, verbose, seed)
    977 
    978     if 'firing_rate' in metric_names:
--> 979         firing_rates_epochs = metric_calculator.compute_firing_rates()
    980         metrics_epochs.append(firing_rates_epochs)
    981 

c:\users\thijs\miniconda3\envs\test_sp_3\lib\site-packages\spiketoolkit\validation\metric_calculator.py in compute_firing_rates(self)
    377         for epoch in self._epochs:
    378             in_epoch = np.logical_and(self._spike_times > epoch[1], self._spike_times < epoch[2])
--> 379             firing_rates_all, _ = metrics.calculate_firing_rate_and_spikes(self._spike_times[in_epoch],
    380                                                                            self._spike_clusters[in_epoch],
    381                                                                            self._total_units, verbose=self.verbose)

c:\users\thijs\miniconda3\envs\test_sp_3\lib\site-packages\spikemetrics\metrics.py in calculate_firing_rate_and_spikes(spike_times, spike_clusters, total_units, verbose)
    201 
    202         for_this_cluster = (spike_clusters == cluster_id)
--> 203         firing_rates[cluster_id] = firing_rate(spike_times[for_this_cluster],
    204                                                min_time=np.min(spike_times),
    205                                                max_time=np.max(spike_times))

IndexError: index 2 is out of bounds for axis 0 with size 2


```

**Comment by alejoe91** [comment]
Hi @TRuikes 
Thanks for reporting this.

@colehurwitz can you take care of this?

**Comment by colehurwitz** [comment]
Yeah, I was looking into reproducing this just now.

**Comment by TRuikes** [comment]
thanks

**Comment by colehurwitz** [comment]
I think this new PR should fix the bug. The metrics have to run over all the units and then pick out the units that were specified by the user. We were setting the total units to be the wrong value though which was causing an issue in the metric loops.

**Comment by colehurwitz** [comment]
Note for @alejoe91 , it would be nice if we could only compute the metrics on the specified units, but that will only work for some metrics (silhouette score needs to compute pairs for example). Firing rate is one where we could do it on the given units... but we need to think about if we only want to implement it for some metrics.

**Comment by colehurwitz** [comment]
@TRuikes if you want to give the PR a try, I think it should fix the problem.

**Comment by TRuikes** [comment]
works! I don't know how heavy the computations for all metrics are, but we've used Isolation Distance mostly, and that one can take up some load. Further we are using low threshold for detection, meaning we have multiple noise clusters (say 20) vs true clusters (~5), so in our current pipeline we save quite a lot of time by not computing Iso dist for all clusters. This is why I think only computing metrics for specified units might be a useful addition. 

An idea; if the user gives an invalid metricname in 'metric_names', instead of saying it's wrong, also print out valid options.

Then another bug I found, when calling (without recording, idk if you intend it to work like this):
```python
res = st.validation.compute_metrics(
    sorting=sorting_klusta,
    # recording=recording_klusta,
    metric_names=['num_spikes'],
    isi_threshold=0.001,
    unit_ids=[unit_ids[2], unit_ids[3]],
    verbose=True
)
```

giving:

```
Traceback (most recent call last):
  File "C:/Users/Thijs/Desktop/PhD/Code/Data_format_julien/data_format_julien/misc/test_sp.py", line 17, in <module>
    res = st.validation.compute_metrics(
  File "C:\Users\Thijs\Desktop\PhD\Code\spike_interface_gits\spiketoolkit\spiketoolkit\validation\quality_metrics.py", line 1126, in compute_metrics
    md = MetricData(sorting=sorting, sampling_frequency=recording.get_sampling_frequency(), recording=recording,
AttributeError: 'NoneType' object has no attribute 'get_sampling_frequency'
```

**Comment by alejoe91** [comment]
I agree that it should be possible to pass a subset of units. Note that for now you could also build a SubSortingExtractor and filter out the good units only!

**Comment by colehurwitz** [comment]
I think those are some good suggestions. I can look into:

1. Computing metrics on a subset... I have an idea for that.
2. Printing valid names is good idea.
3. I will figure out that bug about not passing in the recording. Seems like it should be a quick fix.

**Comment by colehurwitz** [comment]
I will make new issues for these and close this one.
