### ISSUE TITLE
Validation metrics for spike sorting

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#33]
This would cover some validation metrics for spike sorting without ground truth.

**Comment by alejoe91** [comment]
same as https://github.com/SpikeInterface/spiketoolkit/issues/11

**Comment by alejoe91** [comment]
We could use some of this code, or the entire package:

https://github.com/spike-sorting-validation/spikesortingvalidation

Maybe we should reach out to Pierre?

@colehurwitz31 @magland @samuelgarcia @mhhennig

**Comment by samuelgarcia** [comment]
I started with Pierre Yger this repo 2 years agao.
But this repo is totally empty !! It was just a very begining (1 hour of work).
This is why I am here.
I will remove that old repo as soon as spikeinterface will be mature enough.
Note I prefer evry thing here except the name of the package (I prefer the old one  :)

Pierre plan to be in the meeting.

**Comment by alejoe91** [comment]
we have issues for different metrics. closing
