### ISSUE TITLE
compute isi violation

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#336]
Hi, 
I encounter issues using  compute_isi_violations function. I found some abherant values...

If I set min_isi to 0.0005 (which is min of isi value take into account?) and isi_threshold to 0.001 (which is max of isi value take into account?, the doc is not absolutly clear about that but this is the more logical) I got 0.7 for this unit:
![image](https://user-images.githubusercontent.com/22896067/79348881-de6e8280-7f35-11ea-94e7-10ff64b0ea48.png)

When it is clear that on a window of 0.0005-0.001 their is really little number of spikes.

Furthermore when I use my own isi violation function I found really small value for isi violation with the same window.

Do you know what's happening?

Cheer,
Victor

**Comment by alejoe91** [comment]
Hi Victor,

@colehurwitz should be able to answer that! We are in the process of updating the docs about that, so sorry about the confusion!

Cheers,
Alessio

**Comment by colehurwitz** [comment]
I will look into this

**Comment by colehurwitz** [comment]
So I figured out the issue:

`min_isi` sets a threshold for the duplicate spikes (any refractory period violation smaller than this is not taken into account for the isi score).

`isi_threshold`  is the actual isi violation threshold that contributes to the isi violation output. 

So min_isi can't be smaller than isi_threshold or strange behaviour will happen. We can enforce this in the function I think.

**Comment by colehurwitz** [comment]
It looks like there is a recently introduced bug in isi_violations:

``` 
isis = np.diff(spike_train)

if min_isi is not None:
   duplicate_spikes = np.where(isis <= min_isi)[0]
   spike_train = np.delete(spike_train, duplicate_spikes + 1)
else:
   min_isi = 0
```

As can be seen, the isis are calculated before duplicate spikes (determined by min_isi) are removed. So it looks like min_isi is being ignored in the calculation. I can make a PR for this.

**Comment by alejoe91** [comment]
Also maybe @jsiegle can provide some input!

**Comment by jsiegle** [comment]
Cole's fix is correct—the ISIs need to be re-computed after deleting duplicate spikes.

**Comment by alejoe91** [comment]
Thanks @jsiegle

Another thing: why is the default [min_isi=0.000166](https://github.com/AllenInstitute/ecephys_spike_sorting/blob/a073e3b6bae18286c4afedd084100ba1ae59cb9a/ecephys_spike_sorting/scripts/create_input_json.py#L171)? Shouldn't it be half of the sampling frequency?
In that case it's missing a 0 (it should be 16.6 us ~ 1 / 30kHz *0.5 = 0.0000166)

**Comment by colehurwitz** [comment]
Hey @llobetv , would you mind posting your isi violation function so we can compare?

**Comment by jsiegle** [comment]
Hi @alejoe91, in the `ecephys_spike_sorting` repo, the 0.000166 min ISI value reflects the fact that there's a step prior to computing the metrics that removes putative double-counted spikes within that window. In the case of `spikemetrics`, there should indeed be another zero added.

**Comment by alejoe91** [comment]
Thanks @jsiegle 

Than I'll change it to `1 / fs * 0.5`!

**Comment by llobetv** [comment]
Here my code:
```
def contamination_ratio(list_sample, sampling_rate, refractory_time, censored_time, n_of_samples):
    """
    return ratio of contamination in 1 cluster base on its refractory period contamination, don't work very well for unit with freq < 1 Hz and N spike < 4000 (censored = 0.5e-3 and refractory 1e-3)
    
    it's supposed that contamination can be in refractory period of an other contamination spike
    
    - list_sample : list or np.array with sample of each spike of 1 cluster
    - sampling_rate : int
    - refractory_time : time considered as refractory time, in second
    - censored_time : min time between spikes when there is the spike detection
    - n_of_samples : number of sample in the recording
    
    """
    
    assert refractory_time > censored_time, "censored period is higher than refractory period"

    # pdb.set_trace()
    
    isi = np.diff(list_sample)
    isi_time = isi/float(sampling_rate)
    
    refractory_violation_count = np.count_nonzero((isi_time < refractory_time) *\
                                            (isi_time > censored_time)) #count event between censored time and refractory time

    freq = (len(list_sample)*1.) / (n_of_samples/sampling_rate) # freq of the unit
    freq_censored_period = refractory_violation_count*1. / (len(list_sample) * (refractory_time - censored_time))
    ratio_contamination = freq_censored_period/freq

    # # this is the equivalent but less logic
    # ratio_contamination = (refractory_violation_count * n_of_samples/sampling_rate) /\
    #     (len(list_sample)**2 * (refractory_time - censored_time))

    return ratio_contamination
```

**Comment by alejoe91** [comment]
Ok, I see there are 2 discrepancies in the code. 

1. In [our implementation ](https://github.com/SpikeInterface/spikemetrics/blob/f47bef947a7ef254278c14b7093d82429f9a7eb9/spikemetrics/metrics.py#L494)the `violation_time` is multiplied by 2. @jsiegle can you clarify why is it so?

2. We use min_time and max_time to compute [total firing rate](https://github.com/SpikeInterface/spikemetrics/blob/f47bef947a7ef254278c14b7093d82429f9a7eb9/spikemetrics/metrics.py#L524). I think this is sub-optimal as it could not correspond the the length of the recording. @colehurwitz I suggest passing the recording duration to the spikemetrics functions.

**Comment by jsiegle** [comment]
The 2x multiplier accounts for the fact that the potential window for ISI violations extends both before and after each spike.

**Comment by colehurwitz** [comment]
The x2 makes sense as @jsiegle mentioned and it shows up in the original papers/implementations.

I can pass in recording duration as a param,  but we don’t need a recording to compute isi_violations so I think that should be optional.

**Comment by llobetv** [comment]
The 2x multiplier would be only if you count both widows before and after each spikes but here you use np.diff() so you take only window after each spike, not the one before. 
So you have to remove it.

I try your function and mine on real datas and for the next unit your algo found 0.56 and mine 1.11:
![image](https://user-images.githubusercontent.com/22896067/79638126-3a2e4b00-8184-11ea-897b-47e938e3d5ff.png)
bin: 0.33ms, isi_threshold=1ms, min_isi=0.5ms

**Comment by alejoe91** [comment]
@jsiegle I think that @llobetv makes a good point here. What do you think?

**Comment by colehurwitz** [comment]
@alejoe91 and I discussed the window in isi_violations and we still think that the x2 multiplier is necessary for the computation when using `np.diff`:

For an example with arbitrary units:

```
refractor_viol_time = 5
spike_times = [10, 18, 20, 24]
np.diff(spike_times) = [8, 2, 4]
num_refractory_violations = 2
```
So using `np.diff` will actually take into account the window before and after the spikes by default.

**Comment by jsiegle** [comment]
Was just about to respond to this. To add some context: the original definition of this metric comes from [Hill, Mehta, and Kleinfeld (2011)](https://www.jneurosci.org/content/31/24/8699). The idea behind it is that, out of _N_ spikes in a cluster, some fraction _f<sup>p</sup>_ are from contaminating units. The remainder, _N_(1-_f<sup>p</sup>_), are true spikes. For every true spike, there are two opportunities for a violation, both before and after. Therefore, the total number of actual violations, `np.sum(np.diff(spike_times) > viol_time)`, is computed separately from the amount of time theoretically available for violations, 2 _t<sub>r</sub>_ * _N_(1-_f<sup>p</sup>_), which is where the 2x multiplier comes in.

One thing I don't love about this metric is that it's actually measuring (1-_f<sup>p</sup>_) * _f<sup>p</sup>_, which is the fraction of true spikes multiplied by the fraction of contaminating spikes. This is not something for which we have an immediate intuition, as we would for, say, the overall rate of ISI violations throughout the experiment.

**Comment by llobetv** [comment]
You are right, my bad...
So Isi violation for full noised cluster is expected to be close to 0.5?

Isn't their a way to correct the value to get True noise contamination ratio? I make few test and error in calculation seems stable.
Here isi_violation calc for several units with *2. y axis is real contamination and x axis is isi_violation

![image](https://user-images.githubusercontent.com/22896067/80094225-2d37a000-8566-11ea-8f30-a98224260eaf.png)

The drop at the end is probably due to underestimation in num_refractory_violations when 2 consecutives spikes are closer that isi violation period. Then with np.diff you only count 2 violation when real number of violation should be 3.

**Comment by llobetv** [comment]
I try to find what sould be calculated isi_violation based on true contamination ratio and I found:
isi_violation = contamination - 0.5*contamination**2

So I solve it and found:
contamination = 1 - (1 - 2*isi_violation)**0.5

It give me this curve which is still not perfect (I don't know what is lacking...) but much better:
![image](https://user-images.githubusercontent.com/22896067/80102765-8954f100-8573-11ea-8d0a-49a23da710cb.png)


Here i add correction of the drop (I calc isi on 10th closest spike instead of 1):

![image](https://user-images.githubusercontent.com/22896067/80102811-9b369400-8573-11ea-9cbc-0fa71849cf8e.png)

**Comment by llobetv** [comment]
I found one issue, I overestimate window duration of 1 sample, but now contamination ration is overestimated of 7%.
![image](https://user-images.githubusercontent.com/22896067/80112620-98db3680-8581-11ea-9849-cb57bbc2f710.png)


For the method I take real unit with isi_violation = 0 and I add random spike, so I know real contamination ratio. 
I also calculate  isi on 10th closest spike instead of 1.

**Comment by llobetv** [comment]
OK i finally found the origin of overestimation, my std was too high and cannot be inferior to 0.

Here the final curve with 6 units (longer recording so less variability):

![image](https://user-images.githubusercontent.com/22896067/80124494-a21fcf80-8590-11ea-969c-bb33a49abdeb.png)

**Comment by alejoe91** [comment]
Thanks again for looking into this @llobetv 

Will close the issue (and I promise we'll improve the docs)!
