### ISSUE TITLE
postprocessing.export_to_phy uses an absurd amount of memory

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#339]
Hi,

I have a phy folder containing about 7GB a data (30 min, 64 channels, 30 kHz).

I am trying to write a code to remove duplicated spikes, here is the following code:

```
phy_folder = "/home/aze/Documents/data"
save_folder = "/home/aze/Documents/data/test"
recording = se.PhyRecordingExtractor(phy_folder)
sorting = se.PhySortingExtractor(phy_folder)

# Code to remove duplicated spikes from sorting

st.postprocessing.export_to_phy(recording, sorting, output_folder = save_folder, verbose = False, n_jobs = 1, memmap = True)
```

When I run this code, when reaching `export_to_phy`, bit runs for about a minute without using a lot of memory (it seems to be copying the data file during this time). Then suddendly, the RAM usage increases over time, and then my program crashes due to "not enough memory on my system".
I have 16 GB of RAM + 16 Gb of swap, and the program crashes when both become full (before running it, only 3GB of RAM were being used).

I don't understand why exporting data that is about 7GB takes more than 32GB of RAM?

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

Can you make sure you are using the master version? we are currently making a lot of updates (same for spikeextractors), but we should be almost done.

What OS are you using? Whats is the terminal output using verbose=True?

**Comment by Dradeliomecus** [comment]
I am using the master branch version, updated this morning.
I am using Ubuntu 18.04.4 LTS.

The output when `verbose = True` is :
```
Waveform 1/125
Killed
```

**Comment by alejoe91** [comment]
Ok let me try to replicate this. It might be due to the `PhySortingExtractor`. In the meanwhile can you try to see if this PR https://github.com/SpikeInterface/spiketoolkit/pull/340 solves the memory issue (using the same args).

**Comment by Dradeliomecus** [comment]
I did:
```
cd ~/dev/spike_interface/spiketoolkit
git checkout postprocessing_dump
python setup.py install
```

I hope this is what you meant.
It didn't solve the issue.

**Comment by llobetv** [comment]
Hi :) , 
I'm working with Dradeliomecus.
I have the same issue, which disapear when n_jobs>1.
I try your update but it didn't solve memory consumption, but it solve an other issue that I encounter when we try to remove duplicate spikes and then export to phy (and that also wasn't present with n_jobs>1)

**Comment by alejoe91** [comment]
Hi @llobetv 

How do you guys remove duplicate spikes? Maybe that actually can contribute to the issue in the way the recording and sorting are 'passed' to the extract wavefirn function

**Comment by Dradeliomecus** [comment]
Here is the complete code:

```
recording = se.PhyRecordingExtractor(phy_folder)
sorting = se.PhySortingExtractor(phy_folder)

# For each unit, look at all spikes. If there is a spike
# followed by another one with less than "window_duplicate" timepoints,
# consider it a duplicate and remove the second spike.
for unit_id in sorting.get_unit_ids():
    spike_train = sorting.get_unit_spike_train(unit_id = unit_id)   # Contains the time at which all spikes where captured (in timepoints).
    time_diff_spikes = np.diff(spike_train)                         # At index i, contains the time difference between spikes i and spike i+1.
    duplicates = np.where(time_diff_spikes < window_duplicate)[0]+1 # Contains the indices of the second spike (the one to remove).

    # Remove the duplicated spikes from the spike trains.
    sorting._spiketrains[sorting.get_unit_ids().index(unit_id)] = np.delete(spike_train, duplicates)

    # Update the amplitudes accordingly.
    if(unit_id in sorting._features.keys()):
        amp = sorting.get_unit_spike_features(unit_id, 'amplitudes')
        pc_feat = sorting.get_unit_spike_features(unit_id, 'pc_features')
        sorting.set_unit_spike_features(unit_id, 'amplitudes', np.delete(amp, duplicates, axis = 0))
        sorting.set_unit_spike_features(unit_id, 'pc_features', np.delete(pc_feat, duplicates, axis = 0))


# Now, save the data
st.postprocessing.export_to_phy(recording, sorting, output_folder = save_folder, verbose = True, n_jobs = 1, memmap = True)
```

**Comment by alejoe91** [comment]
Do you get the same bug if you don't run the remove duplicate code?

**Comment by Dradeliomecus** [comment]
Removing the for loop still yields to the same problem.

**Comment by alejoe91** [comment]
Ok I'll look into it! 

BTW, you should not set spiketrains like this: `sorting._spiketrains`.
The changes otherwise will note be considered if you use get_waveforms. THis is because with joblib the recording and sorting objects are *dumped* to a dictionare and they are re-initialized inside each job. So if you make in-memory changes they won't be considered. A workaround would be to save the sorting after duplicate removal (e.g. using the NpzSortingExtractor) and then reload it. Now the changes are saved to a file

**Comment by alejoe91** [comment]
Mmm I can't reproduce the error using the same extractors.. maybe you guys could share a zip file with your data by email?

**Comment by Dradeliomecus** [comment]
Alright thanks !

Yes I know I shouldn't change a variable that start with an underscore, but I didn't find any method so remove spikes by their index.

I tried to save the sorting using PhySortingExtractor.write_sorting, but as you told me it shouldn't be used.
I'm gonna look at the NpzSortingExtractor, thank you for the tip!

**Comment by alejoe91** [comment]
> Hi :) ,
> I'm working with Dradeliomecus.
> I have the same issue, which disapear when n_jobs>1.
> I try your update but it didn't solve memory consumption, but it solve an other issue that I encounter when we try to remove duplicate spikes and then export to phy (and that also wasn't present with n_jobs>1)

I guess the issue is that the changes where not propagated. That happens because of what I described above!

**Comment by alejoe91** [comment]
BTW, do you get the same bug if you set `memmap` to `False`? Just trying to figure out why this happens. The implementation looks should be the exact same regardless of n_jobs

**Comment by Dradeliomecus** [comment]
Yes, the same bug happens if I set `memmap` to `False`.

I am sending you the data folder to your gmail account (the one listed in your profile).

**Comment by alejoe91** [comment]
I found the problem. You have a very populated spiketrain 0 (283303 spikes). The length of each snippet (waveform) is 180 and you have 64 channels. There was a problem in `spikeextractors.get_snippet()`. Basically a large array is initialized and then populated with snippets, but we did not initialize the `dtype`. So it was effectively creating a `float64` array, whit size:

283303 * 180 * 64 * 8 ~ 26 gb

I fixed it here by setting the dtype from the recording (`int16`), so now it uses ~ 6gb for the first waveform. 

Can you check that [this PR](https://github.com/SpikeInterface/spikeextractors/pull/365) solves the issue? I also added the `CacheSortingExtractor` mechanism, so you can modify the spiketrains and cache them to a tmp file (a npz file) with one line of code.
```
sort_cache = se.CacheSortingExtractor(sorting)
# now the changes are bound to a file.
```

Regarding the modification of spiketrains, you can take a look at the [`CurationSortingExtractor`](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py). It should have everything you need to split units based on spike indexes.

Let me know if this fixes the issue!

**Comment by Dradeliomecus** [comment]
It's running and working!
Since I have a lot of spikes it seems to take a while (about an hour or two) but now I don't have the memory error!

I might change some parameters to make the process faster (like length of waveform, n_jobs ...).

Thank you very much!

**Comment by alejoe91** [comment]
Thank you for spotting this! Not an easy one to find ;)

**Comment by Dradeliomecus** [comment]
So I changed the last line of my code to:
`st.postprocessing.export_to_phy(recording, sorting, output_folder=save_folder, verbose=True, n_jobs=2, ms_before=3, ms_after=4, compute_pc_features=False, max_spikes_per_unit=2000, recompute_info=False, memmap=True)`
(with `n_jobs` to 1 or to 2)

Now it runs pretty quickly (5-10 min) and it correctly works exports all the data with the removed duplicates.
What's the advantage to using `NpzSortingExtractor` or `CacheSortingExtractor` rather than the method I'm using?

Thank you!

**Comment by alejoe91** [comment]
So if you change the _spiketrains without dumping the extractor, the changes are not bound to a file. Therefore, if n_jobs>1, the changes to the spiketrains are not kept, as the extractor is reloaded from the file in each subprocess (so the duplicates are not removed).

**Comment by Dradeliomecus** [comment]
Well I ran my code with `n_jobs=2` and the duplicates were actually removed.

Maybe it's not supposed to do that, but it does ^^

**Comment by alejoe91** [comment]
Without saving to `NpzSortingExtractor`? I find it very strange, because in the subprocess the sorting is reloaded and it loses any info about the underlying _spiketrains

**Comment by Dradeliomecus** [comment]
Yers without `NpzSortingExtractor` begin run. Here is the entire code:

```
recording = se.PhyRecordingExtractor(phy_folder)
sorting = se.PhySortingExtractor(phy_folder)

# For each unit, look at all spikes. If there is a spike
# followed by another one with less than "window_duplicate" timepoints,
# consider it a duplicate and remove the second spike.
for unit_id in sorting.get_unit_ids():
    spike_train = sorting.get_unit_spike_train(unit_id=unit_id)     # Contains the time at which all spikes where captured (in timepoints).
    time_diff_spikes = np.diff(spike_train)                         # At index i, contains the time difference between spikes i and spike i+1.
    duplicates = np.where(time_diff_spikes < window_duplicate)[0]+1 # Contains the indices of the second spike (the one to remove).

    # Remove the duplicated spikes from the spike trains.
    sorting._spiketrains[sorting.get_unit_ids().index(unit_id)] = np.delete(spike_train, duplicates)

    # Update the amplitudes accordingly.
    if(unit_id in sorting._features.keys()):
        amp = sorting.get_unit_spike_features(unit_id, 'amplitudes')
        pc_feat = sorting.get_unit_spike_features(unit_id, 'pc_features')
        sorting.set_unit_spike_features(unit_id, 'amplitudes', np.delete(amp, duplicates, axis=0))
        sorting.set_unit_spike_features(unit_id, 'pc_features', np.delete(pc_feat, duplicates, axis=0))


# Now, save the data
st.postprocessing.export_to_phy(recording, sorting, output_folder=save_folder, verbose=True, n_jobs=2, ms_before=3, ms_after=4, compute_pc_features=False, max_spikes_per_unit=2000, recompute_info=False, memmap=True)
```

It removes very few spikes, but only the ones very close to each other (checked with the cross-correlogram).

I did it with the very same dataset I sent you yesterday, you can check it yourself if you want (unit 151 has 234,166 spikes before running the function, and after it becomes unit 115 with 234,092 spikes).

**Comment by alejoe91** [comment]
I'll try!

Just to be sure, these numbers: 

> I did it with the very same dataset I sent you yesterday, you can check it yourself if you want (unit 151 has 234,166 spikes before running the function, and after it becomes unit 115 with 234,092 spikes).

 are from the phy GUI?

Of course if you are in the same sessions the changes will hold (because you still have the `sorting` object). What I'm saying, is that the waveforms are extracted by subsampling all waveforms (not excluding the duplicates). If you do not set `max_spikes_per_unit`, this might lead to an error as there will be a mismatch between the number of spikes and the number of waveforms. 

I strongly recommend just adding: `sort_cache = se.CacheSortingExtractor(sorting)` befor exporting to phy, to make sure everything runs smooth.

Check out the CurationSortingExtractor otherwise. That keeps track of all the changes and should work!

**Comment by Dradeliomecus** [comment]
Ah yes, they come from the phy GUI.
And yes, not setting `max_spikes_per_unit` returns an error because 2 arrays are of different sizes.

I'm trying to understand how `CacheSortingExtractor` and `CurationSortingExtractor` work.
Do I need to export `sort_cache` or `sorting` with `export_to_phy()`?

**Comment by alejoe91** [comment]
You need to use `sort_cache`, which is a new `SortingExtractor`.

Caching basically just makes a copy of the current object and saves it to npz. It's what I suggested before, but a bit nicer :)

The CurationSortingExtractor is a bit more complicated and not documented. We could add a remove duplicates in the `curation` module that does that automatically. Maybe @colehurwitz can do it?

**Comment by Dradeliomecus** [comment]
Ok I get it.

Thank you very much for all the help!
