### ISSUE TITLE
Consensus Graph Method

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#34]
Development of comparison methods for multiple sorted datasets using graph algorithms

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/issues/22

basically same issue: closing https://github.com/SpikeInterface/spiketoolkit/issues/22

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/98
