### ISSUE TITLE
IndexError: index 12 is out of bounds for axis 0 with size 12

### ISSUE THREAD

**Issue by yarikoptic** [SpikeInterface/spiketoolkit#342]
Look how far I got myself into ;-)

anyways, trying to export my precious clustering results into `phy` format:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-13-4dbb7cd0178b> in <module>
      1 # phy is recommended for GUI to curate, data should be exported:
----> 2 st.postprocessing.export_to_phy(recording, klusta_out, output_folder='yoh-klusta/phy')

~/proj/misc/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py in export_to_phy(recording, sorting, output_folder, compute_pc_features, max_channels_per_template, **kwargs)
   1140     spike_templates, templates, templates_ind, similar_templates, channel_map_si, channel_groups, \
   1141     positions = _get_phy_data(recording, sorting, compute_pc_features,
-> 1142                               max_channels_per_template, **kwargs)
   1143 
   1144     # Save .tsv metadata

~/proj/misc/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py in _get_phy_data(recording, sorting, compute_pc_features, max_channels_per_template, **kwargs)
   1621 
   1622     # similar_templates.npy - [nTemplates, nTemplates] single
-> 1623     similar_templates = _compute_templates_similarity(templates, templates_ind)
   1624 
   1625     # spike_templates.npy - [nSpikes, ] uint32

~/proj/misc/spiketoolkit/spiketoolkit/postprocessing/postprocessing_tools.py in _compute_templates_similarity(templates, template_ind)
   1195                     reorder_t_ind_i[s] = np.where(t_ind_i == sc)[0]
   1196                     reorder_t_ind_j[s] = np.where(t_ind_j == sc)[0]
-> 1197                 t_i_shared = t_i[reorder_t_ind_i]
   1198                 t_j_shared = t_j[reorder_t_ind_j]
   1199                 t_i_lin = t_i_shared.reshape(t_i_shared.shape[0] * t_i_shared.shape[1])

IndexError: index 12 is out of bounds for axis 0 with size 12
```
This is a bleeding edge spiketoolkit (0.6.1-41-gffb4c2e, I believe with released 0.6.1 I had somewhat different exception).  

Full ipython notebook: https://github.com/vandermeerlab/data-formats/blob/893dcb7641a4980527bac54e3e7af6dd49c5ce28/yoh_try_spikeinterfaces.ipynb

Full data is here: http://datasets.datalad.org/?dir=/labs/mvdm/MotivationalT-v2/R050/R050-2014-03-31_raw

**Comment by alejoe91** [comment]
Nice job! I'll look into it :) thanks for sharing the data and the code, makes my life easier eheheh

**Comment by alejoe91** [comment]
HI @yarikoptic 

Your notebook should run now after: 
- https://github.com/SpikeInterface/spiketoolkit/pull/343

And for neo extractors and locations:
- https://github.com/SpikeInterface/spikeextractors/pull/377
- https://github.com/SpikeInterface/spikeextractors/pull/376
- https://github.com/SpikeInterface/spikeextractors/pull/375

Now you're ready to spike sort the hell out of it! :)

PS. what kind of data is it? The output of klusta looks really bad!

**Comment by yarikoptic** [comment]
woohoo! Thank you @alejoe91 -- I will check it out later.

I believe it was some small test recording, also as you saw I had done no parameters selection or preprocessing, so bad results might be not surprising.  I will leave to @mvdm , who collected and generously shared the data, to comment more on the nature of data ;)  I guess things should improve when we get to real recordings of interest.  One of the goals will also be to compare to manually curated sorting and thus get closer to addressing https://github.com/spikodrome/metasort/issues/1 and possibly via https://github.com/spikodrome/metasort/issues/2 (i.e. AgreementSortingExtractor) ;)

**Comment by yarikoptic** [comment]
I would love to see release(s) with those fixes, but let me first test drive things more -- I bet my trouble-magnet will attract more issues ;)

**Comment by alejoe91** [comment]
> woohoo! Thank you @alejoe91 -- I will check it out later.
> 
> I believe it was some small test recording, also as you saw I had done no parameters selection or preprocessing, so bad results might be not surprising. I will leave to @mvdm , who collected and generously shared the data, to comment more on the nature of data ;) I guess things should improve when we get to real recordings of interest. One of the goals will also be to compare to manually curated sorting and thus get closer to addressing [spikodrome/metasort#1](https://github.com/spikodrome/metasort/issues/1) and possibly via [spikodrome/metasort#2](https://github.com/spikodrome/metasort/issues/2) (i.e. AgreementSortingExtractor) ;)

The sampling rate is 2 kHz! We are also looking into concensus based vs manual curation for the spikeinterface paper. Will let you know our preliminary results, but it looks promising! :) 

> I would love to see release(s) with those fixes, but let me first test drive things more -- I bet my 
> trouble-magnet will attract more issues ;)

I'll release new versions of the single packages tomorrow. We have made plenty of updates and bug fixes over the last couple of weeks.

**Comment by alejoe91** [comment]
Closing this for the moment @yarikoptic
