### ISSUE TITLE
CurationSortingExtractor.merge_unit() len(sort_indices) != np.concatenate(shared_features[i]).size

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#349]
Hi,

Their is an issue with the line 157, when it try to set feature for the new cluster.
If feature hasn't the same size as spike train, for exemple because you exctract only subpart of waveform in my case,  np.concatenate(shared_features[i])[sort_indices] make it crash as len(sort_indices) <  np.concatenate(shared_features[i]).size.
So their is probably a need for an "if len(sort_indices) == np.concatenate(shared_features[i]).size".

Otherwise, 
self.set_unit_spike_features works only if the feature has the same lenght as spiketrain. So in case 
len(sort_indices) != np.concatenate(shared_features[i]).size, you can either just ignore the feature or use an other method to add the feature.

Cheer,
Victor

**Comment by llobetv** [comment]
Their is no link with the previous comment,   but l.159 their is a 
raise ValueError(str(unit_ids) + " has one or more invalid unit ids")
That just make the merge function crash, the line should proably place at the beginning of the function with an if?

If you can I can make the PR with the 2 corrections (but only with the case where feature with invalid size are ignore)

**Comment by alejoe91** [comment]
Hi Victor,

Yes the CurationsortingExtractor hasn't been updated to to the new way we handle features (with idxs as well).

Would you try to give it a try to implement it the proper way? otherwise just ignoring it for now is fine for me

**Comment by llobetv** [comment]
I'll give a try, 
I remove the precedent comment, It was an error that I add wiht my modifications

**Comment by llobetv** [comment]
Solve with #350
