### ISSUE TITLE
Make sure exportToPhy working well

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#35]
Alessio, you said that you wanted to make sure our exporttoPhy is working well.

**Comment by alejoe91** [comment]
a4ea1f50bf8d1f85b0fc8f70ce1287c9182a91db

exportToPhy works, but there is still the issue on the template amplitude...

**Comment by alejoe91** [comment]
closing https://github.com/SpikeInterface/spiketoolkit/issues/12

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/commit/99df9cfa9d667b3ac20ea334e081deaad7e82953

finally fixed this. now works like a charm: st.postprocessing.exportToPhy(recording, sorting)
