### ISSUE TITLE
Module 'spiketoolkit.curation' has no attribute 'CurationSortingExtractor'

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#354]
I am trying to use the `CurationSortingExtractor`, and used the documentation: https://spikeinterface.readthedocs.io/en/latest/api.html#spiketoolkit.curation.CurationSortingExtractor

However, when using `st.curation.CurationSortingExtractor`, I can an error:

```
AttributeError: module 'spiketoolkit.curation' has no attribute 'CurationSortingExtractor'
```

Has the class been moved and the documentation is not yet up to date, or is it a bug?

**Comment by alejoe91** [comment]
Hi just re-added it: https://github.com/SpikeInterface/spiketoolkit/pull/353

Can you pull master again?

**Comment by Dradeliomecus** [comment]
It now works, thank you very much!
