### ISSUE TITLE
CurationSortingExctractor fail with export to phy

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#358]
Hi,

Just to mention that when you try to export_to_phy with  CurationSortingExctractor you get an error due to the parent_sorting argument in the __init__() function.
I just convert it to CacheSortingExtractor and it solve the issue, but their is maybe something cleaner to do.

@Dradeliomecus

Cheer,
Victor

**Comment by alejoe91** [comment]
Yep the dumping is not in place yet, but @colehurwitz is making it

**Comment by alejoe91** [comment]
The dumping is in place now :)
