### ISSUE TITLE
Some praticals issues with dead channels and similarity matrix

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#360]
Hi,

I encounter some praticals issues.

Fisrt link to dead channels. If I set a dead channels, it won't be exctract which is nice but when phy show data it will generated some painful behavior. The channel exctract instead of the dead one will change for every channel and in my case switch from right to left every channel (and make waveform representation move a lot every cluster, which make it paintful to use).

So I just decided to exctract all channel, but then similarity score just become really bad because it use proportion of shared exctracted channel for ponderation. It would be much better to use real distance ?

Cheers,
Victor

**Comment by alejoe91** [comment]
Hi Victor,

Sorry I didn't get exactly what's the problem here. Can you provide an example/a phy plot?
What painful behavior do you observe in phy? The problem with phy is that all templates must have the same shape, so an extra channel must be chosen (usually we pick the closest one to the largest peak).

**Comment by llobetv** [comment]
Hi Alejoe,

I know the pb, but then the channel will switch form right to left each time I switch channel (which happen often) wich is a bit anoying for intensive analysis (that will begin soon). 
ex:

![image](https://user-images.githubusercontent.com/22896067/81546229-5b94e800-937a-11ea-8777-0d5df454d84c.png)
![image](https://user-images.githubusercontent.com/22896067/81546264-664f7d00-937a-11ea-828b-9d0de2ce4a98.png)

So of course exctract all channel solve this issue but then similarity score totally failes because is based on n channel exctract. 
I can try an implementation to add an adjency_radius to scale similarity value.

Cheer,
Victor

**Comment by alejoe91** [comment]
@llobetv I have an idea. Instead of appending an extra channel, we can just append an empty template of nans. This should keep the. shape (so phy is happy) and we can easily disable it when computing similarity

**Comment by llobetv** [comment]
Hi,
The solution you propose would work well I think, and solve all the issue I mention before !

**Comment by alejoe91** [comment]
Hi @llobetv 

Do you have time to give it a try? I think that the main problem is when you ave multiple groups. Is it your case?

**Comment by llobetv** [comment]
I can give a try but not before Tuesday,

Yes it is, I actually have 4 groups of 16 channels.

**Comment by alejoe91** [comment]
ok! I'll leave it to you then. You will need to modify [this part ](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1543-L1561) and the [_compute__template_similarity](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1130)
