### ISSUE TITLE
export_to_phy_duration, exctract amplitude

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#366]
Hi !
I encounter some timing issue when I convert my sorting to phy... The duration is really high, more than 1 hour when analysis alone take 10mn.
I have the feeling that the longest step is amplitude calculation, and it seems that it is not parallelize. 

What is your feeling about that?
One option could be set exctract_amplitude optional (which I can easily implemented) or add parallelization (not so much experience in that unfortunatly)

Cheer,
Victor

**Comment by alejoe91** [comment]
Hi Victor,

We can definitely implement both. Maybe you can try to implement the `compute_amplitudes=False` in the `export_to_phy` and I'll take care of the parallelization of compute amplitudes.

Sounds good?

**Comment by llobetv** [comment]
Yep, sounds good for me, I'll handle that tomorrow !

**Comment by llobetv** [comment]
Done, I don't make deep test but it appear to solve my issue, I'll finish testing tomorrow.

But I got one question, why does exctract amp is so slow?
I check and get_snippets l.559 is the slower, and I try with several  snippet_len and even multiply it by 100 don't change it's time duration... Their is probably an issue their, isn't it?

I use cacheSortingExctractor.

**Comment by llobetv** [comment]
So I'm not sure if parallelization is needed

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/368

**Comment by alejoe91** [comment]
So the `get_snippets` is supposed to be the slowest because of the multpiple access and data retrieval from the same file. There is nothing we can actually do about it!
