### ISSUE TITLE
export_to_phy, template_ind sort

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#374]
Hi guys, 
It has been a while :)

I have a small issue which is link to template_ind when max_channels_per_template == recording.get_num_channels(), or when I use grouping_property (Then all chan are exctracted and subpart is took based on group label).

In that case templates are extracted in the order of the ch index and not sorted by their amplitude. 

But phy seems to use first value of template_ind as channel_idx, which is 0 if I extract all channel and first group channel if I use  grouping_property. This make the analysis a bit more complicated as units are now sort on their ch_id and not their best ch index.

I can add some lines to reorder templates and templates_ind based on their amplitude, if you are agree?

Cheer,
Victor

**Comment by alejoe91** [comment]
Hi Victor,

Sure I think it's fine to sort the templates and template_ind based on descending amplitude. Note that also the locations will need to be sorted and maybe other stuff too (like pca_scores channels - feature_ind). So it's not so trivial :)

Can you give it a try? We can discuss on the PR

Cheers
Alessio

**Comment by llobetv** [comment]
#375
