### ISSUE TITLE
Error when removing bad channels from ephys recordings

### ISSUE THREAD

**Issue by mdandola** [SpikeInterface/spiketoolkit#383]
Hi,

 am processing a 32 channels open-ephys binary recording, and when I try to remove bad channels I get this error:

> _`File "/export/opt/anaconda2/envs/spikeinterface/lib/python3.7/site-packages/spiketoolkit/preprocessing/common_reference.py", line 61, in get_traces
> 
>     return traces[channel_ids].astype(self._dtype)
> 
> IndexError: index 29 is out of bounds for axis 0 with size 29`_ 

Preprocessing is ran using the following code lines:

> outRecordingBadChannels    = st.preprocessing.remove_bad_channels(InRecording,
>                                                                        bad_channel_ids = preprocessingParams['bad_channel_ids'])
> 
>    outRecordingBandPassFilter = st.preprocessing.bandpass_filter(outRecordingBadChannels,
>                                                                    freq_min = preprocessingParams['freq_min'],
>                                                                    freq_max = preprocessingParams['freq_max'])
> 
>  outRecordingCommonReference = st.preprocessing.common_reference(outRecordingBandPassFilter,
>                                                                      reference = preprocessingParams['reference'])
> 

And the parameters file (.json) looks like this:

> {"n_channels":32,
>  "frequency":30000,
>  "prb_file":"/export/data/....[].prb",
> 
>  "sorter_options":{
>                   "detect_threshold": 3,
>                   "filter": true,
>                   "freq_min": 300, 
>                   "freq_max": 6000
>                   },
> 
>  "preprocessing_options":{
>                  "bad_channel_ids": [12, 14, 15],
>                  "reference":"average"
>                 }
> }

thank you!
best 

Mattia

**Comment by alejoe91** [comment]
Hi @mdandola 

Thanks for the issue. I'll try to replicate it and see what's wrong. Are you using the master branch of spiketoolkit or the pip version? 

Cheers
Alessio

**Comment by mdandola** [comment]
Hi Alessio,
thanks for the quick reply. 
We use the pip version

Mattia

**Comment by alejoe91** [comment]
Can you try to check if the error is still there by installing spiketoolkit from the master branch?

You can just clone the repo, uninstall spiketoolkit, `pip install .` from inside the spiketoolkit folder

**Comment by alejoe91** [comment]
Hi @mdandola 

I can't reproduce the error with the latest master. We might have fixed it already :) 
I also tried with an open ephys dataset byt it works fine on my side. Let me know if using the master brnch fixes the error on your side too

**Comment by mdandola** [comment]
Hi Alessio,

unfortunately I can't try it immediately: this is an installation on a department-wide computation server, and the person in charge with root credentials will be away for two weeks. I will try to verify on a local installation, but I will let you know whether the master branch installation solves the original problem in a couple of weeks! 
thanks for your help

Mattia

**Comment by alejoe91** [comment]
Hi @mdandola 

Have you tried the latest release?

**Comment by mdandola** [comment]
Hi Alessio,

yes, using the latest release solved the problem!
thanks for the help

Mattia
