### ISSUE TITLE
resample then spike sort error

### ISSUE THREAD

**Issue by jthermiz** [SpikeInterface/spiketoolkit#385]
Prior to running spike sorter (mountainsort 4), I resample the data. When I do this I get an error from the spike sorter. There probably aren't many people resampling their data prior to spike sorting, but nonetheless wanted to raise the issue, since an unexpected error is thrown. In the attached example, I'm just resampling at the same rate of the original signal, but even resampling at other frequencies (eg half original), generates the same error: 

_"ValueError: The length of the input vector x must be greater than padlen, which is 27."_

**Code that reproduces the error:**
[resample_sort_error_py.txt](https://github.com/SpikeInterface/spiketoolkit/files/5111084/resample_sort_error_py.txt)

**Console output:**
[ipython_console_result.txt](https://github.com/SpikeInterface/spiketoolkit/files/5111086/ipython_console_result.txt)

I'm using version '0.9.9' of spikeinterface, '0.6.3' of spikeinterface.toolkit and '0.3.3' of spikeinterface.sorters

**Comment by alejoe91** [comment]
HI @jthermiz 

I could not reproduce the error using the latest releases of spikeextractors and spiketoolkit.

Can you try `pip install --upgrade spikextractors spiketoolkit`?

Cheers
Alessio

**Comment by jthermiz** [comment]
Hi @alejoe91 

It looks like the update resolved the issue on my end. Thanks!

-John
