### ISSUE TITLE
Alternative method for artifact rejection

### ISSUE THREAD

**Issue by lfrank** [SpikeInterface/spiketoolkit#386]
Would it be possible for someone to add a preprocessing method that zeros out a user specified set of samples? The idea here is that a user might want to be able to write their own artifact rejection code (this something we need to do) and then use the output of that code (a set of frames to be zeroed) to get rid of the artifacts.

**Comment by alejoe91** [comment]
HI Loren,

It would be possible for sure, but maybe a better approach would be to have a `CustomPreprocessor` that allows the user to define their own `get_traces` function? That would require some thinking, but it'll be more flexible.

What do you think?

**Comment by lfrank** [comment]
Hi Alessio. Thanks for the quick response. In this case I actually think the ability to just zero out samples would be useful even if there is eventually a CustomPreprocessor. This would be for less sophisticated users who just want to delete artifacts but for whom the current functions don’t quite work. For us, for example, we might have an artifact from a physical event (e.g. the animal banging it’s head on the side of the track) that we could detect by looking at the amplitude and variance of the signal, but right now there doesn’t seem to be an easy way for us to get rid of that event.

**Comment by alejoe91** [comment]
Hi Loren, I see. So maybe we can make a `zero_out` preprocessor that takes in a recordingextractor and an array of frame_idxs/mask to zero out. Would that be ok? :)

**Comment by lfrank** [comment]
That would be ideal if you have time to do it...

thanks much

**Comment by alejoe91** [comment]
I'll try to get it done next week!
