### ISSUE TITLE
Avoid writing dat file for phy when Cache or BinDat extractors

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spiketoolkit#387]
Hi guys,

I just check new commit and one of them will generate some issue for me: #1be66496a735a37198ad81a0a6eda6feb5dd062d

The problem is that I use binary file, but I would like to keep the recording.dat for several reasons. Fist when I got dead channel, I appreciate to get the recording.dat without this channel so I can use channel_map from phy/ directory. Secondly, after I analysed my data I moved them so path to my binary file won't work anymore.

Would it be possible to just have an option write_recoding or stuff like that?

Cheer,

Victor

**Comment by alejoe91** [comment]
Hi @llobetv 

Sure, maybe we can have an argument `copy_binary=False` by default. If `copy_binary=True`, then the file is copied in the phy folder. Do you have time to look into that?

Cheers
Alessio

**Comment by llobetv** [comment]
Yes I take care of it !

**Comment by llobetv** [comment]
I got several questions

Fisrt if I add channel_map to recording object then it will copy recording.dat anyway (SubRecordingExtractor)

Second if I use CacheRecoding then recording.dat data is not copy but path to the raw data is /tmp directory. I don't really understand why you don't want to copy recording.dat in that case, where tmp/ directory will be clean after reboot.


Wouldn't it be better to use copy_binary for all exctraction and if copy_binary is False to use the path from recordingExtractor for Cache and Bindat.
For other if recording object is not present phy will work and just show templates which could be good for some people.

**Comment by alejoe91** [comment]
> I got several questions
> 
> Fisrt if I add channel_map to recording object then it will copy recording.dat anyway (SubRecordingExtractor) when you probably don't want to.
> 

You are right, we should check if the underlying base object is binary in the first place.

> Second if I use CacheRecoding then recording.dat data is not copy but path to the raw data is in /tmp directory. I don't really understand why you don't want to copy recording.dat in that case, where tmp/ directory will be clean after reboot.
> 

When you use the caching method, you can point to another save_path using: `rec_cache = se.CacheRecordingExtractor(rec, save_path='my-path.dat')`. Alternatively, if the `save_path` is not given, you can later use the `move_to('my-path.dat')` function to move the binary file where you want.

> Wouldn't it be better to use copy_binary for all exctraction and if copy_binary is False to use the path from recordingExtractor for Cache and Bindat.
> For other if recording object is not present phy will work and just show templates which could be good for some people.

Sorry I don't understand what you mean with this. Could you try to explain it better?

**Comment by llobetv** [comment]
Sorry for the delay,
I just say that copy_binary could be used every time as binary data is not needed to open with phy. 
And in the case copy_binary is False then used link to rawData if available.

**Comment by llobetv** [comment]
Maybe I still weren't clear, the idea was to use copy_binary params to set creation of recording.dat optional, either when recording object don"t come from raw data.

And in case copy_binary is False and that a path to raw data exist, use it as you do today. Otherwise just let the relative path to the raw file empty.

**Comment by alejoe91** [comment]
Hi @llobetv 

Does phy work without a path to the binary file?

**Comment by llobetv** [comment]
Yep it does

**Comment by alejoe91** [comment]
ok then it's a good idea. By default, though, copy_binary should be True in my opinion

**Comment by llobetv** [comment]
It seems logical yes, I'll do that! :)
