### ISSUE TITLE
Global demuxed CAR (preprocessing step for neuropixels)

### ISSUE THREAD

**Issue by MarineChap** [SpikeInterface/spiketoolkit#390]
Dear, 
Thank you for this amazing tool. 

We are using it with neuropixels. I see that we already have the possibility to preprocess the data with a common average referencing filter, but for neuropixels it needs to be done by group of channels of similar sample time offsets from each ADC group (because of the time division multiplexing). 
Do you know if we can use the group option ([here](https://github.com/SpikeInterface/spiketoolkit/blob/020655ec4e7e1d242ecf300a3b6fbc45c8f5b507/spiketoolkit/preprocessing/common_reference.py#L12)) to do the global demuxed CAR (like in CatGT for example) ? Do you know if it has been already used like this before ? 

Thank you for your help.

**Comment by alejoe91** [comment]
Hi @MarineChap :)

Yes you can definitely use groups. You would need to extract channel groups belonging ti the same time offsets outside, and then pass the groups as a list of lists (each list containing the channel ids of different groups).
That applies CAR (or CMR) to the different groups separately, which I believe is what you need!

If the demux info is available from spiekGLX files, then it'd probably be a good idea to load them as channel properties directly from the `SpikeGLXRecordingExtractor`. Do you know how to retrieve that information from the file?

**Comment by MarineChap** [comment]
Hi @alejoe91 
Thank you for your response. Super cool. 
I am sure the information is somewhere, either as a fix format (like always 1-12-24..etc. go togethers) or wrote in the metadata, but for the moment I am not sure. I can keep you posted when I found the answer.

**Comment by MarineChap** [comment]
hi @alejoe91  

I don't know if you are still interested by the demuxed CAR but Allen Institute did an open-source C++ version of it.

https://github.com/AllenInstitute/ecephys_spike_sorting/blob/master/ecephys_spike_sorting/modules/median_subtraction/SpikeBandMedianSubtraction/Source/Main.cpp

I did not take a deep look in the code yet but from what I can see the demuxed group are in fact guess from the offset section in the metadata. 
I definitely don't have the time right now to really look at it but if you are interested I can put on my TODO list for later.

Have a good day

**Comment by alejoe91** [comment]
HI @MarineChap 

Thanks for the update here! Me neither unfortunately, but we can look into it next month. Maybe @jsiegle can also chime in :)

**Comment by MarineChap** [comment]
Ah Ah It is the one who redirected me on this implementation ;)

**Comment by alejoe91** [comment]
Thanks @alejoe91 then :)

**Comment by MarineChap** [comment]
Hi @alejoe91 

After analyze by Hanna Den Bakker (Kloosterman Lab),  we would be in fact more interested by a local CAR instead of the demuxed CAR. Is it only a global car in the preprocessing step right ? 

In attached a short comparison of the different preprocessing methods and the result obtained.
[Documentation_CAR.pdf](https://github.com/SpikeInterface/spiketoolkit/files/6124703/Documentation_CAR.pdf)

If needed some dev, I have some free time in the two next weeks.

**Comment by alejoe91** [comment]
Interesting! Not yet in place, would you like to give it a try? :)

**Comment by samuelgarcia** [comment]
Hi.
The main problem will be te retrieve information on how channels are sampled togother or not.
This is hihly device dependant.

**Comment by MarineChap** [comment]
Hello, 
That was the question for the demuxed CAR but not for the local CAR, no ? 

By the way, implementation question, I was thinking : 
- put the local CAR in the common reference class with a reference keyword local 
- Add two parameters : radius and channel number -- As it is parameters really specific for the this implementation, where they should be defined next to group, ref_channels ... ect? Or there is a other/better way for that ? 

Thanks

**Comment by alejoe91** [comment]
Hi @MarineChap I agree with you, the local CAR is universal. 

As for your question, why do you need the channel number? Wouldn't each channel be re-referenced based on the radius? 

Also can I ask you a question on the document you  shared? What does your automated validation consist of?

Thanks!

**Comment by MarineChap** [comment]
Okay I need to find a better name for this channel number parameters. When doing the local CAR, it will be the average of N nearest number of channels outside of the radius. I was thinking to put as parameters; the radius and this N number of of channels. 

The automated validation is not much more what you already have. . Originally we wanted to just applied your spiketoolkit validation workflow but the researchers developing it had some troubles to apply it on kilosort 3, 2.5 and 2. So they switched on the ecephys code. So what they meant by automated validation is just the equivalent of the compute_metrics method in your spikemetrics repo. I am trying now to switch it on using the spiketoolkit instead. 
I know it is a lot of works but it would be really useful to have some notebooks ready to use with a whole validation pipeline for every sorters.

**Comment by alejoe91** [comment]
> Okay I need to find a better name for this channel number parameters. When doing the local CAR, it will be the average of N nearest number of channels outside of the radius. I was thinking to put as parameters; the radius and this N number of of channels.
> 
Got it! Maybe `num_local_channels` can be a good name and you could explain what the mechanism is in the do string :)

> The automated validation is not much more what you already have. . Originally we wanted to just applied your spiketoolkit validation workflow but the researchers developing it had some troubles to apply it on kilosort 3, 2.5 and 2. So they switched on the ecephys code. So what they meant by automated validation is just the equivalent of the compute_metrics method in your spikemetrics repo. I am trying now to switch it on using the spiketoolkit instead.
> I know it is a lot of works but it would be really useful to have some notebooks ready to use with a whole validation pipeline for every sorters.

What was the problem with the validation pipeline? Can I ask you what quality metrics and what thresholds you use? Did you have problems with the `st.curation.threshold` functions?

**Comment by MarineChap** [comment]
I am not clear on what the problem was exactly. You helped Kasia on it at some points. 
They were also the problems with reloading the data from phy when some channels has been removed. I think we fixed together this one. Don't worry I will open issues if needed.

**Comment by MarineChap** [comment]
Hello, 
Do you have something in your API to directly find out the nearest electrodes from a channel id ? Thanks

**Comment by alejoe91** [comment]
Hi @MarineChap 

We have code here and there (e.g. [here](https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/postprocessing/postprocessing_tools.py#L1974-L1977)), but not in a centralized location. Can you make a `utilis.py` in the base `spiketoolkit` folder and make a:

```
def get_closest_channels(recording, channel_ids, num_channels):
```

function? `channel_ids` can be a list, so it can return the a list of closest channels to each of the indicated channels. LEt me know if you need help with this.

**Comment by MarineChap** [comment]
I am hesitating if we need to have a group option for this method. 
If we are filtering only in a group, do we need to take the closest channels only in this group or we are taking the closest channel and next step, we are removing the channels not present in it ?

**Comment by alejoe91** [comment]
> I am hesitating if we need to have a group option for this method.
> If we are filtering only in a group, do we need to take the closest channels only in this group or we are taking the closest channel and next step, we are removing the channels not present in it ?

The filter will be applied on all channels unless a `SubRecordingExtractor` is explicitly created using a subset of channels. So I think it's safe :)

**Comment by MarineChap** [comment]
@alejoe91  Sorry to bother you but... when are you planning to release this package following my PR? We are waiting for an official release to install it in our cluster. 
Thanks 
Have a good day

**Comment by alejoe91** [comment]
@MarineChap sorry I forgot!!! 

Pushed a new version now (0.7.5), should be up on PyPi in a few minutes.

**Comment by MarineChap** [comment]
Super. Thanks !
