### ISSUE TITLE
Set sampling rate

### ISSUE THREAD

**Issue by jthermiz** [SpikeInterface/spiketoolkit#393]
Set sampling rate method does not seem to work for an inherited object (eg. object generated from st.curation). Please see below code, which illustrates the problem on a toy example.

`import spikeextractors as se
import spiketoolkit as st

_, sorting = se.example_datasets.toy_example()
fs = sorting.get_sampling_frequency()
sorting_curated = st.curation.threshold_isi_violations(sorting, threshold=0, 
                                                       threshold_sign='greater', duration_in_frames=10*fs)

print(sorting_curated.get_sampling_frequency())
sorting_curated.set_sampling_frequency(fs/2) # set sampling frequency method doesn't work for inherited 'validation' object
print(sorting_curated.get_sampling_frequency()) #should return 15000, but returns 30000

#%% works for parent object

print(sorting.get_sampling_frequency())
sorting.set_sampling_frequency(fs/2)
print(sorting.get_sampling_frequency())`

**Comment by jthermiz** [comment]
I think I have a better handle on this issue. set sampling rate method is fine. It's get sampling rate method that is the trouble maker. Here's a potential fix:

remove get sampling rate method (let it inherit it's parent method automatically)
initialize sampling rate in constructor: `self._sampling_frequency = parent_sorting.get_sampling_frequency()`

**Comment by alejoe91** [comment]
Hi @jthermiz 

Thanks for bringing this up! I think that your suggestion would work 👍  Can you make a small PR?

Could I ask you why you need to change the sampling frequency? Note that just setting the `sampling_frequency` would not really change the effective sampling rate, but it would actually just shrink or increase the duration. If you really need to downsample the spike trains, we would need to add something that takes care of downsampling at the frames level (snap to the closest downsampled frame).

**Comment by jthermiz** [comment]
Hi @alejoe91 

I just made the PR. I hope I did everything right -- this was my first PR!

I'd like to compare 2 sorting generated from recordings from different sample frequencies. Spikecomparison tools only allow comparisons between sortings with the same sample rate, so I have make it seem like the sorting was obtained at a different rate by changing the sample frequency and multiplying updating the event times accordingly as you mention.

That being said, I found another way to do this. I get spike times and simply creating a new NumpySortingExtractor object rather than messing around with CurationSortingExtractor object generated by spiketoolkit. This gave approach gave me less headaches since I don't know how to update event times in the CurationSortingExtractor object

**Comment by alejoe91** [comment]
Hi @jthermiz 

Thanks, the PR looks good!

Yes as you suggest, if your goal is to compare spike sorting output at different sampling rates, it is much better to create a new NumpySortingExtractor and taking care of resampling outside. The `CurationSortingExtractor` is more complicated as its intended to be compatible to any kind of curation.

Let us know if you have other issues! Closing this for now :)
