### ISSUE TITLE
TODO: document how to install spyking circus and ironclust

### ISSUE THREAD

**Issue by magland** [SpikeInterface/spiketoolkit#4]
in order to make the spike sorter wrappers work

**Comment by alejoe91** [comment]
spyking_circus is done

**Comment by jamesjun** [comment]
Here is the ironclust installation instruction:

0. Prerequisites: Matlab toolbox (parallel processing toolbox and CUDA is optional)
1. git clone https://github.com/jamesjun/ironclust
2. set "IRONCLUST_SRC='~/src/ironclust" in .bashrc (alternatively pass ironclust path when calling ironclust sort function)

**Comment by jamesjun** [comment]
@alejoe91, Where can I find documentation for the spyking-circus within spiketoolkit? I have encountered the following error while running the example ipynb:

```
| Step "merging" failed for reason Command '['mpirun', '-x', 'LD_LIBRARY_PATH', '-x', 'PATH', '-np', '4', 'spyking-circus-subtask', 'merging', '/home/jamesjun/src/spiketoolkit/examples/tmp/spyking_circus/recording.npy', '4', '0', 'False', 'None']' returned non-zero exit status 1.!
```

**Comment by alejoe91** [comment]
All installation info are there.
