### ISSUE TITLE
Epoch information disappears from RecordingExtractor after preprocessing steps

### ISSUE THREAD

**Issue by joramvanrheede** [SpikeInterface/spiketoolkit#406]
Hi spikeinterface team,

I'm running into an issue of disappearing epoch information after running preprocessing steps.

I have built a recordingextractor out of a number of subrecordings using the MultiRecordingTimeExtractor method. I have added epoch labels myself, and the MultiRecordingTimeExtractor helpfully keeps track of the start_frame and end_frame of each epoch.

However, when I run any preprocessing steps on the resulting RecordingExtractor object, epoch information is lost, and I have to use a workaround to put the epoch information back in.

Example:
```
block_recording     = se.MultiRecordingTimeExtractor(recording_list, epoch_names = block_stages)
block_recording.get_epoch_names()
```
output:
['epoch name 1',
 'epoch name 2'
 'etc...']
```
block_recording_CAR = st.preprocessing.common_reference(block_recording, reference='median')
block_recording_CAR.get_epoch_names()
```
output:
[ ]

It is the same when running st.preprocessing.remove_bad_channels().

I can use a workaround to put the epoch information back in using add_epoch(), but I was wondering if this is intentional behaviour or needs fixing?

**Comment by alejoe91** [comment]
Hi @joramvanrheede 

This is definitely unintentional and we need to fix it! Thank you for spotting it. 

@colehurwitz do you have time to look into this?

**Comment by joramvanrheede** [comment]
Thanks for the quick reply! As I said, it's not a critical issue as it is possible to add the epochs back in, but I thought I would let you know. 

Also, I didn't want to stray off the point in the main issue but thank you for all your work on this toolkit - I'm only just beginning to use it but already seeing that it's going to make everything more reproducible and save a lot of work!

**Comment by alejoe91** [comment]
> Thanks for the quick reply! As I said, it's not a critical issue as it is possible to add the epochs back in, but I thought I would let you know.
> 
> Also, I didn't want to stray off the point in the main issue but thank you for all your work on this toolkit - I'm only just beginning to use it but already seeing that it's going to make everything more reproducible and save a lot of work!

Glad to hear that! :)

**Comment by colehurwitz** [comment]
I should be able to look into this!

**Comment by alejoe91** [comment]
@joramvanrheede should be fixed using the master branches of spikeextractors and spiketoolkit

**Comment by joramvanrheede** [comment]
Fantastic, thank you!
