### ISSUE TITLE
preprocessing.whiten and raw mda (just on windows)

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spiketoolkit#409]
Hi guys, I'm having a strange error, I'm loading a mda recording:

```
recording = se.MdaRecordingExtractor(folder_path='E:\\test\\example')
filtered = st.preprocessing.bandpass_filter(recording, freq_min=300, freq_max=6000)
rw = st.preprocessing.whiten(filtered )
```

That work fine as usual, but when I tried to whiten the unfiltered recording:

`rw = st.preprocessing.whiten(recording)
`

I got

`  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spikeextractors\extractors\mdaextractors\mdaextractors.py", line 55, in get_traces
    recordings = recordings[channel_ids, :]
TypeError: 'NoneType' object is not subscriptable`

**Comment by alejoe91** [comment]
Hi @ferchaure! 

Mmm interesting...strange that it failed when instantiating the object, and not when retrieving traces. I'll look into it in the next days!

**Comment by ferchaure** [comment]
Let me know if I can help you with it. I got a warning before that error:

`E:\programs\Anaconda3\envs\bcm\lib\site-packages\spikeextractors\extractors\mdaextractors\mdaio.py:127: RuntimeWarning: overflow encountered in long_scalars
  offset = self._header.header_size + self._header.num_bytes_per_entry * i
[Errno 22] Invalid argument`

**Comment by alejoe91** [comment]
Can you paste the entire error?

**Comment by ferchaure** [comment]
E:\programs\Anaconda3\envs\bcm\lib\site-packages\spikeextractors\extractors\mdaextractors\mdaio.py:127: RuntimeWarning: overflow encountered in long_scalars
  offset = self._header.header_size + self._header.num_bytes_per_entry * i
[Errno 22] Invalid argument
Problem reading chunk from file: F:\sl_data_test\shared\ydg.mda
Traceback (most recent call last):
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-51-e7b68ffa9ea9>", line 1, in <module>
    rw = st.preprocessing.whiten(recording)
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spiketoolkit\preprocessing\whiten.py", line 76, in whiten
    seed=seed
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spiketoolkit\preprocessing\whiten.py", line 13, in __init__
    self._whitening_matrix = self._compute_whitening_matrix(seed=seed)
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spiketoolkit\preprocessing\whiten.py", line 31, in _compute_whitening_matrix
    data = self._get_random_data_for_whitening(seed=seed)
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spiketoolkit\preprocessing\whiten.py", line 26, in _get_random_data_for_whitening
    end_frame=ff + chunk_size)
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spikeextractors\extraction_tools.py", line 774, in corrected_args
    get_traces_correct_arg = func(args[0], **kwargs)
  File "E:\programs\Anaconda3\envs\bcm\lib\site-packages\spikeextractors\extractors\mdaextractors\mdaextractors.py", line 55, in get_traces
    recordings = recordings[channel_ids, :]
TypeError: 'NoneType' object is not subscriptable

**Comment by alejoe91** [comment]
Hi @ferchaure 

I was not able to reproduce the error on mac..maybe it's related to the specific file. Could you send me the file so I can double check?

Does this happen with other mda files?

Cheers
Alessio

**Comment by ferchaure** [comment]
Hi alessio,

I debugged a bit the error (I'm starting to love pycharm) an the issue starts in mdaio.py particulaty on the method `_read_chunk_1d` in the first line it define `offset = self._header.header_size + self._header.num_bytes_per_entry * i`  when it works the python variables are Int64 ( python default int) and everything is fine, but if `i` is a int32 then the operation output is casted to int32 and that gets an overflow and the function return None. 

I tracked the root of the datatype differences up to get_traces() when the frames are in int32, a filtered recording eventually cast the inputs to int (I didn't find where) before call the get_traces on mdaextractors; but on the raw recording the casting is not done and, if the file is big enough, eventually generates the overflow. 

I haven't done the math but, with at least a mda recording type float64, with 68564199 frames and 8 channels the overflow issue appears.

The simplification of the issue is (for a file big enough):

`recording.get_traces([0],(39012478))
` works
`recording.get_traces([0],np.int32(39012478))
` it doesn't work


I know, is really a spikeextractor issue.

**Comment by alejoe91** [comment]
HI @ferchaure thanks for debugging this!

I think that the easiest solution would be to cast start frame and end frame to `int16` in the [`cast_start_end_frame`](https://github.com/SpikeInterface/spikeextractors/blob/774d30ca8e98822fa489fca883cc3767ff798460/spikeextractors/extraction_tools.py#L876) function which is used by the [`check_get_traces_args`](https://github.com/SpikeInterface/spikeextractors/blob/774d30ca8e98822fa489fca883cc3767ff798460/spikeextractors/extraction_tools.py#L809) (that decorates all `get_traces` functions)

I'll make a PR in a few minutes :)

**Comment by alejoe91** [comment]
@ferchaure can you test this PR? https://github.com/SpikeInterface/spikeextractors/pull/502/files#diff-acedec256b397104824caa2c5dee2ea9f0bb08dc0b7541bb2c554dbb48fc9445R889

**Comment by ferchaure** [comment]
It works! :+1:
