### ISSUE TITLE
How to deal with several environement.

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#41]
An issue we will face very soon is the following : some sorter are not compatible in the same environement.
For instance, recently phy was still using the QT4 package.
Tridesclous is based on PyQt5 for the GUI. The actual conda system (but not pip) prevent from installing both Qt4 and Qt5.
So this means that tridesclous and phy can't live in the same environement.
It is not a major problem in general. On my machine I create an env for each projet I want to test.

But here in spiketoolkit, all sorters are suposed to be installed in the same env because they have be lauch and compare in the same interpreter.

This could be fix with the class apraoch by uncoupling the "run" of the sorter and the instanciation of the "sorting" object like this.
```
    sorting = se.TridesclousSortingExtractor(tdc_dirname)
    return sorting
```
classes could add some functionalities to "run" the sorter ouside the environement with another python interpreter, make the result persistent (which is always the case) and in second step the "SortingExtractor" object could be instanciate in the main env.

What do you think ?

**Comment by colehurwitz31** [comment]
That seems like it could be a nice solution! I think moving towards a class based sorting system with features like this would be a good step in the right direction. 

We are also looking into wrapping spike sorting algorithms in singularity containers which could solve some of the dependency issues.

**Comment by samuelgarcia** [comment]
containers system sounds good but spiketoolkit would be linux only, no ?

**Comment by colehurwitz31** [comment]
That’s true that singularity would only be a solution for Linux based systems. Our plan is to make a separate repo for singularity wrapped sorters. 

For spiketoolkit, you are right that we need another solution. I think that decoupling instantiation and running of spike sorters would be a nice solution as you mentioned.

Would the next step be looking into making each sorter an object then?

**Comment by samuelgarcia** [comment]
As soon as tridesclous is finish I can take in charge of moving towards classes.

**Comment by colehurwitz31** [comment]
Great! Thanks so much for all the good feedback and support. :) I can also help move to classes if you would like to discuss the process this week

**Comment by alejoe91** [comment]
@samuelgarcia the dev branch of `phy` uses PyQt5!

I was actually able to install all sorters in the same environment :)

But I support in general the use of classes for spike sorters

**Comment by samuelgarcia** [comment]
Yes I kown this but dev branch is not as easy as the pip install phy.

**Comment by samuelgarcia** [comment]
I think we can close this for the moment.
Container will not be implemented soon here.
