### ISSUE TITLE
`st.postprocessing.get_unit_waveforms` returns waveforms for only 300 spikes

### ISSUE THREAD

**Issue by wuffi** [SpikeInterface/spiketoolkit#414]
The `st.postprocessing.get_unit_waveforms()` method would always give me a matrix with shape `(300, num_channels, 120)` irrespective of parameters.

Minimal example:
```
import spikeextractors as se
import spiketoolkit as st

recording = se.PhyRecordingExtractor('/path/to/KiloSort_input')
sorting = se.PhySortingExtractor('/path/to/KiloSort_output')
# Get waveforms for unit 1 on channel 1
wf = st.postprocessing.get_unit_waveforms(recording,sorting,1,1,None)
# wf[0].shape is always (300, num_channels, 120) irrespective of parameters
```
Plotting the waveforms indicates they are correct, but just too few.

I'm using the master branch on Windows 10.

**Comment by alejoe91** [comment]
Hi @wuffi 

You have to use the `max_spikes_per_unit=None` to get all waveforms. Note that it is a kwarg so you need to use the keyword! 

If you have compute waveforms already and you want to recompute them, you also need to use the `recompute_info=True` argument.

**Comment by wuffi** [comment]
Thanks @alejoe91, it's working.
The decisive argument was `recompute_info=True` - because also the `channel_ids=1` positional argument didn't have any effect.
Thinking about it not it's obvious, but I'm wondering whether it would make sense to make `recompute_info=True` for users like me. It would come at the cost of performance.

**Comment by mhhennig** [comment]
@alejoe91, shall we make a default `recompute_info=False`. I ran into this once, and I should know :) This can be very confusing for users who do not know about tihos option.

**Comment by alejoe91** [comment]
@mhhennig I don't think so..it's used extensively in the code to return properties and features already computed. We should improve the docs about this
