### ISSUE TITLE
Provide user with list of available quality metrics for use in compute_quality_metrics

### ISSUE THREAD

**Issue by lfrank** [SpikeInterface/spiketoolkit#415]
It would be very helpful to have a function that returns a list of the strings corresponding to the available quality metrics so that a user could know how to call compute_quality_metrics() without having to look in the code itself.

A broader suggestion would be to create a dictionary of references to the quality metric functions. In that case the keys of that dictionary would correspond to the strings that the user would need to use, and that would ensure that as quality metrics are added, there is a consistent way to register them and keep track of them.

**Comment by alejoe91** [comment]
Hi Loren!

We have it :) `st.validation.get_quality_metrics_list()`

**Comment by lfrank** [comment]
Great; thanks. Just FYI, that doesn’t seem to be in the documentation:
