### ISSUE TITLE
get_unit_waveforms crashes with n_jobs > 1

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#421]
Hi,

I'm using `spikeinterface` to do multiple things, one of which is to extract the waveforms.
I have a lot of waveforms and a lot of CPU cores, and as such, I would like to take advantage of the `n_jobs` parameter, except when it's anything but `1`, it returns an error:

```
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    waveforms, spikes, channels = spiketoolkit.postprocessing.get_unit_waveforms(recording, sorting, return_idxs=True, n_jobs=10, max_channels_per_waveforms=1, max_spikes_per_unit=int(10*recording_length), memmap=True, dtype=np.int16)
  File "/users/nsr/wyngaard/.local/lib/python3.8/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 277, in get_unit_waveforms
    unit_waveforms, = Parallel(n_jobs=n_jobs, backend=joblib_backend)(
ValueError: too many values to unpack (expected 1)
```

I've tried with `n_jobs=2` also, but the same error occurs.
So for the time being, I'm using `n_jobs=1`, but it's pretty slow (~5 minutes).

I'm using the latest version of `spike_interface` (version 0.7.1).

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

We are in the process of updating all packages. The efficiency issue in spiketoolkit has been solved.
In the meanwhile you can try to install all SI packages from the github master.

Cheers
Alessio

**Comment by Dradeliomecus** [comment]
Ah yes indeed, installing from github solved the problem, thanks!

For several low frequency units (~1 Hz), it's somehow slower as `n_jobs` increases (2.8s with 1, 4.4s with 2 and 7.8s with 10).
However for high frequency units (~80 Hz), it's faster (526s with 1 and 319s with 10).

Thank you!

**Comment by alejoe91** [comment]
Yes indeed. The strategy now favors high firing rates. The idea is to load the recording in chunks and extract all waveforms from the chunks. Of course if you only have a few spikes, it becomes less efficient. But in general, let's say for a normal number of spikes, it is now way faster :)

**Comment by alejoe91** [comment]
Note that the waveforms extraction is much faster even using one job only. There is some overhead in starting multiple jobs, so I recommend doing that if you have long recordings/many channels
