### ISSUE TITLE
compute_unit_pca_scores setting unit_ids

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spiketoolkit#424]
Hi, this is probably a little bug. I getting this error trying to compute pca scores:

```
  File "/home/fer/anaconda3/envs/test/lib/python3.7/site-packages/spiketoolkit/postprocessing/postprocessing_tools.py", line 1108, in compute_unit_pca_scores
    wf = waveforms[idx_waveform]
IndexError: list index out of range
```
But only if I set unit_ids.  Probably because waveforms in that code is suppose to be a list with the same length of sorting.get_unit_ids() and it isn't the case if unit_ids is passed as an argument.

**Comment by alejoe91** [comment]
Ah! Nice catch @ferchaure :)

Would you have time to make a patch for this? A bit busy these coming days...let me know!

**Comment by alejoe91** [comment]
@ferchaure can you test that this PR fixes the problem? https://github.com/SpikeInterface/spiketoolkit/pull/427

**Comment by ferchaure** [comment]
Thanks, It works now.
