### ISSUE TITLE
BlankSaturationRecording for memmaps

### ISSUE THREAD

**Issue by ferchaure** [SpikeInterface/spiketoolkit#428]
Hi guys, I notice that inside BlankSaturationRecording the values obtained by self._recording.get_traces() are edited. And that coulb be a memmap. I try using it with a recording that I loaded using load_extractor_from_pickle() and I got:

>    traces[traces >= self._threshold] = self._median
> ValueError: assignment destination is read-only

I guess that a solution could be: check the type of traces and if it is a memmap and it will be edited then a copy on ram should be made.

**Comment by alejoe91** [comment]
Hi @ferchaure 

Another possibility would be to just convert traces to array in all cases (in memory) and modify that. Could you make a PR? In any case the initial copy should be out of scope after the return, so the RAM should get released

**Comment by ferchaure** [comment]
okok I will do the PR, but make a copy could be sub optimal if the trace is note edited.

**Comment by alejoe91** [comment]
True! I agree it's better to check if it's a memmap object
