### ISSUE TITLE
Normalisation messes up spiketimes

### ISSUE THREAD

**Issue by marvinseifert** [SpikeInterface/spiketoolkit#432]
Hi,
I am trying to use spiketoolkit to normalise the recording before doing the spikesorting but something goes wrong <br />
this is what I am doing: <br />

```python
RX = se.BiocamRecordingExtractor(raw_file, verbose=True)
RX_normalized = st.preprocessing.normalize_by_quantile(RX)
```
I use herdingspikes for the sorting. <br/>
```python
Sorter = ss.sorter_dict['herdingspikes']

hs = Sorter(recording=RX_normalized, output_folder='E:\\Out')
p = hs.default_params()
p
p['clustering_bandwidth'] = 5.0
p['detect_threshold'] = 2
p['spk_evaluation_time'] = 1
p['filter'] = False
p['pre_scale'] = False
hs.set_params(**p)
```

The strange thing is: herdingspikes seems to detect the right number of spikes but assigns wrong timestamps to them: <br />
![image](https://user-images.githubusercontent.com/40001645/102481163-417e5f00-4059-11eb-914b-d7df257504f0.png)

Here I plotted the trace and the corresponding detected spikes as dots under the trace. As you can see, hardly any spikes are found in the first half of the recording despite the signal being stronger there. Is there something I do wrong or is this a bug? I am not 100% sure if I set the threshold correctly, as the trace is normalized. 

If I dont do the normalisation before the sorting but set p['pre_scale'] = True it works just fine: 
![image](https://user-images.githubusercontent.com/40001645/102482462-1f85dc00-405b-11eb-94ad-79ce5842f4bc.png)

Thanks!

**Comment by alejoe91** [comment]
Hi @marvinseifert 

Forwarding this to @mhhennig and @colehurwitz, as they are the developers of herding spikes

**Comment by colehurwitz** [comment]
Thanks for linking @alejoe91 ! I will look into this with @mhhennig

**Comment by mhhennig** [comment]
Let me check...

**Comment by mhhennig** [comment]
I think the big artifact here causes a problem. First of all, pre_scale=True just uses `normalize_by_quantile`, but it scales to 20. This is something we should finally fix: the HS2 detection uses integers (for speed), and the `normalize_by_quantile` by default scales it to 1 (meaning the specified quantile has unit range). This will throw the detection off. In addition, the bandpass (`filter=True`) will only make the artifact worse. Have you tried the following?
```
p['filter'] = False
p['pre_scale'] = True
```
alternatively both = False and no normalisation at all (HS2 was made for Biocam anyway).
I think either could work. You can also try the `blank_saturation` prepocessing module, this should blank out your big artifact.
We need to write some code so HS2 can automatically re-scale the data, easy enough...maybe in the holidays...

**Comment by marvinseifert** [comment]
Hi Matthias, thanks for your answer. I was just playing around with it an thought the normalization would be the same in herdingspikes and spiketoolkit. Thanks for letting me know, that this is not the case. I will just use the normalization p['pre_scale'] = True, in herdingspikes, that works fine.
