### ISSUE TITLE
get_unit_waveforms and get_unit_templates do not work with Kilosort sorting/recording extractors

### ISSUE THREAD

**Issue by hamdanspam** [SpikeInterface/spiketoolkit#437]
I have been trying to visualize waveforms using `st.postprocessing.get_unit_waveforms` on Colab using Kilosort Sorting/Recording extractors.

The data have not been sorted with Phy, but it seems to me that that should not matter. Let me know if I should do that, though.

The issue is that I can call `st.postprocessing.get_unit_waveforms`, but when I plot them, they appear to be more or less noise, with a spike or two thrown in occasionally apparently by chance.

```
wfs = st.postprocessing.get_unit_waveforms(
      KS_recording, KS_sort, max_spikes_per_unit=1000,
      ms_before=1, ms_after=1,compute_property_from_recording=True,
      # verbose=True,
      unit_ids=[ci_df['id'].values[ind]],
      channel_ids=[ci_df['ch'].values[ind]],
      recompute_info=True
  );
```

When I call `st.postprocessing.get_unit_templates`, I get a large nested array with the right shape, but with only zeros.

I would appreciate any insight.

**Comment by alejoe91** [comment]
Can you try to compute the waveforms and templates on all channels? Using `channel_ids=None`. I think that this is also causing the plotting to fail. 

Another thing, is the recording filtered? If not, then probably this could be the problem, since waveforms are extracted from the raw (unfiltered) data. You can add a bandpass filter as this:

```
recording = st.preprocessing.bandpass_filter(KS_recording)
```

Note that in this case it will take more time to extract waveforms, since the recordings will be filtered before computing the waveforms. To speed up this process, you can distribute it over many jobs. You can add this extra args: `n_jobs=8` (or more) and `chunk_mb=2000` (this controls how much ram to use in Mb). Let me know if this fixes the issue.

**Comment by hamdanspam** [comment]
```
# Extract Recording and Sorting objects
KS_recording = se.KiloSortRecordingExtractor(DATA_PATH)
KS_sort = se.KiloSortSortingExtractor(DATA_PATH)

# Filter recording
KS_recording_filtered = st.preprocessing.bandpass_filter(
    KS_recording,
    chunk_size=2000,
)

# Get waveforms
wfs = st.postprocessing.get_unit_waveforms(
    KS_recording_filtered, KS_sort,
    max_spikes_per_unit=200,
    ms_before=1, ms_after=1,
    compute_property_from_recording=True,
    verbose=True,
    unit_ids=ci_df['id'].values,
    channel_ids=None,
    recompute_info=True,
    n_jobs=7,
    chunk_mb=2000,
    save_property_or_features=True
)

# Get templates
templates = st.postprocessing.get_unit_templates(
    KS_recording_filtered, KS_sort,
    max_spikes_per_unit=200,
    ms_before=1, ms_after=1,
    compute_property_from_recording=True,
    verbose=True,
    unit_ids=ci_df['id'].values,
    channel_ids=None,
    recompute_info=True,
    n_jobs=7,
    chunk_mb=2000,
    save_property_or_features=True
)

# Plot unit templates
# Taken from https://spikeinterface.github.io/blog/ensemble-sorting-of-a-neuropixels-recording/
sw.plot_unit_templates(
    KS_recording_filtered,
    KS_sort,
    unit_ids=[10],
    max_spikes_per_unit=10,
    channel_locs=True,
    radius=75,
    show_all_channels=False,
    lw=1.5,
    plot_channels=False
);


```

For the graph, I get this:
![image](https://user-images.githubusercontent.com/15875720/104645111-7c2ce480-5663-11eb-9ba4-61dabf6531f0.png)

So it seems that filtering does not remove the divide by zero error. I noticed that the first few waveforms for a particular channel are actual signal, but after a certain point, they are all zeros again. 

Templates appear to be all zeros too. You mentioned [here](https://github.com/SpikeInterface/spikewidgets/issues/75) that

> Vscale is computed from the waveforms to space the different waveform plots. Is it possible that one waveform is all zeros?

This appears to be the case. How can I stop that from happening?

**Comment by alejoe91** [comment]
Not sure..I have to see the data. Do the recordings look good? Have you tried to open the kilosort output in phy?

**Comment by hamdanspam** [comment]
I have not opened these data in phy because it's large and in the cloud, but I agree that that is a good first step. I will confirm that the recordings look good.

**Comment by hamdanspam** [comment]
The recording has not been sorted in phy, however.

**Comment by alejoe91** [comment]
The output of kilosort can be opened directly in phy. ( You should have a params.py and a bunch of .npy files). Since waveforms becomes all zeros after some time, I suspect there could be something wrong with the recording..if waveforms are mainly zero, also templates will be

**Comment by hamdanspam** [comment]
@alejoe91 figured out that the issue came from the fact that my recording was shortened but the spike sorting applied to the whole recording, leading to some zeroed values. The recording may not have started from the actual beginning either, leading to misaligned values. This duration mismatch will be checked against in the future.
