### ISSUE TITLE
Curation removes unit properties from the original sorting

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#442]
Now it seems that after curation (e.g. using `threshold_firing_rates`) computed unit properties e.g. max_channel etc.  from the original sorter are lost, and need to be re-computed again. But shouldn't these properties be inherited from the original sorter?

I am on spiketoolkit version 0.7.2

**Comment by alejoe91** [comment]
Hi @teristam 

Can you try with master? I think I fixed it :)

**Comment by teristam** [comment]
Thanks! Sorry for asking these kind of questions. Really don't know how outdated the pip version is from the master...

**Comment by teristam** [comment]
btw, do you have an estimate when will these changes be pushed to the pip version? I am developing the sorting pipeline to be used by many members of my group. It will be great if they don't need to install from master every time....

**Comment by alejoe91** [comment]
A couple of months! You can check the Releases page and the last commit date :) I suggest always using the master version and pull every couple of weeks

**Comment by alejoe91** [comment]
I would say we make a new release for the single packages every couple of months, so you can base it on master and freeze it to 0.7.3 once released

**Comment by teristam** [comment]
Hi, I just install the master, but I seem to still have the same problem.

```
print('Doing curation...')
sorting_ms4_curated = st.curation.threshold_snrs(sorting=sorting_ms4, recording = recording,
  threshold = 2, threshold_sign='less',
    max_snr_spikes_per_unit=100, apply_filter=False) #remove when less than threshold

print('Original:')
print(sorting_ms4.get_unit_property_names(0))
print('Curated:')
print(sorting_ms4_curated.get_unit_property_names(0))
```

Output:


```
Doing curation...
Original:
['group', 'max_channel', 'mda_max_channel', 'mean_firing_rate', 'number_of_spikes', 'snr', 'template', 'waveforms_channel_idxs']
Curated:
[] 
```

Have I missed anything? When I run the master, it encountered an error with spikemetrics 0.2.2, so I have updated it to 0.2.3.

**Comment by alejoe91** [comment]
Ok then I'll look into it! Should be an easy fix ;) I'll let you know when it's done

**Comment by alejoe91** [comment]
@colehurwitz do you have time to look into this? The CurationSortingExtractor base class does copy props and feats, so I don't know why this is happening

**Comment by colehurwitz** [comment]
Yes, I will check this out

**Comment by colehurwitz** [comment]
Hmm, I could not reproduce the error. I created this script:

```
import spikeextractors as se
import spiketoolkit as st

recording, sorting = se.example_datasets.toy_example()

for unit_id in sorting.get_unit_ids():
    sorting.set_unit_property(unit_id=unit_id, property_name="foo", value=0)


print('Doing curation...')
sorting_curated = st.curation.threshold_snrs(sorting=sorting, recording = recording, threshold = 2, threshold_sign='less', max_snr_spikes_per_unit=100, apply_filter=False) #remove when less than threshold


print('Original:')
print(sorting.get_unit_property_names(1))
print('Curated:')
print(sorting_curated.get_unit_property_names(1))
```

Output
```
Doing curation...
Original:
['foo', 'max_channel', 'snr', 'template']
Curated:
['foo', 'max_channel', 'snr', 'template']
```

Versions:

spikeextractors: '0.9.3'
spiketoolkit: '0.7.2'
spikemetrics: '0.2.3'

**Comment by colehurwitz** [comment]
Maybe this is a Mountainsort4 extractor issue? Although I am not sure why that would be the case.

**Comment by alejoe91** [comment]
I think this is fixed! https://github.com/SpikeInterface/spiketoolkit/blob/master/spiketoolkit/validation/quality_metric_classes/utils/curationsortingextractor.py#L28-L31
