### ISSUE TITLE
get_unit_waveforms parameter update

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#444]
Hi,

There is a bug, where if I extract the waveforms twice with different parameters, the parameters from the first function call will be applied:

```
sessions = [0, 1]

recordings = [spikeextractors.BinDatRecordingExtractor("0153/session_{0}/rec/sorted.dat".format(session+1), 30000, 64, np.int16) for session in sessions]
sortings = [spikeextractors.PhySortingExtractor("0153/session_{0}/extraCellAnalysis/phy".format(session+1)) for session in sessions]
units_ids = [np.array(sorting.get_unit_ids(), dtype=np.uint16) for sorting in sortings]
units_channels = [np.array(spiketoolkit.postprocessing.get_unit_waveforms(recordings[i], sortings[i], unit_ids=units_ids[i], return_idxs=True, max_spikes_per_unit=2000, max_channels_per_waveforms=1, ms_before=2, ms_after=3)[2], dtype=np.uint16)[:, 0] for i in range(len(sessions))]
units_shanks = [channels // 16 for channels in units_channels]

print(np.array(spiketoolkit.postprocessing.get_unit_waveforms(recordings[0], sortings[0], unit_ids=[44], max_spikes_per_unit=4000, ms_before=1, ms_after=1)[0], dtype=np.uint16).shape)
```

The output isn't an array of shape `(4000, 64, 60)` as expected but `(2000, 1, 150)`.
If I change the first function call (e.g. from 2000 to 1500), then the shape of the last line becomes `(1500, 1, 150)`.

Why is it not applying the correct parameters?
Is it something to do with a cache?

**Comment by alejoe91** [comment]
Hi,

This is because waveforms are cached. To recompute them, just add the `recompute_info=True` argument :)

**Comment by Dradeliomecus** [comment]
Ah I see, thank you! :)
You're the best!

But shouldn't that be `true` by default?

**Comment by alejoe91** [comment]
> Ah I see, thank you! :)
> You're the best!
>

Thanks! And no worries!

> But shouldn't that be `true` by default?

I think it's better to have it False, because otherwise if you have multiple calls to get_unit_waveforms it would be very te consuming!

**Comment by colehurwitz** [comment]
I do think this is a potential source of errors though. If a user is changing the waveform parameters (such as max_channels_per_waveforms), I don't think that recompute_info should be False such that they end up with something different than what they asked for. Not sure how to solve this though other than to make recompute_info True by default, however, that does cause time concerns.

**Comment by colehurwitz** [comment]
@samuelgarcia @alejoe91 

Do you guys think this should be discussed further? I think what @Dradeliomecus mentioned above is actually a bug and should be addressed somehow.

**Comment by samuelgarcia** [comment]
I think this is something we have to take in account in the next refactoring.
Since we will have an object to extract waveform, if we change the parameters then the cache should be destroy or unlink automatically.
