### ISSUE TITLE
compute_unit_pca_score assume unit_ids is a list

### ISSUE THREAD

**Issue by teristam** [SpikeInterface/spiketoolkit#445]
Hi,

In `compute_unit_pca_score`, it seems to assume that `unit_ids` is always a list, so it make extensive of `idx_waveform = unit_ids.index(unit_id)`, but from the code, it can actually also be a `np.ndarray` , due to the check `    elif not isinstance(unit_ids, (list, np.ndarray)):`. Similar problems may also exist in other functions.

Some 3rd party extractor, e.g. those from spikeforest2, return `unit_ids` as a `np.ndarray` and it breaks the metrics code there. Should be just a one-liner to  make sure `unit_ids` is a list?

Thanks!

**Comment by colehurwitz** [comment]
I think converting unit_ids to a list in the `compute_unit_pca_score ` function is the best solution currently. Although it is not great that third party extractors return different objects than our extractors. We should check with spikeforest2 about that.
