### ISSUE TITLE
spiketoolkit.preprocessing.remove_artifacts.RemoveArtifactsRecording traces can't be used

### ISSUE THREAD

**Issue by joramvanrheede** [SpikeInterface/spiketoolkit#448]
After I have used st.preprocessing.remove_artifacts() on a recordingextractor, I am unable to use the get_traces() method on the new 'RemoveArtifactsRecording' extractor or use spikewidgets.plot_timeseries() to visualise my artifact-free traces.

In both cases I get with the following error:

> File "... my_env\lib\site-packages\spiketoolkit\preprocessing\remove_artifacts.py", line 28, in get_traces
>     traces[:, trig - pad[0]:trig + pad[1]] = 0
> ValueError: assignment destination is read-only

I assume it has somethig to do with the fact that the RemoveArtifactsRecording extractor uses a memmap rather than having the whole trace available, but is there a way to get around this?

**Comment by alejoe91** [comment]
Hi @joramvanrheede 

We had the same problem with another preprocessor and ended up calling a `copy()` of the traces before applying the changes. Will make a PR tomorrow, unless you want to give it a try?

**Comment by joramvanrheede** [comment]
Hi Alessio,

Thanks for the quick reply - I'm happy to give it a try tomorrow afternoon! 

Joram

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/449
