### ISSUE TITLE
Replacing artifacts with interpolation

### ISSUE THREAD

**Issue by joramvanrheede** [SpikeInterface/spiketoolkit#451]
I'm currently dealing with a data set that involves electrical stimulation, and the artifacts are HUGE. They also seriously affect the quality of the spike sorting.

Currently remove_artifacts() sets parts of the traces affected by artifacts to 0. Therefore, running it on the raw signal (which often fluctuates some distance away from 0) produces a trace that has a lot of sudden deviations to 0 that are problematic in their own right.

Running remove_artifacts() on a high-pass filtered recording (obtained using bandpass_filter() ) gets rid of this issue, but when artifacts are very large (as in my current recordings) there is filter ringing behaviour that affects a wider part of the trace. 

For my purposes it would therefore be very helpful to replace artifacts in the raw trace using some kind of interpolation between the start and the end of the artifact window.

I'm going to have a go at making my own 'interpolate_artifacts.py' with an 'InterpolateArtifactsRecording' class - I can generate a pull request if you think this would be of interest to others. 

It looks like the get_traces() method of the RemoveArtifactsRecording class is the crucial place for implementing this - are there any other places you think I should make edits to accomplish this?

**Comment by alejoe91** [comment]
Hi @joramvanrheede 

I think it's a good idea, even though I'm not sure what the best interpolation would be.
I think that the best but not trivial option would be to fit some kind of AR model to the data and predict the missing values using that. 

But sure give it a go with a PR and we can discuss on that! You could also modify the `remove_artifact` by adding an argument (e.g. `mode='zeros' / 'interpolate'`).

Yes, everything you need to modify is the `get_traces()` method (in case you don't need other computations -- e.g. in the `CenterRecording` the center value for each channel is computed in the `__init__`

**Comment by joramvanrheede** [comment]
Thanks Alessio - I will go with your suggestion of adding a 'mode' argument to remove_artifact for now - that does seem more sensible, will report back once I've got something working

**Comment by joramvanrheede** [comment]
Hi @alejoe91 

I've currently got something working using scipy.interpolate.interp1d. 

Using spaced out samples from 1ms before and after the artifact window, I fit a cubic spline and then I replace the artifact samples by the values for that fit at the sample points. It seems to achieve a relatively smooth continuation of the trace. 

(I use spaced out samples because if using only the last 2-3 samples on either side of the artifact window the fit is very susceptible to random fluctuations at that point)

I've accounted for edge cases with no samples before/after by simply filling the nearest available value.

Currently testing it on a full data set. If it all runs fine - can you see any fundamental problems with this approach or should I prepare a pull request?

**Comment by alejoe91** [comment]
Hi @joramvanrheede 

What if in the 1ms before or after the window there's a spike? I guess a simple check on the amplitude of the sampels wrt to the std of a 1s snippet of the traces could work to avoid that.

Yes please make a PR :) Can you paste some images of the fitted data there? 

Cheers
Alessio


PS: Cheers from Julian too ;)

**Comment by joramvanrheede** [comment]
Fair point - 1ms is probably still a bit risky I will experiment with basing the fit on a median data point from 0-1ms, 1-2ms ms and 2-3ms before. Using the medians should be fairly robust to spikes, and having the fit reference points spaced out over a slightly longer interval should hopefully avoid extreme curves.

Will post some pictures later.

Cheers,

Joram

PS - yes, I only realised that you worked together the other day!

**Comment by joramvanrheede** [comment]
Hi Alessio, I've just created a pull request - the proposed new version of remove_artifacts has a 'mode' argument that defaults to 'zeros' (old behaviour), but can now also include 'linear' (for linear interpolation) and 'cubic' for cubic spline interpolation. There is an additional input argument 'fit sample spacing' that determines the spacing of sample points for the cubic spline before and after the artifact (defaults to 1ms).

This is what the 'cubic' looks like with our big stim artifacts (where there is also a considerable effect on the LFP!)
![GP_cubic](https://user-images.githubusercontent.com/13217618/108245893-b862d180-7148-11eb-9609-2482ec7931f2.png)

This is 'linear' in the same situation; it makes things better but there are sharp transitions (high frequency content) on either side of the artifact:
![GP_linear](https://user-images.githubusercontent.com/13217618/108245898-b8fb6800-7148-11eb-80b1-3a330c847551.png)

Here is a different location with 'cubic', further away from the stimulation: no LFP effect, only a large stim artifact:
![Other_cubic](https://user-images.githubusercontent.com/13217618/108245899-b8fb6800-7148-11eb-9676-e1a3e99e2576.png)

Here is 'linear' for the same location; as you can see when the trace is relatively flat, linear and cubic look fairly similar:
![Other_linear](https://user-images.githubusercontent.com/13217618/108245900-b993fe80-7148-11eb-97ce-157526284ec4.png)

**Comment by joramvanrheede** [comment]
I've tried to account for your concern about high frequency fluctuations by 1) allowing the user to define the spacing of the fit sample points (larger spacing = more robust cubic fit), and 2) by taking the median of 5 samples around each sample point for the fit, so that very local extreme values have less influence; it seems to do a decent job.
