### ISSUE TITLE
Add filter_flag to export_to_phy

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#455]
Hi,

I'm running `export_to_phy` with a non-filtered recording, and I always get the warning.

I noticed in the source code that there is an `empty_flag` for this function, but not a `filter_flag`.
Could it be added?

Thanks!

**Comment by alejoe91** [comment]
Hi,

Where is the `empty_flag` you mention? Sure it could be added. Can you make a PR?

**Comment by Dradeliomecus** [comment]
Here is the `empty_flag` (the filter recording is just below):
https://github.com/SpikeInterface/spiketoolkit/blob/61f9231cbdc9521a46acca6428ce25e1bab5288c/spiketoolkit/postprocessing/postprocessing_tools.py#L1291

I'm gonna try to make a PR (I've never done it before, but I should be able to figure it out with Google).

**Comment by Dradeliomecus** [comment]
The PR should be done (#456).
