### ISSUE TITLE
CurationSortingExtractor resets tmp folder

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#458]
Hi!

If I make a `SortingExtractor` where I set the `tmp_folder`, and then create a `CurationSortingExtractor` from this previous sorting, then it will reset the `tmp_folder` to `/tmp`.
I need to manually get the previous `tmp_folder` and set it again once the cast is done.

I believe this is a bug?

Best,
Aurélien

**Comment by alejoe91** [comment]
It's like this by construction, but I agree that for the CurationSortingExtractor the `tmp_folder` could be copied over from the parent sorting. 

@colehurwitz would you agree? 

@Dradeliomecus could you make a PR about this? You just need to set the tmp folder in the `CurationSortingExtractor` init

**Comment by Dradeliomecus** [comment]
It's done: #459
