### ISSUE TITLE
save_pc_features all_waveforms takes a lot of disk space

### ISSUE THREAD

**Issue by Dradeliomecus** [SpikeInterface/spiketoolkit#461]
Hi,

While using `export_to_phy`, I found that if `save_pc_features` is set to `True`, then it saves a file `all_waveforms.raw` containing the same information as all the `waveforms_x.raw`.
This duplicates all the waveforms temporarily saved on disk, which in my case writes an additional `62 GB` (for a total of 124 GB), which takes a lot of space and takes a lot of time to write (unless a NVMe SSD is used).

Is there a way to not rewrite the `all_waveforms memmap`? If so, it seems it could be a good improvement.

**Comment by alejoe91** [comment]
Hi @Dradeliomecus 

This is true but it's needed to compute PCA. Do you have a better solution in mind?

**Comment by samuelgarcia** [comment]
We could estimate the pcd projetion (pca.fit) on a subset.
Then we could pca.transform(wf) on the fly without cahce to disk.

**Comment by Dradeliomecus** [comment]
> We could estimate the pcd projetion (pca.fit) on a subset.
> Then we could pca.transform(wf) on the fly without cahce to disk.

I agree,
If the data is this big, the fit can be done on a subset of spikes ; there is no need to use all of the spikes.

**Comment by alejoe91** [comment]
@Dradeliomecus can you try to make a PR for it?

**Comment by Dradeliomecus** [comment]
I can try.
I'll take be a little while to make it and test it, but hopefully I can make it today :)
