### ISSUE TITLE
allow to set TMP directory for phy_export ? 

### ISSUE THREAD

**Issue by gmaggi** [SpikeInterface/spiketoolkit#469]
Hello,

Apparently, during the phy_export operation, several (~200) files are created in the /tmp folder.
Those files are named waveforms_*.raw. It turns out that those fill up the /tmp folder and yields a crash in the job execution.

Is there a way to choose another location to store these waveforms_*.raw?
Also, could you tell me please what is the function of these waveforms_*.raw?

Thanks,
Giuliano.

**Comment by MFVDias** [comment]
Hi Giuliano, 

I ran into the same problem and started using the `set_tmp_folder` method to set a temporary folder on an external SSD.
```
sort_all.set_tmp_folder('/Volumes/DataProc/Spikeinterface/tmp')   
st.postprocessing.export_to_phy(rec_cmr,
                                sort_all,
                                output_folder='phy_test')
```

I create the temporary folder in advance with:

```
import os
tmp_folder = '/Volumes/DataProc/Spikeinterface/tmp'
if not os.path.exists(tmp_folder):
    os.mkdir(tmp_folder)
```

**Comment by gmaggi** [comment]
Hi @mfvd , 
Thank you for the tip, and sorry for my delayed feedback.
The workaround works well!

Thanks,
Giuliano.
