### ISSUE TITLE
Peak SNR

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#47]
"Peak amplitude of mean template, divided by RMS noise level, after filtering. This is the max over time and electrode number. Noise level (σ) may be robustly estimated using median absolute deviation (MAD) computed from filtered data, scaled to a Gaussian equivalent σ. 

This requires a standard definition of filter parameters purely for the computation of this quality metric. (excluding spatial whitening)"

- Metric taken from - Proposal for web-based spike sorting validation - Alex Barnett, Jeremy Magland, and James Jun

**Comment by samuelgarcia** [comment]
I have done something like this on Spampinato ground truth dataset 252 channels.

See https://github.com/SpikeInterface/spikeresults/pull/1

**Comment by alejoe91** [comment]
this is implemented in the quality metrics
