### ISSUE TITLE
Local CAR - Neuropixels radius values 

### ISSUE THREAD

**Issue by MarineChap** [SpikeInterface/spiketoolkit#476]
Hello,
Some remaining bugs to fix : 
- crashed with the verbose option (tuple transformed in str)
- crashed when there is no cell contained in the annulus (exclude/include radius to close from each other) 

I will do a PR fixing it. 

However, I still have a question about the unity of the electrode distances for the neuropixels. Where in catgt you would put 2,8 um as radius, I don't know what would be the equivalent in spike interface.

Here, as an example,  the nearest distance obtained from the electrodes 10 on my neuropixels probes: 
```
[  25.61249695   25.61249695   32.           40.           40.
   51.2249939    51.2249939    52.           52.           62.09669879
   62.09669879   76.83749085   76.83749085   80.           80.
   86.16263691   86.16263691  101.27191121  101.27191121  110.92339699
  110.92339699  120.          120.          ....]
```

Thanks, Have a good day

**Comment by alejoe91** [comment]
Hi @MarineChap 

Thanks for pushing a fix. Regarding the distances, those I'm not sure what a good value would be. Where did you get the 2, 8um from? Sorry, what is catgt? The physical distance between electrodes in neuropixels is around 20um..so I would use at least 40-100um

**Comment by MarineChap** [comment]
Hello @alejoe91, 
CatGT is the tool developed by Bill Karsh for  neuropixels pre-processing including a local car. But indeed, now that I am looking better in the doc I think 2,8 is the number of electrodes sites and not the distance in um as my colleagues told me. 
Thanks. We will do some tests to see what it is the best values.

**Comment by MarineChap** [comment]
@alejoe91  Sorry to bother you with that but just checking in case of local radius chosen too close, what would you expect as behavior : 
- raise an error when creating the CommonReferenceRecording object (same place as other asserts)
- raise an error in get_traces 
- Don't raise an error - just don't remove any reference value from the channel concerned

Thanks

**Comment by alejoe91** [comment]
Hi @MarineChap 

No worries at all! I would raise an error when creating the object
