### ISSUE TITLE
Error in Template Waveform Extraction 

### ISSUE THREAD

**Issue by gprabaha** [SpikeInterface/spiketoolkit#479]
I am trying to extract the individual and the average (template) waveform for each unit, which I am extracting using MountainSort. To do that I use the following commands:

    templates = st.postprocessing.get_unit_templates(recording, sorting, max_spikes_per_unit=200,
                                                    save_as_property=True, verbose=False)
    max_chan = st.postprocessing.get_unit_max_channels(recording, sorting, save_as_property=True, verbose=False)
    wf = st.postprocessing.get_unit_waveforms(recording, sorting, ms_before=1, ms_after=2,
                                                save_as_features=True, verbose=True)

The waveforms extracted seemed to be shifted along the Y-axis, and I am not sure the scale is the same for all the waveform. Below are extracted waveforms from a file plotted.

![bla_1_04122016_kurosawacoppola_pre_templates_extracted_ms4 =50x50](https://user-images.githubusercontent.com/11420071/114453286-628a3300-9ba7-11eb-9c7f-1b602415f0bf.png)

In contrast, if I use the *firings.mda* file, and use the spiketimes in it to extract individual spikes out from the filtered wideband data, then calculate the average waveforms from it, those waveforms look fine (this has been dome in Matlab though). Here is the case where I calculated the average waveform by averaging all spikes:

![bla_1_04122016_kurosawacoppola_pre_avg_waveform_ms4_sorting](https://user-images.githubusercontent.com/11420071/114453913-0673de80-9ba8-11eb-88cb-70409b4f6848.png)

And here is the case where I max-normalized each spike before calculating the mean waveform:

![bla_1_04122016_kurosawacoppola_pre_avg_norm_waveform_ms4_sorting](https://user-images.githubusercontent.com/11420071/114454204-5783d280-9ba8-11eb-9429-896282b70358.png)

So if the spiketimes are correct, then I wonder why the template waveforms extracted in python look weird. I plan to use features extracted of the units using `st.postprocessing.compute_unit_template_feature`, so I want to make sure that the templates are being extracted correctly.

**Comment by alejoe91** [comment]
Hi!

Is `recording` filtered? I think that the offsets might be due to the recording not being filtered when you extract the template. Can you try to filter it with `st.preprocessing.bandpass_filter` and run it again?

**Comment by gprabaha** [comment]
Thanks for the suggestion! `recording` was not filtered, so now I am using `recording_f` instead, which is Butterworth filtered. Below is the updated post-processing function:

    def postprocess_recording(recording_f, sorting, file_name, output_path_parent, output_dir_name):
    
      output_dir = output_path_parent + output_dir_name + file_name + "/"
      if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)
      
      ###################################################
      # Extract the shape of each waveform of each unit #
      ###################################################
      example_wf = st.postprocessing.get_unit_waveforms(recording_f, sorting, ms_before=1, ms_after=2,
                                                save_as_features=True, verbose=True)
      print("Shared unit spike feature names: ", sorting.get_shared_unit_spike_feature_names())
      print("Waveform count summary (n_spikes, n_channels, n_points)", example_wf[0].shape)
    
      #######################################################
      # Retreive the channel of highest prob. for each unit #
      #######################################################
      max_chan = st.postprocessing.get_unit_max_channels(recording_f, sorting, save_as_property=True, verbose=False)
    
      ##########################################
      # Get the average waveform for each unit #
      ##########################################
      templates = st.postprocessing.get_unit_templates(recording_f, sorting, max_spikes_per_unit=None,
                                                      save_as_property=True, verbose=False)
    
      savename = output_dir+file_name+'extracted_features.mat'
      scipy.io.savemat(savename,{'example_waveforms':example_wf,'maxchn':max_chan, 'templates':templates}, do_compression=True)                                                
      
      ###################################################
      # Compute verification metrics like isi violation #
      ###################################################
      metrics= st.validation.compute_quality_metrics(sorting=sorting, recording=recording_f,
                                                    metric_names=['firing_rate', 'isi_violation', 'snr'],
                                                    as_dataframe=True)
    
      metrics.to_csv(output_dir + "metrics.csv")                                              
      
      #######################################################################
      # Compute waveform features like half-max width and peak-trough ratio #
      #######################################################################
    
      features = st.postprocessing.compute_unit_template_features(recording_f, sorting, max_spikes_per_unit=None, as_dataframe=True, 
                                                                upsampling_factor=10)
    
      features.to_csv(output_dir + "features.csv")

And the template outputs now align well as shown below:

![bla_1_04122016_kurosawacoppola_pre_templates_extracted_ms4](https://user-images.githubusercontent.com/11420071/114562683-b6932700-9c3c-11eb-9897-bebd4e124c0b.png)

As a followup, should I be using `recording_f` everywhere? I had been using `recording` to pass as a parameter to `ss.run_mountainsort4`, with `default_ms4_params['filter'] = True`. Now I updated the script to use `recording_f` everywhere. That seems to have reduced the variability in output across multiple runs on the same file, but still, the number of units extracted vary in some runs. Here is an example of a run where the output looks different from above:

![bla_1_04122016_kurosawacoppola_pre_templates_extracted_ms4](https://user-images.githubusercontent.com/11420071/114563732-ad568a00-9c3d-11eb-8283-d3ac329a8e06.png)

**Comment by alejoe91** [comment]
Hi! 

So of course for postprocessing you need to use filtered data, because the postprocessing functions use whatever recording you give as input and to get spikes you need filtered data.

Internally mountainsort4 and other sorters filter the data by default, so it's your choice whether to use SI for filtering as well or to rely on the different sorters. Personally, I would filter everything in SI so you are sure that the processing is the same.

Regarding getting different outputs for different spike sorting runs, this is probably due to the sorter internally using some random seeds and some subsampling of spikes/waveforms. The main units however should be the same

**Comment by gprabaha** [comment]
Hi!
I am calculating the templates of each unit using all the spikes identified, setting `max_spikes_per_unit=None`. But for storing, it seemed better to keep the default 300 samples of waveforms retrieved from `st.postprocessing.get_unit_waveforms`. I also wanted to store the SEM of the waveform, but if I have to calculate that, then I have to extract all the waveforms and then calculate SEM of the individual units. I thought some inbuilt functions might already have access to that information and spit the error out?

**Comment by alejoe91** [comment]
SpikeInterface caches the waveforms so when you call the get templates it's not recomputing them by default. To force recomputation, you can add the `recompute_info=True` argument to the `get_unit_templates` function

**Comment by alejoe91** [comment]
For the SEM question, this is not implemented in SI yet, but you could compute it 'manually'  and then store it as a property with the `set_unit_property` function
