### ISSUE TITLE
Refractory Violations and Ratio

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#52]
The ratio between the frequency of spikes present within 0- to 2-ms interspike interval (ISI) and those at 0- to 20-ms interval is defined as the ISI ratio. It can be used as a measure of possible contamination of an isolated single unit by spikes of another unit.  

- Metric taken from: Large-scale, high-density (up to 512 channels) recording of local circuits in behaving animals - Antal Berényi, et al.

**Comment by alejoe91** [comment]
this is done, right @colehurwitz ?

**Comment by colehurwitz** [comment]
In theory, yes, but still needs unit tests at some point.
