### ISSUE TITLE
Add HS2 in sorter list

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#54]
@colehurwitz31 @mhhennig : would it be lot of work to implement HS2 in sorter list ?

**Comment by colehurwitz31** [comment]
There are a couple challenges that we need to solve to implement HS2 within SpikeInterface.

- Our read functions need to be replaced with recordingextractors (this is doable)
- We have a Probe object for each acquisition system that requires a specific channel position file associated with it. We need this for our localization. We have to somehow work the Probe object and the channel positions into our wrapped-sorter
-We have a session class for running and visualizing the sorting using HS2. We would have to extract the relevant functions from this class for running our code and put that into the SpikeInterface Sorter class.

Other than that, I think we can implement HS2 relatively easily in spiketoolkit.

**Comment by alejoe91** [comment]
a5cbb014685062ff6de63b72f2c4302807f6d490
