### ISSUE TITLE
Some sorters have a high verbosity event with debug=False

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#55]
In the new class approach. there is debug=False/True.

The goal is mainly to act on the verobose to debug or not.
This is not taken in account by many sorter that display lot a message.
For instance klusta or MS4 are verbose too much for my taste.

If we want, to run many sorter on many dataset,the inner verbosity of each run should be off to keep an eye on the main thing.

No ?

**Comment by samuelgarcia** [comment]
Further more, if we want to publish notebbok to compare results of sorters, the run of each sorter should off.

**Comment by samuelgarcia** [comment]
Klusta verbosity is very annoying.
Maybe we can do something directly on the klusta repo.

**Comment by samuelgarcia** [comment]
HS2 is quite verbose too.
@colehurwitz31 @mhhennig : could you turn off console output when self.debug=False ?

Note that self.debug can be change to self.verbose in BaseSorter if you prefer.

**Comment by alejoe91** [comment]
I think we can just catch the stdout from the popen function. Let's discuss tomorrow

**Comment by alejoe91** [comment]
@samuelgarcia 
Update:
I made a PR to klustakwik2 and I removed the initial print.
You can install locally from the master branch: https://github.com/kwikteam/klustakwik2

I asked to release a new version on Pypi too :)

**Comment by samuelgarcia** [comment]
Thanks.

**Comment by alejoe91** [comment]
@samuelgarcia 

Just uploaded a new release for klustakwik2 :)
try pip installing it  (0.2.7) and it should not give the log message!

**Comment by samuelgarcia** [comment]
Yeah.
you are a boss.

**Comment by alejoe91** [comment]
Move to spikesorters
