### ISSUE TITLE
Add yass in sorter list

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#58]
Add yass in sorter list.
yass is written in python and there is 2 API:
  * command line level
  * python level
It should be super easy to implement.

**Comment by alejoe91** [comment]
@samuelgarcia I have some code, but I fould yass to be poorly documented.

Have you tried it before? maybe we can reach out tp the paninski lab and ask if someone is interestred in implementing it?

**Comment by samuelgarcia** [comment]
In the doc [here](https://yass.readthedocs.io/en/latest/getting_started.html)


run yass as a script seems trivial:
```
import logging
import numpy as np

import yass
from yass import preprocess
from yass import detect
from yass import cluster
from yass import templates
from yass import deconvolute

np.random.seed(0)

# configure logging module to get useful information
logging.basicConfig(level=logging.INFO)

# set yass configuration parameters
yass.set_config('config_sample.yaml', 'deconv-example')

standarized_path, standarized_params, whiten_filter = preprocess.run()

(spike_index_clear,
 spike_index_all) = detect.run(standarized_path,
                               standarized_params,
                               whiten_filter)


spike_train_clear, tmp_loc, vbParam = cluster.run(spike_index_clear)

(templates_, spike_train,
 groups, idx_good_templates) = templates.run(
    spike_train_clear, tmp_loc)

spike_train = deconvolute.run(spike_index_all, templates_)
```


Maybe we could start with this.

**Comment by alejoe91** [comment]
ok sounds good to me :) 
There is also kilosort2 https://github.com/MouseLand/Kilosort2/ that was released today!

**Comment by samuelgarcia** [comment]
new class ?

**Comment by samuelgarcia** [comment]
Started in #67.

**Comment by alejoe91** [comment]
Move to spikesorters
