### ISSUE TITLE
Effect of updating spike sorters on spiketoolkit

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#63]
If a developer was to update a spike sorter, changing either the parameters or the underlying implementation, would it break our class implementation of that sorter?

@alejoe91 @samuelgarcia

**Comment by samuelgarcia** [comment]
I don't get your question.
Do you mean : if a sorter have a API change does it break our classes ?

**Comment by colehurwitz31** [comment]
We already discussed this, but we should require a sorter pip version number. I was referring to if a sorter changed its underlying implementation or added new features, it would break our class. It also means that older versions of the sorter may not work with our wrappers.

**Comment by alejoe91** [comment]
With the spikesorters package this should be fixed. @samuelgarcia @colehurwitz  do you guys agree?

**Comment by colehurwitz** [comment]
Yes!
