### ISSUE TITLE
Proposal about spiketoolkit.comparison

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#69]
Today I have discovered and explore a bit the comparison submodule.
I mainly play with the sorting comparison at the moement.
This is very cool and cover many needs.
Thank you.

Here some feedback about the code itself:
  * There is a lake of documentation
  * there is a lake of unitests
  * variable do not have obvious naming for a newcomer (TP, FP, gtst, sst).  - BTW what is CL ? -

The class approach for SortingComparison is very good from the user behavior view.

But internally important and complicate function like **_do_matching _do_counting _do_confusion** are hard to read because they are in the class itself.

Theses 3 functions, as they are complicated should come with many unitests.
I think having this functionality inside isolated function would be better for the code debugging and reading. We could do that without breaking the behavior the method of class would do a call to the function.

@alejoe91 @colehurwitz31 @mhhennig : would it be OK if I would propose some refactoring on this module (100% compatibale of course) with this implementation that would split the difficulty of testing each piece ? I would also include some docs and variable renaming.

I have another proposal about this submodule:
  * **use pandas as backend to render results**

Some function like **compute_performance** are cool to display one results.
But we could the same function for a **list** of comparison and we would have a DataFrame with index as comparison and mletrics as columns.
What do you think ? It add a depency for the project but it is a very common one in the python world.

It would be perfect to compbing the laucher sorter on many datasetXsorter and the fact that we would collect many metrics in one function that return a  dataframe.
What do you think ?

I would be happy to hear your feedback about this.

**Comment by alejoe91** [comment]
Hi @samuelgarcia 

I think splitting the function that need tests in separate functions, maybe in a sorting_tools file is a great idea. I agree we should write extensive tests on them, e.g. comparison between the same set of spike trains etc.

Documentation should also be added.
BTW, CL is classification error - gtsts: ground truth spike train - sst: sorted spike trains. This is taken from literature, but I agree that it's not straightforward and it should at leat be documented.

I'm also ok to use pandas as backend. I think that spikewidgets already has pandas as deoendency, and as you sais, it's a very common one.

Do you want to give it a try at refractoring? I can help too :)

**Comment by alejoe91** [comment]
Also I think that plotConfusionMatrix should be ported to spikewidgets

**Comment by colehurwitz31** [comment]
Yes, I agree with your comments Samuel! Thanks for looking at each of our modules with a critical eye, it is very helpful.

I think adding **pandas** as a dependency is fine also. We really want to keep dependencies out of the spikeextractors module, but we are more flexible on spiketoolkit.

**Comment by samuelgarcia** [comment]
Thank you for feedback.
I will try to start the refactoring when I will have some time.

**Comment by samuelgarcia** [comment]
Close by #73
