### ISSUE TITLE
Enhancement in sorter/launcher and avoid copy in sorter

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#71]
Many sorter have by internally the RawBinary as input.
In spiekextractor, it is the BinDatRecordingExtractor with frames_first=True.

This is more or less the universal format.
The main drawback, is that it do not have any metadata (dtype, nb_channel, smaple_rate,...)

Many sorter use this : tridesclous, spyking-circus, kilosort, kilosrt2, klusta, yass.

In the actual way all sorter are implemented, to make possible to have any extractor as input, each sorter make a deepcopy inside the **output_folder** with **writeBinaryDatFormat**.

For big files (like the Sampinato ground truth), this make the run_time totally unefficient, because the input file is copied many times.
Further more the writeBinaryDatFormat load everything in memmory to achieve this, (except for tridesclous where I made a by chunk writeBinaryDatFormat).

I propose the following change for theses sorter :
  * if the recording is **BinDatRecordingExtractor** and **frames_first=True**, then the file would 
    not be copied and the **BinDatRecordingExtractor._datfile** would be give to the sorter to 
    avoid this deepcopy.

So in sorter/launcher.py, I would also propose this change:
   * for each recording, force a **writeBinaryDatFormat** in the working_folder for each recording.
     Create a new recording with BinDatRecordingExtractor and give this input to all sorter.

With this we could solve many copy on the drive and we could facilitate to run many sorter on a cluster because only the rawbinary file path would be given which is easy to serialize (as oposed to Recording).

**Comment by samuelgarcia** [comment]
Started in #82

**Comment by alejoe91** [comment]
this has been merged. Closing!
