### ISSUE TITLE
Bug in Klusta

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#72]
In actual Klusta, there is a 
```
se.writeBinaryDatFormat(recording, output_folder / file_name)
```
which is 

```
se.writeBinaryDatFormat(recording, output_folder / file_name, transpose=False)
```
which no transpose so (nb_channel, nb_sample) but in teh doc here
https://klusta.readthedocs.io/en/latest/sorting/

They claim that klusta file must be (nb_channel, nb_sample) which is standard raw binary.
My guess is that kilosort also have the same problem because it was done in the same lab so the input file should the same same (nb_channel, nb_sample).

In **spikeextractors** ```writeBinaryDatFormat``` claim that  transpose=False is for (klusta, kilosort, yass), I think this is a mistake since getTraces give shape (nb_channel, nb_sample).

SC alos have this format (nb_sample, nb_channel) with **raw_binary**:
https://spyking-circus.readthedocs.io/en/0.4.3/code/data.html
but the one choosen here is **numpy** (see spikyingcircus config file) were the shape can be both situation, the timeaxis is guess from the shape size see:
https://github.com/spyking-circus/spyking-circus/blob/master/circus/files/npy.py

**Comment by alejoe91** [comment]
Hi @samuelgarcia 

I don't think it's a bug. You can see here that without Transpose=True it saves (n_samples, n_channels):
https://github.com/SpikeInterface/spikeextractors/blob/master/spikeextractors/extractors/bindatrecordingextractor/bindatrecordingextractor.py#L52-L53

Also we have tested klusta and kilosort and they work correctly. I also opened data saved to kilosort format in the new kilosort GUI and the signals look correct.

Also SC should work fine with the npy format.

Do you agree?

**Comment by samuelgarcia** [comment]
Oups. Sorry. I miss this

When transpose=False in fact it **do** transpose!!!
It is quite counter intuitive.

And this is very dangerous behavior, I definitly vote for time_axis=0 or time_axis=1 with a time_axis=0 by default.

**Comment by samuelgarcia** [comment]
And so the new implementaion is totally wrong.

https://github.com/SpikeInterface/spikeextractors/pull/105
