### ISSUE TITLE
Function naming --> Camel case or underscores?

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#76]
We have a mixture of function naming conventions in spiketoolkit:

computeUnitSNR
vs.
bandpass_filter

I think we need to pick one and stick to it. What are your thoughts on which we should pick?
@alejoe91 @samuelgarcia

**Comment by alejoe91** [comment]
7. Methods
Method names should be all lower case
Words in an method name should be separated by an underscore
Non-public method should begin with a single underscore
If a method name needs to be mangled, two underscores may begin its name

https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html

I htink we should stick tho this. This means refractoring all spikeextractors too

**Comment by alejoe91** [comment]
9. Functions
Function names should be all lower case
Words in a function name should be separated by an underscore

**Comment by colehurwitz31** [comment]
I see. Yeah, it looks like that is the convention. I don't mind either way if we are consistent.

**Comment by colehurwitz31** [comment]
Although it will be a big change for spikeextractors... I think we need to be consistent so I don't mind changing it..

**Comment by colehurwitz31** [comment]
Or should we do camel case because then we do way less refactoring?

**Comment by colehurwitz31** [comment]
What if we kept the camel case in the spikeextractors and made all functions in spiketoolkit underscores. That would be pretty consistent and would also be a visual differentiation between spikeextractor methods and spiketoolkit methods.. Thoughts? @alejoe91

**Comment by samuelgarcia** [comment]
Personnaly, I really prefer the under score for function and method.
Camel case are used for class name in python.

We could be banish from the python community for that :)
Guido itself could excommunicate all of us if we keep camel case!!!
Not talking about pep8 and linting soldiers from the python community looking into code.

**Comment by magland** [comment]
Hi all. Are we going to make the change to lower_case_with_underscore() functions? If so, can we do it now? Otherwise, let's not ever do it. I am okay with both routes. But if we switch to lower_case() we will need to make a big sync effort of all the code we have that uses spike extractors, etc.

**Comment by magland** [comment]
Thinking more about it... maybe we could freeze camelCase() for spikeextractors 0.3. Then for >=0.4 we plan to move to lower_case(). Then in our projects we can specify the 0.3 dependency.

**Comment by colehurwitz31** [comment]
I can do it today if we all want to go that route. I would just switch everything in spikeextractors first and then move to spiketoolkit and spikewidgets next. @samuelgarcia @alejoe91 @magland

**Comment by magland** [comment]
I'm okay with it @colehurwitz31, as long as you release as >=0.4 for SpikeExtractors.
And maybe we could use >=0.4 for spiketoolkit for consistency. (I notice that spiketoolkit has not been released to pypi for several months)

**Comment by colehurwitz31** [comment]
Ok, I will release the refactored spikeextractors as 0.4.0. I think we were waiting for sortercomparison to do another release, but we are still waiting until that is fully documented and checked.
