### ISSUE TITLE
Bias in compute_performance in sortingcomparison

### ISSUE THREAD

**Issue by samuelgarcia** [SpikeInterface/spiketoolkit#77]
I have spend a bit of times refactoring SortingSomparison so now I anderstand better how performance metrics are done even there some obscurs zone.

Here my main feeling: there is bias in how performances are computed.
This due to **_do_counting()**.
The count dict is **"summary"** of all by units countings (FP, FN, ...)
But this count dict is done by using a **sum**. this means that all spike from all units are pooled togother to make the performance metrics.
This bias the result towards units that have a strong firing rate.
I think you should also do an "average" acroos GT units performance and not a sum.

For instance, if unit_id=0 have many spike and a bad performance it would mak the fact that unit=1 that have few spikes and good performance.

It is obsvious, in spike sorting that units that have amplitude AND high firing that easier to detect.
Our performance enhance high firing.

@mhhennig @colehurwitz31 @alejoe91 @magland : what do you think ?

**Comment by alejoe91** [comment]
@samuelgarcia 

Very good point! We should take the average instead

**Comment by samuelgarcia** [comment]
I will make a big change today  in compute_performence(SortingComparison).
Actually the do_counting make a "pooled sum" of all TP/FP/...
This bias the result.
We need finer perf metrics.

I propose:
  * to add **SortingComparison.get_performance(self, method="...")**
    where **method** could be :
        * 'by_spiketrain' : return a pd.DataFrame by spiketrain of performance.
        * 'pooled_with_sum': return a pd.Serie with previous behavior for compatibility
        * 'pooled_with_average': same as 'pooled_with_sum' with average accros
  * and so to change the **do_counting()**
  * add **SortingComparison.print_performance(self, method="...")**
  * remove **def compute_performance(SC, ...)** because there are 3 differents case known.
  * add 3 functions one for each case.

This change will not be  retro compatible with previous code because I will need to chnage the _counts attribute and make it more complexe to deal with the 3 cases.

@alejoe91 @magland @mhhennig : are you OK with this ?
