### ISSUE TITLE
handle parameters in a standardized way

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spiketoolkit#79]
Each module should provide an interface of _default_params and _qtgraph_params

**Comment by colehurwitz31** [comment]
Can you explain _default_params vs _qtgraph_params again? Why do we have two param structures and how would we use them?

**Comment by colehurwitz31** [comment]
I don't think PyQtGraph supports list/numpy array types for Parameters. Should we still try to do the list of dictionaries for the gui_params @samuelgarcia

**Comment by samuelgarcia** [comment]
No pyqtgraph build UI on top on theses parameters and only simple type can be editable.
You cannot give an array nor a list because the widget would be too difficult.
Do you have an example in sorter where you need an array as parameters ?

**Comment by samuelgarcia** [comment]
> Each module should provide an interface of _default_params and _qtgraph_params

I think that should be accessible with a method (get_default_params) that would be constructed from the _qtgraph_params internally. This would avoid to make it twice and errors.

**Comment by colehurwitz31** [comment]
For the BinDatRecordingExtractor, it expects a list of recording_channels. So I wanted to give params for this.

**Comment by samuelgarcia** [comment]
We can this but we need to inject a new "type" in pyqtgraph and implement the QWidget on top on this.

What do you have in mind ? A list of checkbox ? A double list with keep no_keep where item can be drag and drop ?
We need some work for that.

**Comment by colehurwitz31** [comment]
I was thinking we implement of the list of dictionaries still, but instead of using the PyQtGraph parameter, we just implement our own Parameter class and make it simpler and more compatible with different types.

I am not sure how to support lists to be honest since recording_channels might have 100s of fields to fill in! What do you think? We need to have gui_params for the extractors, preprocessing, sorters, and postprocessing to make the gui work.

**Comment by samuelgarcia** [comment]
If this is the only place where a list is necessary I would do this:
modify recording_channels input to accept a list (the normal case) or a str.

In case of str then I would do a ```recording_channels = map(int, recording_channels.plit(' '))```. (or more complicated for more check)

So the recording_channels at GUI level would be a textline where the user would just put manually the list of channels.

**Comment by colehurwitz31** [comment]
Oh, that makes sense. So in the gui_params, we would put the type of recording_channels to be a string. Then we can tokenize and turn that string into a list before creating the BinDatRecordingExtractor.

**Comment by colehurwitz31** [comment]
Also, how can we handle something like a np.dtype? Currently, the BinDatRecordingExtractor requires a dtype to be passed in.

**Comment by colehurwitz31** [comment]
So I have done most of the extractors, but BinDatRecordingExtractor and TrideclousSortingExtractor are tricky because they both have lists... I can put those in as strings for now.

**Comment by alejoe91** [comment]
@colehurwitz31 fixed?

**Comment by alejoe91** [comment]
I believe this is fixed. Of not we should move it to spikesorters
