### ISSUE TITLE
Complete Documentation of Spiketoolkit

### ISSUE THREAD

**Issue by colehurwitz31** [SpikeInterface/spiketoolkit#85]
We should try to have documentation of all the functions and types in spiketoolkit as we do in spikeextractors.

**Comment by samuelgarcia** [comment]
Do you mean docstring everywhere or start a sphinx doc  + a readtheedoc ?
I have tried in zone a put ptach to add some doc (sorters, comparison).
I have not check all other submodule yet.

**Comment by colehurwitz31** [comment]
I think we need to start with docstrings everywhere then we can move to readthedocs. spikeextractors is in pretty good shape, but we probably need to fix the tools.py documention.

I was just trying to add gui_params to the preprocessing module and there is no documentation of parameters and some of the parameter names should really be replaced.

**Comment by colehurwitz31** [comment]
Also, I don't know if you say, but I think it might be best to keep the generate structure of PyQtGraph params (list of dictionaries), but to move away from using it. I made a pull request in spikeextractors discussing this.

**Comment by alejoe91** [comment]
https://github.com/SpikeInterface/spiketoolkit/pull/94

**Comment by alejoe91** [comment]
working on it 
https://github.com/SpikeInterface/spiketoolkit/pulls
