### ISSUE TITLE
GUI Params - Sorters (help needed)

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spiketoolkit#91]
I was hoping to get some help on determining the important parameters for each sorting algorithm so that I can put them in a GUI params list of parameter dictionaries.

I know the important params for herding spikes, but not the other algorithms.

**Comment by samuelgarcia** [comment]
Hi Cole.
I guess that you can put all "_default_params" for all sorter.
Note that for tridesclous, I still need to flatten the list (and also for HS, I think).
No ?

**Comment by colehurwitz31** [comment]
I could try to include all default_params, but I wanted to minimise the number of params in the GUI and try not to have complicated types (yet).

I am planning on having a separate gui_params for each sorter that is in the format of PyQtGraph (list of dictionaries).
