### ISSUE TITLE
whitening

### ISSUE THREAD

**Issue by nahawtho** [SpikeInterface/spiketoolkit#93]
neither st.whiten(sorting) nor sw.lazyfilters.whiten(RXf) (from the  spikewidgets/examples/ground_truth_comparison/ground_truth_comparison.ipynb example) nor WhitenRecording(sorting) from the function definition in st appear to be working. Is there some newer version of writing this function, or am I missing something. Thanks!

**Comment by nahawtho** [comment]
whiten(recording)* is what i meant

**Comment by colehurwitz31** [comment]
Thanks for pointing this out! We forgot to update this notebook for new changes with the interface. The newest commit should fix these issues (you will have to reinstall spikewidgets).

Spikewidgets is a little underdeveloped compared to spikeextractors/spiketoolkit and we are still trying to figure out the best direction for it.

**Comment by alejoe91** [comment]
can we close this? @nahawtho is it working now with the latest spikewidgets?

**Comment by nahawtho** [comment]
Yes, appears to be working. Thank you!
